// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: launcher_configuration/v1/launcher_configuration.proto

package launcher_configurationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgencyDetailed struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev                        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Administrator                 *string                `protobuf:"bytes,2,opt,name=administrator,proto3,oneof" json:"administrator,omitempty"`
	AttemptedLandings             *int32                 `protobuf:"varint,3,opt,name=attempted_landings,json=attemptedLandings,proto3,oneof" json:"attempted_landings,omitempty"`
	AttemptedLandingsPayload      *int32                 `protobuf:"varint,4,opt,name=attempted_landings_payload,json=attemptedLandingsPayload,proto3,oneof" json:"attempted_landings_payload,omitempty"`
	AttemptedLandingsSpacecraft   *int32                 `protobuf:"varint,5,opt,name=attempted_landings_spacecraft,json=attemptedLandingsSpacecraft,proto3,oneof" json:"attempted_landings_spacecraft,omitempty"`
	ConsecutiveSuccessfulLandings *int32                 `protobuf:"varint,6,opt,name=consecutive_successful_landings,json=consecutiveSuccessfulLandings,proto3,oneof" json:"consecutive_successful_landings,omitempty"`
	ConsecutiveSuccessfulLaunches *int32                 `protobuf:"varint,7,opt,name=consecutive_successful_launches,json=consecutiveSuccessfulLaunches,proto3,oneof" json:"consecutive_successful_launches,omitempty"`
	Country                       []*Country             `protobuf:"bytes,8,rep,name=country,proto3" json:"country,omitempty"`
	Description                   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FailedLandings                *int32                 `protobuf:"varint,10,opt,name=failed_landings,json=failedLandings,proto3,oneof" json:"failed_landings,omitempty"`
	FailedLandingsPayload         *int32                 `protobuf:"varint,11,opt,name=failed_landings_payload,json=failedLandingsPayload,proto3,oneof" json:"failed_landings_payload,omitempty"`
	FailedLandingsSpacecraft      *int32                 `protobuf:"varint,12,opt,name=failed_landings_spacecraft,json=failedLandingsSpacecraft,proto3,oneof" json:"failed_landings_spacecraft,omitempty"`
	FailedLaunches                *int32                 `protobuf:"varint,13,opt,name=failed_launches,json=failedLaunches,proto3,oneof" json:"failed_launches,omitempty"`
	Featured                      bool                   `protobuf:"varint,14,opt,name=featured,proto3" json:"featured,omitempty"`
	FoundingYear                  *int32                 `protobuf:"varint,15,opt,name=founding_year,json=foundingYear,proto3,oneof" json:"founding_year,omitempty"`
	Id                            int32                  `protobuf:"varint,16,opt,name=id,proto3" json:"id,omitempty"`
	Image                         *Image                 `protobuf:"bytes,17,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl                       *string                `protobuf:"bytes,18,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	Launchers                     string                 `protobuf:"bytes,19,opt,name=launchers,proto3" json:"launchers,omitempty"`
	Logo                          *Image                 `protobuf:"bytes,20,opt,name=logo,proto3" json:"logo,omitempty"`
	Name                          string                 `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`
	Parent                        *string                `protobuf:"bytes,22,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	PendingLaunches               *int32                 `protobuf:"varint,23,opt,name=pending_launches,json=pendingLaunches,proto3,oneof" json:"pending_launches,omitempty"`
	ResponseMode                  string                 `protobuf:"bytes,24,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SocialLogo                    *Image                 `protobuf:"bytes,25,opt,name=social_logo,json=socialLogo,proto3" json:"social_logo,omitempty"`
	SocialMediaLinks              []*SocialMediaLink     `protobuf:"bytes,26,rep,name=social_media_links,json=socialMediaLinks,proto3" json:"social_media_links,omitempty"`
	Spacecraft                    string                 `protobuf:"bytes,27,opt,name=spacecraft,proto3" json:"spacecraft,omitempty"`
	SuccessfulLandings            *int32                 `protobuf:"varint,28,opt,name=successful_landings,json=successfulLandings,proto3,oneof" json:"successful_landings,omitempty"`
	SuccessfulLandingsPayload     *int32                 `protobuf:"varint,29,opt,name=successful_landings_payload,json=successfulLandingsPayload,proto3,oneof" json:"successful_landings_payload,omitempty"`
	SuccessfulLandingsSpacecraft  *int32                 `protobuf:"varint,30,opt,name=successful_landings_spacecraft,json=successfulLandingsSpacecraft,proto3,oneof" json:"successful_landings_spacecraft,omitempty"`
	SuccessfulLaunches            *int32                 `protobuf:"varint,31,opt,name=successful_launches,json=successfulLaunches,proto3,oneof" json:"successful_launches,omitempty"`
	TotalLaunchCount              *int32                 `protobuf:"varint,32,opt,name=total_launch_count,json=totalLaunchCount,proto3,oneof" json:"total_launch_count,omitempty"`
	Type                          *AgencyType            `protobuf:"bytes,33,opt,name=type,proto3" json:"type,omitempty"`
	Url                           string                 `protobuf:"bytes,34,opt,name=url,proto3" json:"url,omitempty"`
	WikiUrl                       *string                `protobuf:"bytes,35,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AgencyDetailed) Reset() {
	*x = AgencyDetailed{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyDetailed) ProtoMessage() {}

func (x *AgencyDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyDetailed.ProtoReflect.Descriptor instead.
func (*AgencyDetailed) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *AgencyDetailed) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyDetailed) GetAdministrator() string {
	if x != nil && x.Administrator != nil {
		return *x.Administrator
	}
	return ""
}

func (x *AgencyDetailed) GetAttemptedLandings() int32 {
	if x != nil && x.AttemptedLandings != nil {
		return *x.AttemptedLandings
	}
	return 0
}

func (x *AgencyDetailed) GetAttemptedLandingsPayload() int32 {
	if x != nil && x.AttemptedLandingsPayload != nil {
		return *x.AttemptedLandingsPayload
	}
	return 0
}

func (x *AgencyDetailed) GetAttemptedLandingsSpacecraft() int32 {
	if x != nil && x.AttemptedLandingsSpacecraft != nil {
		return *x.AttemptedLandingsSpacecraft
	}
	return 0
}

func (x *AgencyDetailed) GetConsecutiveSuccessfulLandings() int32 {
	if x != nil && x.ConsecutiveSuccessfulLandings != nil {
		return *x.ConsecutiveSuccessfulLandings
	}
	return 0
}

func (x *AgencyDetailed) GetConsecutiveSuccessfulLaunches() int32 {
	if x != nil && x.ConsecutiveSuccessfulLaunches != nil {
		return *x.ConsecutiveSuccessfulLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetCountry() []*Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *AgencyDetailed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AgencyDetailed) GetFailedLandings() int32 {
	if x != nil && x.FailedLandings != nil {
		return *x.FailedLandings
	}
	return 0
}

func (x *AgencyDetailed) GetFailedLandingsPayload() int32 {
	if x != nil && x.FailedLandingsPayload != nil {
		return *x.FailedLandingsPayload
	}
	return 0
}

func (x *AgencyDetailed) GetFailedLandingsSpacecraft() int32 {
	if x != nil && x.FailedLandingsSpacecraft != nil {
		return *x.FailedLandingsSpacecraft
	}
	return 0
}

func (x *AgencyDetailed) GetFailedLaunches() int32 {
	if x != nil && x.FailedLaunches != nil {
		return *x.FailedLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *AgencyDetailed) GetFoundingYear() int32 {
	if x != nil && x.FoundingYear != nil {
		return *x.FoundingYear
	}
	return 0
}

func (x *AgencyDetailed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyDetailed) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *AgencyDetailed) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *AgencyDetailed) GetLaunchers() string {
	if x != nil {
		return x.Launchers
	}
	return ""
}

func (x *AgencyDetailed) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *AgencyDetailed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyDetailed) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *AgencyDetailed) GetPendingLaunches() int32 {
	if x != nil && x.PendingLaunches != nil {
		return *x.PendingLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyDetailed) GetSocialLogo() *Image {
	if x != nil {
		return x.SocialLogo
	}
	return nil
}

func (x *AgencyDetailed) GetSocialMediaLinks() []*SocialMediaLink {
	if x != nil {
		return x.SocialMediaLinks
	}
	return nil
}

func (x *AgencyDetailed) GetSpacecraft() string {
	if x != nil {
		return x.Spacecraft
	}
	return ""
}

func (x *AgencyDetailed) GetSuccessfulLandings() int32 {
	if x != nil && x.SuccessfulLandings != nil {
		return *x.SuccessfulLandings
	}
	return 0
}

func (x *AgencyDetailed) GetSuccessfulLandingsPayload() int32 {
	if x != nil && x.SuccessfulLandingsPayload != nil {
		return *x.SuccessfulLandingsPayload
	}
	return 0
}

func (x *AgencyDetailed) GetSuccessfulLandingsSpacecraft() int32 {
	if x != nil && x.SuccessfulLandingsSpacecraft != nil {
		return *x.SuccessfulLandingsSpacecraft
	}
	return 0
}

func (x *AgencyDetailed) GetSuccessfulLaunches() int32 {
	if x != nil && x.SuccessfulLaunches != nil {
		return *x.SuccessfulLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetTotalLaunchCount() int32 {
	if x != nil && x.TotalLaunchCount != nil {
		return *x.TotalLaunchCount
	}
	return 0
}

func (x *AgencyDetailed) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyDetailed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AgencyDetailed) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type AgencyMini struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,4,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	Type          *AgencyType            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyMini) Reset() {
	*x = AgencyMini{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyMini) ProtoMessage() {}

func (x *AgencyMini) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyMini.ProtoReflect.Descriptor instead.
func (*AgencyMini) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *AgencyMini) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyMini) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyMini) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyMini) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyMini) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyMini) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgencyNormal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Administrator *string                `protobuf:"bytes,2,opt,name=administrator,proto3,oneof" json:"administrator,omitempty"`
	Country       []*Country             `protobuf:"bytes,3,rep,name=country,proto3" json:"country,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Featured      bool                   `protobuf:"varint,5,opt,name=featured,proto3" json:"featured,omitempty"`
	FoundingYear  *int32                 `protobuf:"varint,6,opt,name=founding_year,json=foundingYear,proto3,oneof" json:"founding_year,omitempty"`
	Id            int32                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Image         *Image                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Launchers     string                 `protobuf:"bytes,9,opt,name=launchers,proto3" json:"launchers,omitempty"`
	Logo          *Image                 `protobuf:"bytes,10,opt,name=logo,proto3" json:"logo,omitempty"`
	Name          string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Parent        *string                `protobuf:"bytes,12,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,13,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SocialLogo    *Image                 `protobuf:"bytes,14,opt,name=social_logo,json=socialLogo,proto3" json:"social_logo,omitempty"`
	Spacecraft    string                 `protobuf:"bytes,15,opt,name=spacecraft,proto3" json:"spacecraft,omitempty"`
	Type          *AgencyType            `protobuf:"bytes,16,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,17,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyNormal) Reset() {
	*x = AgencyNormal{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyNormal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyNormal) ProtoMessage() {}

func (x *AgencyNormal) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyNormal.ProtoReflect.Descriptor instead.
func (*AgencyNormal) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *AgencyNormal) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyNormal) GetAdministrator() string {
	if x != nil && x.Administrator != nil {
		return *x.Administrator
	}
	return ""
}

func (x *AgencyNormal) GetCountry() []*Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *AgencyNormal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AgencyNormal) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *AgencyNormal) GetFoundingYear() int32 {
	if x != nil && x.FoundingYear != nil {
		return *x.FoundingYear
	}
	return 0
}

func (x *AgencyNormal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyNormal) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *AgencyNormal) GetLaunchers() string {
	if x != nil {
		return x.Launchers
	}
	return ""
}

func (x *AgencyNormal) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *AgencyNormal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyNormal) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *AgencyNormal) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyNormal) GetSocialLogo() *Image {
	if x != nil {
		return x.SocialLogo
	}
	return nil
}

func (x *AgencyNormal) GetSpacecraft() string {
	if x != nil {
		return x.Spacecraft
	}
	return ""
}

func (x *AgencyNormal) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyNormal) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgencyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyType) Reset() {
	*x = AgencyType{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyType) ProtoMessage() {}

func (x *AgencyType) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyType.ProtoReflect.Descriptor instead.
func (*AgencyType) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *AgencyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Country struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Alpha_2Code             string                 `protobuf:"bytes,1,opt,name=alpha_2_code,json=alpha2Code,proto3" json:"alpha_2_code,omitempty"`
	Alpha_3Code             string                 `protobuf:"bytes,2,opt,name=alpha_3_code,json=alpha3Code,proto3" json:"alpha_3_code,omitempty"`
	Id                      int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NationalityName         string                 `protobuf:"bytes,5,opt,name=nationality_name,json=nationalityName,proto3" json:"nationality_name,omitempty"`
	NationalityNameComposed string                 `protobuf:"bytes,6,opt,name=nationality_name_composed,json=nationalityNameComposed,proto3" json:"nationality_name_composed,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *Country) GetAlpha_2Code() string {
	if x != nil {
		return x.Alpha_2Code
	}
	return ""
}

func (x *Country) GetAlpha_3Code() string {
	if x != nil {
		return x.Alpha_3Code
	}
	return ""
}

func (x *Country) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetNationalityName() string {
	if x != nil {
		return x.NationalityName
	}
	return ""
}

func (x *Country) GetNationalityNameComposed() string {
	if x != nil {
		return x.NationalityNameComposed
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credit        *string                `protobuf:"bytes,1,opt,name=credit,proto3,oneof" json:"credit,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	License       *ImageLicense          `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SingleUse     bool                   `protobuf:"varint,6,opt,name=single_use,json=singleUse,proto3" json:"single_use,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Variants      []*ImageVariant        `protobuf:"bytes,8,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{5}
}

func (x *Image) GetCredit() string {
	if x != nil && x.Credit != nil {
		return *x.Credit
	}
	return ""
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Image) GetLicense() *ImageLicense {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetSingleUse() bool {
	if x != nil {
		return x.SingleUse
	}
	return false
}

func (x *Image) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Image) GetVariants() []*ImageVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ImageLicense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          *string                `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageLicense) Reset() {
	*x = ImageLicense{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageLicense) ProtoMessage() {}

func (x *ImageLicense) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageLicense.ProtoReflect.Descriptor instead.
func (*ImageLicense) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *ImageLicense) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageLicense) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *ImageLicense) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageLicense) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type          *ImageVariantType      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariant) Reset() {
	*x = ImageVariant{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariant) ProtoMessage() {}

func (x *ImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariant.ProtoReflect.Descriptor instead.
func (*ImageVariant) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{7}
}

func (x *ImageVariant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariant) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageVariant) GetType() *ImageVariantType {
	if x != nil {
		return x.Type
	}
	return nil
}

type ImageVariantType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariantType) Reset() {
	*x = ImageVariantType{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariantType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariantType) ProtoMessage() {}

func (x *ImageVariantType) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariantType.ProtoReflect.Descriptor instead.
func (*ImageVariantType) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{8}
}

func (x *ImageVariantType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariantType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LauncherConfiguration struct {
	state                         protoimpl.MessageState          `protogen:"open.v1"`
	Active                        bool                            `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Alias                         string                          `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Apogee                        *float32                        `protobuf:"fixed32,3,opt,name=apogee,proto3,oneof" json:"apogee,omitempty"`
	AttemptedLandings             *int32                          `protobuf:"varint,4,opt,name=attempted_landings,json=attemptedLandings,proto3,oneof" json:"attempted_landings,omitempty"`
	ConsecutiveSuccessfulLandings *int32                          `protobuf:"varint,5,opt,name=consecutive_successful_landings,json=consecutiveSuccessfulLandings,proto3,oneof" json:"consecutive_successful_landings,omitempty"`
	ConsecutiveSuccessfulLaunches *int32                          `protobuf:"varint,6,opt,name=consecutive_successful_launches,json=consecutiveSuccessfulLaunches,proto3,oneof" json:"consecutive_successful_launches,omitempty"`
	Description                   string                          `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Diameter                      *float32                        `protobuf:"fixed32,8,opt,name=diameter,proto3,oneof" json:"diameter,omitempty"`
	FailedLandings                *int32                          `protobuf:"varint,9,opt,name=failed_landings,json=failedLandings,proto3,oneof" json:"failed_landings,omitempty"`
	FailedLaunches                *int32                          `protobuf:"varint,10,opt,name=failed_launches,json=failedLaunches,proto3,oneof" json:"failed_launches,omitempty"`
	Families                      []*LauncherConfigFamilyDetailed `protobuf:"bytes,11,rep,name=families,proto3" json:"families,omitempty"`
	FastestTurnaround             *string                         `protobuf:"bytes,12,opt,name=fastest_turnaround,json=fastestTurnaround,proto3,oneof" json:"fastest_turnaround,omitempty"`
	FullName                      string                          `protobuf:"bytes,13,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	GeoCapacity                   *float32                        `protobuf:"fixed32,14,opt,name=geo_capacity,json=geoCapacity,proto3,oneof" json:"geo_capacity,omitempty"`
	GtoCapacity                   *float32                        `protobuf:"fixed32,15,opt,name=gto_capacity,json=gtoCapacity,proto3,oneof" json:"gto_capacity,omitempty"`
	Id                            int32                           `protobuf:"varint,16,opt,name=id,proto3" json:"id,omitempty"`
	Image                         *Image                          `protobuf:"bytes,17,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl                       *string                         `protobuf:"bytes,18,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	IsPlaceholder                 bool                            `protobuf:"varint,19,opt,name=is_placeholder,json=isPlaceholder,proto3" json:"is_placeholder,omitempty"`
	LaunchCost                    *int32                          `protobuf:"varint,20,opt,name=launch_cost,json=launchCost,proto3,oneof" json:"launch_cost,omitempty"`
	LaunchMass                    *float32                        `protobuf:"fixed32,21,opt,name=launch_mass,json=launchMass,proto3,oneof" json:"launch_mass,omitempty"`
	Length                        *float32                        `protobuf:"fixed32,22,opt,name=length,proto3,oneof" json:"length,omitempty"`
	LeoCapacity                   *float32                        `protobuf:"fixed32,23,opt,name=leo_capacity,json=leoCapacity,proto3,oneof" json:"leo_capacity,omitempty"`
	MaidenFlight                  *string                         `protobuf:"bytes,24,opt,name=maiden_flight,json=maidenFlight,proto3,oneof" json:"maiden_flight,omitempty"`
	Manufacturer                  *AgencyDetailed                 `protobuf:"bytes,25,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	MaxStage                      *int32                          `protobuf:"varint,26,opt,name=max_stage,json=maxStage,proto3,oneof" json:"max_stage,omitempty"`
	MinStage                      *int32                          `protobuf:"varint,27,opt,name=min_stage,json=minStage,proto3,oneof" json:"min_stage,omitempty"`
	Name                          string                          `protobuf:"bytes,28,opt,name=name,proto3" json:"name,omitempty"`
	PendingLaunches               *int32                          `protobuf:"varint,29,opt,name=pending_launches,json=pendingLaunches,proto3,oneof" json:"pending_launches,omitempty"`
	Program                       []*ProgramNormal                `protobuf:"bytes,30,rep,name=program,proto3" json:"program,omitempty"`
	ResponseMode                  string                          `protobuf:"bytes,31,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	Reusable                      bool                            `protobuf:"varint,32,opt,name=reusable,proto3" json:"reusable,omitempty"`
	SsoCapacity                   *float32                        `protobuf:"fixed32,33,opt,name=sso_capacity,json=ssoCapacity,proto3,oneof" json:"sso_capacity,omitempty"`
	SuccessfulLandings            *int32                          `protobuf:"varint,34,opt,name=successful_landings,json=successfulLandings,proto3,oneof" json:"successful_landings,omitempty"`
	SuccessfulLaunches            *int32                          `protobuf:"varint,35,opt,name=successful_launches,json=successfulLaunches,proto3,oneof" json:"successful_launches,omitempty"`
	ToThrust                      *float32                        `protobuf:"fixed32,36,opt,name=to_thrust,json=toThrust,proto3,oneof" json:"to_thrust,omitempty"`
	TotalLaunchCount              *int32                          `protobuf:"varint,37,opt,name=total_launch_count,json=totalLaunchCount,proto3,oneof" json:"total_launch_count,omitempty"`
	Url                           string                          `protobuf:"bytes,38,opt,name=url,proto3" json:"url,omitempty"`
	Variant                       string                          `protobuf:"bytes,39,opt,name=variant,proto3" json:"variant,omitempty"`
	WikiUrl                       *string                         `protobuf:"bytes,40,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *LauncherConfiguration) Reset() {
	*x = LauncherConfiguration{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LauncherConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LauncherConfiguration) ProtoMessage() {}

func (x *LauncherConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LauncherConfiguration.ProtoReflect.Descriptor instead.
func (*LauncherConfiguration) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{9}
}

func (x *LauncherConfiguration) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LauncherConfiguration) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *LauncherConfiguration) GetApogee() float32 {
	if x != nil && x.Apogee != nil {
		return *x.Apogee
	}
	return 0
}

func (x *LauncherConfiguration) GetAttemptedLandings() int32 {
	if x != nil && x.AttemptedLandings != nil {
		return *x.AttemptedLandings
	}
	return 0
}

func (x *LauncherConfiguration) GetConsecutiveSuccessfulLandings() int32 {
	if x != nil && x.ConsecutiveSuccessfulLandings != nil {
		return *x.ConsecutiveSuccessfulLandings
	}
	return 0
}

func (x *LauncherConfiguration) GetConsecutiveSuccessfulLaunches() int32 {
	if x != nil && x.ConsecutiveSuccessfulLaunches != nil {
		return *x.ConsecutiveSuccessfulLaunches
	}
	return 0
}

func (x *LauncherConfiguration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LauncherConfiguration) GetDiameter() float32 {
	if x != nil && x.Diameter != nil {
		return *x.Diameter
	}
	return 0
}

func (x *LauncherConfiguration) GetFailedLandings() int32 {
	if x != nil && x.FailedLandings != nil {
		return *x.FailedLandings
	}
	return 0
}

func (x *LauncherConfiguration) GetFailedLaunches() int32 {
	if x != nil && x.FailedLaunches != nil {
		return *x.FailedLaunches
	}
	return 0
}

func (x *LauncherConfiguration) GetFamilies() []*LauncherConfigFamilyDetailed {
	if x != nil {
		return x.Families
	}
	return nil
}

func (x *LauncherConfiguration) GetFastestTurnaround() string {
	if x != nil && x.FastestTurnaround != nil {
		return *x.FastestTurnaround
	}
	return ""
}

func (x *LauncherConfiguration) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *LauncherConfiguration) GetGeoCapacity() float32 {
	if x != nil && x.GeoCapacity != nil {
		return *x.GeoCapacity
	}
	return 0
}

func (x *LauncherConfiguration) GetGtoCapacity() float32 {
	if x != nil && x.GtoCapacity != nil {
		return *x.GtoCapacity
	}
	return 0
}

func (x *LauncherConfiguration) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LauncherConfiguration) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *LauncherConfiguration) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *LauncherConfiguration) GetIsPlaceholder() bool {
	if x != nil {
		return x.IsPlaceholder
	}
	return false
}

func (x *LauncherConfiguration) GetLaunchCost() int32 {
	if x != nil && x.LaunchCost != nil {
		return *x.LaunchCost
	}
	return 0
}

func (x *LauncherConfiguration) GetLaunchMass() float32 {
	if x != nil && x.LaunchMass != nil {
		return *x.LaunchMass
	}
	return 0
}

func (x *LauncherConfiguration) GetLength() float32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *LauncherConfiguration) GetLeoCapacity() float32 {
	if x != nil && x.LeoCapacity != nil {
		return *x.LeoCapacity
	}
	return 0
}

func (x *LauncherConfiguration) GetMaidenFlight() string {
	if x != nil && x.MaidenFlight != nil {
		return *x.MaidenFlight
	}
	return ""
}

func (x *LauncherConfiguration) GetManufacturer() *AgencyDetailed {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *LauncherConfiguration) GetMaxStage() int32 {
	if x != nil && x.MaxStage != nil {
		return *x.MaxStage
	}
	return 0
}

func (x *LauncherConfiguration) GetMinStage() int32 {
	if x != nil && x.MinStage != nil {
		return *x.MinStage
	}
	return 0
}

func (x *LauncherConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LauncherConfiguration) GetPendingLaunches() int32 {
	if x != nil && x.PendingLaunches != nil {
		return *x.PendingLaunches
	}
	return 0
}

func (x *LauncherConfiguration) GetProgram() []*ProgramNormal {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *LauncherConfiguration) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *LauncherConfiguration) GetReusable() bool {
	if x != nil {
		return x.Reusable
	}
	return false
}

func (x *LauncherConfiguration) GetSsoCapacity() float32 {
	if x != nil && x.SsoCapacity != nil {
		return *x.SsoCapacity
	}
	return 0
}

func (x *LauncherConfiguration) GetSuccessfulLandings() int32 {
	if x != nil && x.SuccessfulLandings != nil {
		return *x.SuccessfulLandings
	}
	return 0
}

func (x *LauncherConfiguration) GetSuccessfulLaunches() int32 {
	if x != nil && x.SuccessfulLaunches != nil {
		return *x.SuccessfulLaunches
	}
	return 0
}

func (x *LauncherConfiguration) GetToThrust() float32 {
	if x != nil && x.ToThrust != nil {
		return *x.ToThrust
	}
	return 0
}

func (x *LauncherConfiguration) GetTotalLaunchCount() int32 {
	if x != nil && x.TotalLaunchCount != nil {
		return *x.TotalLaunchCount
	}
	return 0
}

func (x *LauncherConfiguration) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LauncherConfiguration) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *LauncherConfiguration) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type LauncherConfigFamilyDetailed struct {
	state                         protoimpl.MessageState      `protogen:"open.v1"`
	Active                        bool                        `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	AttemptedLandings             *int32                      `protobuf:"varint,2,opt,name=attempted_landings,json=attemptedLandings,proto3,oneof" json:"attempted_landings,omitempty"`
	ConsecutiveSuccessfulLandings *int32                      `protobuf:"varint,3,opt,name=consecutive_successful_landings,json=consecutiveSuccessfulLandings,proto3,oneof" json:"consecutive_successful_landings,omitempty"`
	ConsecutiveSuccessfulLaunches *int32                      `protobuf:"varint,4,opt,name=consecutive_successful_launches,json=consecutiveSuccessfulLaunches,proto3,oneof" json:"consecutive_successful_launches,omitempty"`
	Description                   string                      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	FailedLandings                *int32                      `protobuf:"varint,6,opt,name=failed_landings,json=failedLandings,proto3,oneof" json:"failed_landings,omitempty"`
	FailedLaunches                *int32                      `protobuf:"varint,7,opt,name=failed_launches,json=failedLaunches,proto3,oneof" json:"failed_launches,omitempty"`
	Id                            int32                       `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	MaidenFlight                  *string                     `protobuf:"bytes,9,opt,name=maiden_flight,json=maidenFlight,proto3,oneof" json:"maiden_flight,omitempty"`
	Manufacturer                  []*AgencyDetailed           `protobuf:"bytes,10,rep,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Name                          string                      `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Parent                        *LauncherConfigFamilyNormal `protobuf:"bytes,12,opt,name=parent,proto3" json:"parent,omitempty"`
	PendingLaunches               *int32                      `protobuf:"varint,13,opt,name=pending_launches,json=pendingLaunches,proto3,oneof" json:"pending_launches,omitempty"`
	ResponseMode                  string                      `protobuf:"bytes,14,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SuccessfulLandings            *int32                      `protobuf:"varint,15,opt,name=successful_landings,json=successfulLandings,proto3,oneof" json:"successful_landings,omitempty"`
	SuccessfulLaunches            *int32                      `protobuf:"varint,16,opt,name=successful_launches,json=successfulLaunches,proto3,oneof" json:"successful_launches,omitempty"`
	TotalLaunchCount              *int32                      `protobuf:"varint,17,opt,name=total_launch_count,json=totalLaunchCount,proto3,oneof" json:"total_launch_count,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *LauncherConfigFamilyDetailed) Reset() {
	*x = LauncherConfigFamilyDetailed{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LauncherConfigFamilyDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LauncherConfigFamilyDetailed) ProtoMessage() {}

func (x *LauncherConfigFamilyDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LauncherConfigFamilyDetailed.ProtoReflect.Descriptor instead.
func (*LauncherConfigFamilyDetailed) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{10}
}

func (x *LauncherConfigFamilyDetailed) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LauncherConfigFamilyDetailed) GetAttemptedLandings() int32 {
	if x != nil && x.AttemptedLandings != nil {
		return *x.AttemptedLandings
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetConsecutiveSuccessfulLandings() int32 {
	if x != nil && x.ConsecutiveSuccessfulLandings != nil {
		return *x.ConsecutiveSuccessfulLandings
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetConsecutiveSuccessfulLaunches() int32 {
	if x != nil && x.ConsecutiveSuccessfulLaunches != nil {
		return *x.ConsecutiveSuccessfulLaunches
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LauncherConfigFamilyDetailed) GetFailedLandings() int32 {
	if x != nil && x.FailedLandings != nil {
		return *x.FailedLandings
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetFailedLaunches() int32 {
	if x != nil && x.FailedLaunches != nil {
		return *x.FailedLaunches
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetMaidenFlight() string {
	if x != nil && x.MaidenFlight != nil {
		return *x.MaidenFlight
	}
	return ""
}

func (x *LauncherConfigFamilyDetailed) GetManufacturer() []*AgencyDetailed {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *LauncherConfigFamilyDetailed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LauncherConfigFamilyDetailed) GetParent() *LauncherConfigFamilyNormal {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *LauncherConfigFamilyDetailed) GetPendingLaunches() int32 {
	if x != nil && x.PendingLaunches != nil {
		return *x.PendingLaunches
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *LauncherConfigFamilyDetailed) GetSuccessfulLandings() int32 {
	if x != nil && x.SuccessfulLandings != nil {
		return *x.SuccessfulLandings
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetSuccessfulLaunches() int32 {
	if x != nil && x.SuccessfulLaunches != nil {
		return *x.SuccessfulLaunches
	}
	return 0
}

func (x *LauncherConfigFamilyDetailed) GetTotalLaunchCount() int32 {
	if x != nil && x.TotalLaunchCount != nil {
		return *x.TotalLaunchCount
	}
	return 0
}

type LauncherConfigFamilyMini struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,3,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LauncherConfigFamilyMini) Reset() {
	*x = LauncherConfigFamilyMini{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LauncherConfigFamilyMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LauncherConfigFamilyMini) ProtoMessage() {}

func (x *LauncherConfigFamilyMini) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LauncherConfigFamilyMini.ProtoReflect.Descriptor instead.
func (*LauncherConfigFamilyMini) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{11}
}

func (x *LauncherConfigFamilyMini) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LauncherConfigFamilyMini) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LauncherConfigFamilyMini) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

type LauncherConfigFamilyNormal struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            int32                     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Manufacturer  []*AgencyNormal           `protobuf:"bytes,2,rep,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Name          string                    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Parent        *LauncherConfigFamilyMini `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	ResponseMode  string                    `protobuf:"bytes,5,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LauncherConfigFamilyNormal) Reset() {
	*x = LauncherConfigFamilyNormal{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LauncherConfigFamilyNormal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LauncherConfigFamilyNormal) ProtoMessage() {}

func (x *LauncherConfigFamilyNormal) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LauncherConfigFamilyNormal.ProtoReflect.Descriptor instead.
func (*LauncherConfigFamilyNormal) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{12}
}

func (x *LauncherConfigFamilyNormal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LauncherConfigFamilyNormal) GetManufacturer() []*AgencyNormal {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *LauncherConfigFamilyNormal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LauncherConfigFamilyNormal) GetParent() *LauncherConfigFamilyMini {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *LauncherConfigFamilyNormal) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

type MissionPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agency        *AgencyMini            `protobuf:"bytes,1,opt,name=agency,proto3" json:"agency,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,6,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionPatch) Reset() {
	*x = MissionPatch{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionPatch) ProtoMessage() {}

func (x *MissionPatch) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionPatch.ProtoReflect.Descriptor instead.
func (*MissionPatch) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{13}
}

func (x *MissionPatch) GetAgency() *AgencyMini {
	if x != nil {
		return x.Agency
	}
	return nil
}

func (x *MissionPatch) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MissionPatch) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MissionPatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MissionPatch) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MissionPatch) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

type ProgramNormal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Agencies       []*AgencyMini          `protobuf:"bytes,1,rep,name=agencies,proto3" json:"agencies,omitempty"`
	Description    *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	EndDate        *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Id             int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Image          *Image                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl        *string                `protobuf:"bytes,6,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	MissionPatches []*MissionPatch        `protobuf:"bytes,7,rep,name=mission_patches,json=missionPatches,proto3" json:"mission_patches,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode   string                 `protobuf:"bytes,9,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	StartDate      *string                `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	Type           *ProgramType           `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Url            string                 `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	WikiUrl        *string                `protobuf:"bytes,13,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgramNormal) Reset() {
	*x = ProgramNormal{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramNormal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramNormal) ProtoMessage() {}

func (x *ProgramNormal) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramNormal.ProtoReflect.Descriptor instead.
func (*ProgramNormal) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{14}
}

func (x *ProgramNormal) GetAgencies() []*AgencyMini {
	if x != nil {
		return x.Agencies
	}
	return nil
}

func (x *ProgramNormal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProgramNormal) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *ProgramNormal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramNormal) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ProgramNormal) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *ProgramNormal) GetMissionPatches() []*MissionPatch {
	if x != nil {
		return x.MissionPatches
	}
	return nil
}

func (x *ProgramNormal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramNormal) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *ProgramNormal) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *ProgramNormal) GetType() *ProgramType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ProgramNormal) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProgramNormal) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type ProgramType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramType) Reset() {
	*x = ProgramType{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramType) ProtoMessage() {}

func (x *ProgramType) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramType.ProtoReflect.Descriptor instead.
func (*ProgramType) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{15}
}

func (x *ProgramType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SocialMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Logo          *Image                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMedia) Reset() {
	*x = SocialMedia{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMedia) ProtoMessage() {}

func (x *SocialMedia) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMedia.ProtoReflect.Descriptor instead.
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{16}
}

func (x *SocialMedia) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMedia) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *SocialMedia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SocialMedia) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type SocialMediaLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SocialMedia   *SocialMedia           `protobuf:"bytes,2,opt,name=social_media,json=socialMedia,proto3" json:"social_media,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMediaLink) Reset() {
	*x = SocialMediaLink{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMediaLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMediaLink) ProtoMessage() {}

func (x *SocialMediaLink) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMediaLink.ProtoReflect.Descriptor instead.
func (*SocialMediaLink) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{17}
}

func (x *SocialMediaLink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMediaLink) GetSocialMedia() *SocialMedia {
	if x != nil {
		return x.SocialMedia
	}
	return nil
}

func (x *SocialMediaLink) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ListLauncherConfigurationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLauncherConfigurationsRequest) Reset() {
	*x = ListLauncherConfigurationsRequest{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLauncherConfigurationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLauncherConfigurationsRequest) ProtoMessage() {}

func (x *ListLauncherConfigurationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLauncherConfigurationsRequest.ProtoReflect.Descriptor instead.
func (*ListLauncherConfigurationsRequest) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{18}
}

func (x *ListLauncherConfigurationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLauncherConfigurationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListLauncherConfigurationsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListLauncherConfigurationsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListLauncherConfigurationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Count         int32                    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                   `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                   `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*LauncherConfiguration `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLauncherConfigurationsResponse) Reset() {
	*x = ListLauncherConfigurationsResponse{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLauncherConfigurationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLauncherConfigurationsResponse) ProtoMessage() {}

func (x *ListLauncherConfigurationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLauncherConfigurationsResponse.ProtoReflect.Descriptor instead.
func (*ListLauncherConfigurationsResponse) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{19}
}

func (x *ListLauncherConfigurationsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListLauncherConfigurationsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListLauncherConfigurationsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListLauncherConfigurationsResponse) GetResults() []*LauncherConfiguration {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetLauncherConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLauncherConfigurationRequest) Reset() {
	*x = GetLauncherConfigurationRequest{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLauncherConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLauncherConfigurationRequest) ProtoMessage() {}

func (x *GetLauncherConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLauncherConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetLauncherConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{20}
}

func (x *GetLauncherConfigurationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLauncherConfigurationRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetLauncherConfigurationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LauncherConfiguration *LauncherConfiguration `protobuf:"bytes,1,opt,name=launcher_configuration,json=launcherConfiguration,proto3" json:"launcher_configuration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetLauncherConfigurationResponse) Reset() {
	*x = GetLauncherConfigurationResponse{}
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLauncherConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLauncherConfigurationResponse) ProtoMessage() {}

func (x *GetLauncherConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLauncherConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetLauncherConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP(), []int{21}
}

func (x *GetLauncherConfigurationResponse) GetLauncherConfiguration() *LauncherConfiguration {
	if x != nil {
		return x.LauncherConfiguration
	}
	return nil
}

var File_launcher_configuration_v1_launcher_configuration_proto protoreflect.FileDescriptor

const file_launcher_configuration_v1_launcher_configuration_proto_rawDesc = "" +
	"\n" +
	"6launcher_configuration/v1/launcher_configuration.proto\x12\x19launcher_configuration.v1\"\xca\x11\n" +
	"\x0eAgencyDetailed\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12)\n" +
	"\radministrator\x18\x02 \x01(\tH\x00R\radministrator\x88\x01\x01\x122\n" +
	"\x12attempted_landings\x18\x03 \x01(\x05H\x01R\x11attemptedLandings\x88\x01\x01\x12A\n" +
	"\x1aattempted_landings_payload\x18\x04 \x01(\x05H\x02R\x18attemptedLandingsPayload\x88\x01\x01\x12G\n" +
	"\x1dattempted_landings_spacecraft\x18\x05 \x01(\x05H\x03R\x1battemptedLandingsSpacecraft\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_landings\x18\x06 \x01(\x05H\x04R\x1dconsecutiveSuccessfulLandings\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_launches\x18\a \x01(\x05H\x05R\x1dconsecutiveSuccessfulLaunches\x88\x01\x01\x12<\n" +
	"\acountry\x18\b \x03(\v2\".launcher_configuration.v1.CountryR\acountry\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x06R\vdescription\x88\x01\x01\x12,\n" +
	"\x0ffailed_landings\x18\n" +
	" \x01(\x05H\aR\x0efailedLandings\x88\x01\x01\x12;\n" +
	"\x17failed_landings_payload\x18\v \x01(\x05H\bR\x15failedLandingsPayload\x88\x01\x01\x12A\n" +
	"\x1afailed_landings_spacecraft\x18\f \x01(\x05H\tR\x18failedLandingsSpacecraft\x88\x01\x01\x12,\n" +
	"\x0ffailed_launches\x18\r \x01(\x05H\n" +
	"R\x0efailedLaunches\x88\x01\x01\x12\x1a\n" +
	"\bfeatured\x18\x0e \x01(\bR\bfeatured\x12(\n" +
	"\rfounding_year\x18\x0f \x01(\x05H\vR\ffoundingYear\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x10 \x01(\x05R\x02id\x126\n" +
	"\x05image\x18\x11 \x01(\v2 .launcher_configuration.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\x12 \x01(\tH\fR\ainfoUrl\x88\x01\x01\x12\x1c\n" +
	"\tlaunchers\x18\x13 \x01(\tR\tlaunchers\x124\n" +
	"\x04logo\x18\x14 \x01(\v2 .launcher_configuration.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\x15 \x01(\tR\x04name\x12\x1b\n" +
	"\x06parent\x18\x16 \x01(\tH\rR\x06parent\x88\x01\x01\x12.\n" +
	"\x10pending_launches\x18\x17 \x01(\x05H\x0eR\x0fpendingLaunches\x88\x01\x01\x12#\n" +
	"\rresponse_mode\x18\x18 \x01(\tR\fresponseMode\x12A\n" +
	"\vsocial_logo\x18\x19 \x01(\v2 .launcher_configuration.v1.ImageR\n" +
	"socialLogo\x12X\n" +
	"\x12social_media_links\x18\x1a \x03(\v2*.launcher_configuration.v1.SocialMediaLinkR\x10socialMediaLinks\x12\x1e\n" +
	"\n" +
	"spacecraft\x18\x1b \x01(\tR\n" +
	"spacecraft\x124\n" +
	"\x13successful_landings\x18\x1c \x01(\x05H\x0fR\x12successfulLandings\x88\x01\x01\x12C\n" +
	"\x1bsuccessful_landings_payload\x18\x1d \x01(\x05H\x10R\x19successfulLandingsPayload\x88\x01\x01\x12I\n" +
	"\x1esuccessful_landings_spacecraft\x18\x1e \x01(\x05H\x11R\x1csuccessfulLandingsSpacecraft\x88\x01\x01\x124\n" +
	"\x13successful_launches\x18\x1f \x01(\x05H\x12R\x12successfulLaunches\x88\x01\x01\x121\n" +
	"\x12total_launch_count\x18  \x01(\x05H\x13R\x10totalLaunchCount\x88\x01\x01\x129\n" +
	"\x04type\x18! \x01(\v2%.launcher_configuration.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\" \x01(\tR\x03url\x12\x1e\n" +
	"\bwiki_url\x18# \x01(\tH\x14R\awikiUrl\x88\x01\x01B\x10\n" +
	"\x0e_administratorB\x15\n" +
	"\x13_attempted_landingsB\x1d\n" +
	"\x1b_attempted_landings_payloadB \n" +
	"\x1e_attempted_landings_spacecraftB\"\n" +
	" _consecutive_successful_landingsB\"\n" +
	" _consecutive_successful_launchesB\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_failed_landingsB\x1a\n" +
	"\x18_failed_landings_payloadB\x1d\n" +
	"\x1b_failed_landings_spacecraftB\x12\n" +
	"\x10_failed_launchesB\x10\n" +
	"\x0e_founding_yearB\v\n" +
	"\t_info_urlB\t\n" +
	"\a_parentB\x13\n" +
	"\x11_pending_launchesB\x16\n" +
	"\x14_successful_landingsB\x1e\n" +
	"\x1c_successful_landings_payloadB!\n" +
	"\x1f_successful_landings_spacecraftB\x16\n" +
	"\x14_successful_launchesB\x15\n" +
	"\x13_total_launch_countB\v\n" +
	"\t_wiki_url\"\xba\x01\n" +
	"\n" +
	"AgencyMini\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\x04 \x01(\tR\fresponseMode\x129\n" +
	"\x04type\x18\x05 \x01(\v2%.launcher_configuration.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"\xdd\x05\n" +
	"\fAgencyNormal\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12)\n" +
	"\radministrator\x18\x02 \x01(\tH\x00R\radministrator\x88\x01\x01\x12<\n" +
	"\acountry\x18\x03 \x03(\v2\".launcher_configuration.v1.CountryR\acountry\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bfeatured\x18\x05 \x01(\bR\bfeatured\x12(\n" +
	"\rfounding_year\x18\x06 \x01(\x05H\x02R\ffoundingYear\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\a \x01(\x05R\x02id\x126\n" +
	"\x05image\x18\b \x01(\v2 .launcher_configuration.v1.ImageR\x05image\x12\x1c\n" +
	"\tlaunchers\x18\t \x01(\tR\tlaunchers\x124\n" +
	"\x04logo\x18\n" +
	" \x01(\v2 .launcher_configuration.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12\x1b\n" +
	"\x06parent\x18\f \x01(\tH\x03R\x06parent\x88\x01\x01\x12#\n" +
	"\rresponse_mode\x18\r \x01(\tR\fresponseMode\x12A\n" +
	"\vsocial_logo\x18\x0e \x01(\v2 .launcher_configuration.v1.ImageR\n" +
	"socialLogo\x12\x1e\n" +
	"\n" +
	"spacecraft\x18\x0f \x01(\tR\n" +
	"spacecraft\x129\n" +
	"\x04type\x18\x10 \x01(\v2%.launcher_configuration.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x11 \x01(\tR\x03urlB\x10\n" +
	"\x0e_administratorB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_founding_yearB\t\n" +
	"\a_parent\"0\n" +
	"\n" +
	"AgencyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd8\x01\n" +
	"\aCountry\x12 \n" +
	"\falpha_2_code\x18\x01 \x01(\tR\n" +
	"alpha2Code\x12 \n" +
	"\falpha_3_code\x18\x02 \x01(\tR\n" +
	"alpha3Code\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x10nationality_name\x18\x05 \x01(\tR\x0fnationalityName\x12:\n" +
	"\x19nationality_name_composed\x18\x06 \x01(\tR\x17nationalityNameComposed\"\xbc\x02\n" +
	"\x05Image\x12\x1b\n" +
	"\x06credit\x18\x01 \x01(\tH\x00R\x06credit\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12A\n" +
	"\alicense\x18\x04 \x01(\v2'.launcher_configuration.v1.ImageLicenseR\alicense\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"single_use\x18\x06 \x01(\bR\tsingleUse\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x12C\n" +
	"\bvariants\x18\b \x03(\v2'.launcher_configuration.v1.ImageVariantR\bvariantsB\t\n" +
	"\a_credit\"p\n" +
	"\fImageLicense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04link\x18\x02 \x01(\tH\x00R\x04link\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB\a\n" +
	"\x05_link\"|\n" +
	"\fImageVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12?\n" +
	"\x04type\x18\x03 \x01(\v2+.launcher_configuration.v1.ImageVariantTypeR\x04type\"6\n" +
	"\x10ImageVariantType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xf7\x10\n" +
	"\x15LauncherConfiguration\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1b\n" +
	"\x06apogee\x18\x03 \x01(\x02H\x00R\x06apogee\x88\x01\x01\x122\n" +
	"\x12attempted_landings\x18\x04 \x01(\x05H\x01R\x11attemptedLandings\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_landings\x18\x05 \x01(\x05H\x02R\x1dconsecutiveSuccessfulLandings\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_launches\x18\x06 \x01(\x05H\x03R\x1dconsecutiveSuccessfulLaunches\x88\x01\x01\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1f\n" +
	"\bdiameter\x18\b \x01(\x02H\x04R\bdiameter\x88\x01\x01\x12,\n" +
	"\x0ffailed_landings\x18\t \x01(\x05H\x05R\x0efailedLandings\x88\x01\x01\x12,\n" +
	"\x0ffailed_launches\x18\n" +
	" \x01(\x05H\x06R\x0efailedLaunches\x88\x01\x01\x12S\n" +
	"\bfamilies\x18\v \x03(\v27.launcher_configuration.v1.LauncherConfigFamilyDetailedR\bfamilies\x122\n" +
	"\x12fastest_turnaround\x18\f \x01(\tH\aR\x11fastestTurnaround\x88\x01\x01\x12\x1b\n" +
	"\tfull_name\x18\r \x01(\tR\bfullName\x12&\n" +
	"\fgeo_capacity\x18\x0e \x01(\x02H\bR\vgeoCapacity\x88\x01\x01\x12&\n" +
	"\fgto_capacity\x18\x0f \x01(\x02H\tR\vgtoCapacity\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x10 \x01(\x05R\x02id\x126\n" +
	"\x05image\x18\x11 \x01(\v2 .launcher_configuration.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\x12 \x01(\tH\n" +
	"R\ainfoUrl\x88\x01\x01\x12%\n" +
	"\x0eis_placeholder\x18\x13 \x01(\bR\risPlaceholder\x12$\n" +
	"\vlaunch_cost\x18\x14 \x01(\x05H\vR\n" +
	"launchCost\x88\x01\x01\x12$\n" +
	"\vlaunch_mass\x18\x15 \x01(\x02H\fR\n" +
	"launchMass\x88\x01\x01\x12\x1b\n" +
	"\x06length\x18\x16 \x01(\x02H\rR\x06length\x88\x01\x01\x12&\n" +
	"\fleo_capacity\x18\x17 \x01(\x02H\x0eR\vleoCapacity\x88\x01\x01\x12(\n" +
	"\rmaiden_flight\x18\x18 \x01(\tH\x0fR\fmaidenFlight\x88\x01\x01\x12M\n" +
	"\fmanufacturer\x18\x19 \x01(\v2).launcher_configuration.v1.AgencyDetailedR\fmanufacturer\x12 \n" +
	"\tmax_stage\x18\x1a \x01(\x05H\x10R\bmaxStage\x88\x01\x01\x12 \n" +
	"\tmin_stage\x18\x1b \x01(\x05H\x11R\bminStage\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x1c \x01(\tR\x04name\x12.\n" +
	"\x10pending_launches\x18\x1d \x01(\x05H\x12R\x0fpendingLaunches\x88\x01\x01\x12B\n" +
	"\aprogram\x18\x1e \x03(\v2(.launcher_configuration.v1.ProgramNormalR\aprogram\x12#\n" +
	"\rresponse_mode\x18\x1f \x01(\tR\fresponseMode\x12\x1a\n" +
	"\breusable\x18  \x01(\bR\breusable\x12&\n" +
	"\fsso_capacity\x18! \x01(\x02H\x13R\vssoCapacity\x88\x01\x01\x124\n" +
	"\x13successful_landings\x18\" \x01(\x05H\x14R\x12successfulLandings\x88\x01\x01\x124\n" +
	"\x13successful_launches\x18# \x01(\x05H\x15R\x12successfulLaunches\x88\x01\x01\x12 \n" +
	"\tto_thrust\x18$ \x01(\x02H\x16R\btoThrust\x88\x01\x01\x121\n" +
	"\x12total_launch_count\x18% \x01(\x05H\x17R\x10totalLaunchCount\x88\x01\x01\x12\x10\n" +
	"\x03url\x18& \x01(\tR\x03url\x12\x18\n" +
	"\avariant\x18' \x01(\tR\avariant\x12\x1e\n" +
	"\bwiki_url\x18( \x01(\tH\x18R\awikiUrl\x88\x01\x01B\t\n" +
	"\a_apogeeB\x15\n" +
	"\x13_attempted_landingsB\"\n" +
	" _consecutive_successful_landingsB\"\n" +
	" _consecutive_successful_launchesB\v\n" +
	"\t_diameterB\x12\n" +
	"\x10_failed_landingsB\x12\n" +
	"\x10_failed_launchesB\x15\n" +
	"\x13_fastest_turnaroundB\x0f\n" +
	"\r_geo_capacityB\x0f\n" +
	"\r_gto_capacityB\v\n" +
	"\t_info_urlB\x0e\n" +
	"\f_launch_costB\x0e\n" +
	"\f_launch_massB\t\n" +
	"\a_lengthB\x0f\n" +
	"\r_leo_capacityB\x10\n" +
	"\x0e_maiden_flightB\f\n" +
	"\n" +
	"_max_stageB\f\n" +
	"\n" +
	"_min_stageB\x13\n" +
	"\x11_pending_launchesB\x0f\n" +
	"\r_sso_capacityB\x16\n" +
	"\x14_successful_landingsB\x16\n" +
	"\x14_successful_launchesB\f\n" +
	"\n" +
	"_to_thrustB\x15\n" +
	"\x13_total_launch_countB\v\n" +
	"\t_wiki_url\"\xd7\b\n" +
	"\x1cLauncherConfigFamilyDetailed\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x122\n" +
	"\x12attempted_landings\x18\x02 \x01(\x05H\x00R\x11attemptedLandings\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_landings\x18\x03 \x01(\x05H\x01R\x1dconsecutiveSuccessfulLandings\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_launches\x18\x04 \x01(\x05H\x02R\x1dconsecutiveSuccessfulLaunches\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12,\n" +
	"\x0ffailed_landings\x18\x06 \x01(\x05H\x03R\x0efailedLandings\x88\x01\x01\x12,\n" +
	"\x0ffailed_launches\x18\a \x01(\x05H\x04R\x0efailedLaunches\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\b \x01(\x05R\x02id\x12(\n" +
	"\rmaiden_flight\x18\t \x01(\tH\x05R\fmaidenFlight\x88\x01\x01\x12M\n" +
	"\fmanufacturer\x18\n" +
	" \x03(\v2).launcher_configuration.v1.AgencyDetailedR\fmanufacturer\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12M\n" +
	"\x06parent\x18\f \x01(\v25.launcher_configuration.v1.LauncherConfigFamilyNormalR\x06parent\x12.\n" +
	"\x10pending_launches\x18\r \x01(\x05H\x06R\x0fpendingLaunches\x88\x01\x01\x12#\n" +
	"\rresponse_mode\x18\x0e \x01(\tR\fresponseMode\x124\n" +
	"\x13successful_landings\x18\x0f \x01(\x05H\aR\x12successfulLandings\x88\x01\x01\x124\n" +
	"\x13successful_launches\x18\x10 \x01(\x05H\bR\x12successfulLaunches\x88\x01\x01\x121\n" +
	"\x12total_launch_count\x18\x11 \x01(\x05H\tR\x10totalLaunchCount\x88\x01\x01B\x15\n" +
	"\x13_attempted_landingsB\"\n" +
	" _consecutive_successful_landingsB\"\n" +
	" _consecutive_successful_launchesB\x12\n" +
	"\x10_failed_landingsB\x12\n" +
	"\x10_failed_launchesB\x10\n" +
	"\x0e_maiden_flightB\x13\n" +
	"\x11_pending_launchesB\x16\n" +
	"\x14_successful_landingsB\x16\n" +
	"\x14_successful_launchesB\x15\n" +
	"\x13_total_launch_count\"c\n" +
	"\x18LauncherConfigFamilyMini\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\x03 \x01(\tR\fresponseMode\"\xff\x01\n" +
	"\x1aLauncherConfigFamilyNormal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12K\n" +
	"\fmanufacturer\x18\x02 \x03(\v2'.launcher_configuration.v1.AgencyNormalR\fmanufacturer\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12K\n" +
	"\x06parent\x18\x04 \x01(\v23.launcher_configuration.v1.LauncherConfigFamilyMiniR\x06parent\x12#\n" +
	"\rresponse_mode\x18\x05 \x01(\tR\fresponseMode\"\xcf\x01\n" +
	"\fMissionPatch\x12=\n" +
	"\x06agency\x18\x01 \x01(\v2%.launcher_configuration.v1.AgencyMiniR\x06agency\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12#\n" +
	"\rresponse_mode\x18\x06 \x01(\tR\fresponseMode\"\xe4\x04\n" +
	"\rProgramNormal\x12A\n" +
	"\bagencies\x18\x01 \x03(\v2%.launcher_configuration.v1.AgencyMiniR\bagencies\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\tH\x01R\aendDate\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\x126\n" +
	"\x05image\x18\x05 \x01(\v2 .launcher_configuration.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\x06 \x01(\tH\x02R\ainfoUrl\x88\x01\x01\x12P\n" +
	"\x0fmission_patches\x18\a \x03(\v2'.launcher_configuration.v1.MissionPatchR\x0emissionPatches\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\t \x01(\tR\fresponseMode\x12\"\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\tH\x03R\tstartDate\x88\x01\x01\x12:\n" +
	"\x04type\x18\v \x01(\v2&.launcher_configuration.v1.ProgramTypeR\x04type\x12\x10\n" +
	"\x03url\x18\f \x01(\tR\x03url\x12\x1e\n" +
	"\bwiki_url\x18\r \x01(\tH\x04R\awikiUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_end_dateB\v\n" +
	"\t_info_urlB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_wiki_url\"1\n" +
	"\vProgramType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x86\x01\n" +
	"\vSocialMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\x04logo\x18\x02 \x01(\v2 .launcher_configuration.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"\x8b\x01\n" +
	"\x0fSocialMediaLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12I\n" +
	"\fsocial_media\x18\x02 \x01(\v2&.launcher_configuration.v1.SocialMediaR\vsocialMedia\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"}\n" +
	"!ListLauncherConfigurationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\xb6\x01\n" +
	"\"ListLauncherConfigurationsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12J\n" +
	"\aresults\x18\x04 \x03(\v20.launcher_configuration.v1.LauncherConfigurationR\aresults\"E\n" +
	"\x1fGetLauncherConfigurationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"\x8b\x01\n" +
	" GetLauncherConfigurationResponse\x12g\n" +
	"\x16launcher_configuration\x18\x01 \x01(\v20.launcher_configuration.v1.LauncherConfigurationR\x15launcherConfiguration2\xd0\x02\n" +
	"\x1cLauncherConfigurationService\x12\x99\x01\n" +
	"\x1aListLauncherConfigurations\x12<.launcher_configuration.v1.ListLauncherConfigurationsRequest\x1a=.launcher_configuration.v1.ListLauncherConfigurationsResponse\x12\x93\x01\n" +
	"\x18GetLauncherConfiguration\x12:.launcher_configuration.v1.GetLauncherConfigurationRequest\x1a;.launcher_configuration.v1.GetLauncherConfigurationResponseBVZTcom.gitlab/pobochiigo/bhole/proto/launcher_configuration/v1;launcher_configurationv1b\x06proto3"

var (
	file_launcher_configuration_v1_launcher_configuration_proto_rawDescOnce sync.Once
	file_launcher_configuration_v1_launcher_configuration_proto_rawDescData []byte
)

func file_launcher_configuration_v1_launcher_configuration_proto_rawDescGZIP() []byte {
	file_launcher_configuration_v1_launcher_configuration_proto_rawDescOnce.Do(func() {
		file_launcher_configuration_v1_launcher_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_launcher_configuration_v1_launcher_configuration_proto_rawDesc), len(file_launcher_configuration_v1_launcher_configuration_proto_rawDesc)))
	})
	return file_launcher_configuration_v1_launcher_configuration_proto_rawDescData
}

var file_launcher_configuration_v1_launcher_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_launcher_configuration_v1_launcher_configuration_proto_goTypes = []any{
	(*AgencyDetailed)(nil),                     // 0: launcher_configuration.v1.AgencyDetailed
	(*AgencyMini)(nil),                         // 1: launcher_configuration.v1.AgencyMini
	(*AgencyNormal)(nil),                       // 2: launcher_configuration.v1.AgencyNormal
	(*AgencyType)(nil),                         // 3: launcher_configuration.v1.AgencyType
	(*Country)(nil),                            // 4: launcher_configuration.v1.Country
	(*Image)(nil),                              // 5: launcher_configuration.v1.Image
	(*ImageLicense)(nil),                       // 6: launcher_configuration.v1.ImageLicense
	(*ImageVariant)(nil),                       // 7: launcher_configuration.v1.ImageVariant
	(*ImageVariantType)(nil),                   // 8: launcher_configuration.v1.ImageVariantType
	(*LauncherConfiguration)(nil),              // 9: launcher_configuration.v1.LauncherConfiguration
	(*LauncherConfigFamilyDetailed)(nil),       // 10: launcher_configuration.v1.LauncherConfigFamilyDetailed
	(*LauncherConfigFamilyMini)(nil),           // 11: launcher_configuration.v1.LauncherConfigFamilyMini
	(*LauncherConfigFamilyNormal)(nil),         // 12: launcher_configuration.v1.LauncherConfigFamilyNormal
	(*MissionPatch)(nil),                       // 13: launcher_configuration.v1.MissionPatch
	(*ProgramNormal)(nil),                      // 14: launcher_configuration.v1.ProgramNormal
	(*ProgramType)(nil),                        // 15: launcher_configuration.v1.ProgramType
	(*SocialMedia)(nil),                        // 16: launcher_configuration.v1.SocialMedia
	(*SocialMediaLink)(nil),                    // 17: launcher_configuration.v1.SocialMediaLink
	(*ListLauncherConfigurationsRequest)(nil),  // 18: launcher_configuration.v1.ListLauncherConfigurationsRequest
	(*ListLauncherConfigurationsResponse)(nil), // 19: launcher_configuration.v1.ListLauncherConfigurationsResponse
	(*GetLauncherConfigurationRequest)(nil),    // 20: launcher_configuration.v1.GetLauncherConfigurationRequest
	(*GetLauncherConfigurationResponse)(nil),   // 21: launcher_configuration.v1.GetLauncherConfigurationResponse
}
var file_launcher_configuration_v1_launcher_configuration_proto_depIdxs = []int32{
	4,  // 0: launcher_configuration.v1.AgencyDetailed.country:type_name -> launcher_configuration.v1.Country
	5,  // 1: launcher_configuration.v1.AgencyDetailed.image:type_name -> launcher_configuration.v1.Image
	5,  // 2: launcher_configuration.v1.AgencyDetailed.logo:type_name -> launcher_configuration.v1.Image
	5,  // 3: launcher_configuration.v1.AgencyDetailed.social_logo:type_name -> launcher_configuration.v1.Image
	17, // 4: launcher_configuration.v1.AgencyDetailed.social_media_links:type_name -> launcher_configuration.v1.SocialMediaLink
	3,  // 5: launcher_configuration.v1.AgencyDetailed.type:type_name -> launcher_configuration.v1.AgencyType
	3,  // 6: launcher_configuration.v1.AgencyMini.type:type_name -> launcher_configuration.v1.AgencyType
	4,  // 7: launcher_configuration.v1.AgencyNormal.country:type_name -> launcher_configuration.v1.Country
	5,  // 8: launcher_configuration.v1.AgencyNormal.image:type_name -> launcher_configuration.v1.Image
	5,  // 9: launcher_configuration.v1.AgencyNormal.logo:type_name -> launcher_configuration.v1.Image
	5,  // 10: launcher_configuration.v1.AgencyNormal.social_logo:type_name -> launcher_configuration.v1.Image
	3,  // 11: launcher_configuration.v1.AgencyNormal.type:type_name -> launcher_configuration.v1.AgencyType
	6,  // 12: launcher_configuration.v1.Image.license:type_name -> launcher_configuration.v1.ImageLicense
	7,  // 13: launcher_configuration.v1.Image.variants:type_name -> launcher_configuration.v1.ImageVariant
	8,  // 14: launcher_configuration.v1.ImageVariant.type:type_name -> launcher_configuration.v1.ImageVariantType
	10, // 15: launcher_configuration.v1.LauncherConfiguration.families:type_name -> launcher_configuration.v1.LauncherConfigFamilyDetailed
	5,  // 16: launcher_configuration.v1.LauncherConfiguration.image:type_name -> launcher_configuration.v1.Image
	0,  // 17: launcher_configuration.v1.LauncherConfiguration.manufacturer:type_name -> launcher_configuration.v1.AgencyDetailed
	14, // 18: launcher_configuration.v1.LauncherConfiguration.program:type_name -> launcher_configuration.v1.ProgramNormal
	0,  // 19: launcher_configuration.v1.LauncherConfigFamilyDetailed.manufacturer:type_name -> launcher_configuration.v1.AgencyDetailed
	12, // 20: launcher_configuration.v1.LauncherConfigFamilyDetailed.parent:type_name -> launcher_configuration.v1.LauncherConfigFamilyNormal
	2,  // 21: launcher_configuration.v1.LauncherConfigFamilyNormal.manufacturer:type_name -> launcher_configuration.v1.AgencyNormal
	11, // 22: launcher_configuration.v1.LauncherConfigFamilyNormal.parent:type_name -> launcher_configuration.v1.LauncherConfigFamilyMini
	1,  // 23: launcher_configuration.v1.MissionPatch.agency:type_name -> launcher_configuration.v1.AgencyMini
	1,  // 24: launcher_configuration.v1.ProgramNormal.agencies:type_name -> launcher_configuration.v1.AgencyMini
	5,  // 25: launcher_configuration.v1.ProgramNormal.image:type_name -> launcher_configuration.v1.Image
	13, // 26: launcher_configuration.v1.ProgramNormal.mission_patches:type_name -> launcher_configuration.v1.MissionPatch
	15, // 27: launcher_configuration.v1.ProgramNormal.type:type_name -> launcher_configuration.v1.ProgramType
	5,  // 28: launcher_configuration.v1.SocialMedia.logo:type_name -> launcher_configuration.v1.Image
	16, // 29: launcher_configuration.v1.SocialMediaLink.social_media:type_name -> launcher_configuration.v1.SocialMedia
	9,  // 30: launcher_configuration.v1.ListLauncherConfigurationsResponse.results:type_name -> launcher_configuration.v1.LauncherConfiguration
	9,  // 31: launcher_configuration.v1.GetLauncherConfigurationResponse.launcher_configuration:type_name -> launcher_configuration.v1.LauncherConfiguration
	18, // 32: launcher_configuration.v1.LauncherConfigurationService.ListLauncherConfigurations:input_type -> launcher_configuration.v1.ListLauncherConfigurationsRequest
	20, // 33: launcher_configuration.v1.LauncherConfigurationService.GetLauncherConfiguration:input_type -> launcher_configuration.v1.GetLauncherConfigurationRequest
	19, // 34: launcher_configuration.v1.LauncherConfigurationService.ListLauncherConfigurations:output_type -> launcher_configuration.v1.ListLauncherConfigurationsResponse
	21, // 35: launcher_configuration.v1.LauncherConfigurationService.GetLauncherConfiguration:output_type -> launcher_configuration.v1.GetLauncherConfigurationResponse
	34, // [34:36] is the sub-list for method output_type
	32, // [32:34] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_launcher_configuration_v1_launcher_configuration_proto_init() }
func file_launcher_configuration_v1_launcher_configuration_proto_init() {
	if File_launcher_configuration_v1_launcher_configuration_proto != nil {
		return
	}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[0].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[2].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[5].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[6].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[9].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[10].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[14].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[16].OneofWrappers = []any{}
	file_launcher_configuration_v1_launcher_configuration_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_launcher_configuration_v1_launcher_configuration_proto_rawDesc), len(file_launcher_configuration_v1_launcher_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_launcher_configuration_v1_launcher_configuration_proto_goTypes,
		DependencyIndexes: file_launcher_configuration_v1_launcher_configuration_proto_depIdxs,
		MessageInfos:      file_launcher_configuration_v1_launcher_configuration_proto_msgTypes,
	}.Build()
	File_launcher_configuration_v1_launcher_configuration_proto = out.File
	file_launcher_configuration_v1_launcher_configuration_proto_goTypes = nil
	file_launcher_configuration_v1_launcher_configuration_proto_depIdxs = nil
}
