// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: spacewalk/v1/spacewalk.proto

package spacewalkv1connect

import (
	v1 "com.gitlab/pobochiigo/bhole/proto/spacewalk/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SpacewalkServiceName is the fully-qualified name of the SpacewalkService service.
	SpacewalkServiceName = "spacewalk.v1.SpacewalkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SpacewalkServiceListSpacewalksProcedure is the fully-qualified name of the SpacewalkService's
	// ListSpacewalks RPC.
	SpacewalkServiceListSpacewalksProcedure = "/spacewalk.v1.SpacewalkService/ListSpacewalks"
	// SpacewalkServiceGetSpacewalkProcedure is the fully-qualified name of the SpacewalkService's
	// GetSpacewalk RPC.
	SpacewalkServiceGetSpacewalkProcedure = "/spacewalk.v1.SpacewalkService/GetSpacewalk"
)

// SpacewalkServiceClient is a client for the spacewalk.v1.SpacewalkService service.
type SpacewalkServiceClient interface {
	ListSpacewalks(context.Context, *connect.Request[v1.ListSpacewalksRequest]) (*connect.Response[v1.ListSpacewalksResponse], error)
	GetSpacewalk(context.Context, *connect.Request[v1.GetSpacewalkRequest]) (*connect.Response[v1.GetSpacewalkResponse], error)
}

// NewSpacewalkServiceClient constructs a client for the spacewalk.v1.SpacewalkService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSpacewalkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SpacewalkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	spacewalkServiceMethods := v1.File_spacewalk_v1_spacewalk_proto.Services().ByName("SpacewalkService").Methods()
	return &spacewalkServiceClient{
		listSpacewalks: connect.NewClient[v1.ListSpacewalksRequest, v1.ListSpacewalksResponse](
			httpClient,
			baseURL+SpacewalkServiceListSpacewalksProcedure,
			connect.WithSchema(spacewalkServiceMethods.ByName("ListSpacewalks")),
			connect.WithClientOptions(opts...),
		),
		getSpacewalk: connect.NewClient[v1.GetSpacewalkRequest, v1.GetSpacewalkResponse](
			httpClient,
			baseURL+SpacewalkServiceGetSpacewalkProcedure,
			connect.WithSchema(spacewalkServiceMethods.ByName("GetSpacewalk")),
			connect.WithClientOptions(opts...),
		),
	}
}

// spacewalkServiceClient implements SpacewalkServiceClient.
type spacewalkServiceClient struct {
	listSpacewalks *connect.Client[v1.ListSpacewalksRequest, v1.ListSpacewalksResponse]
	getSpacewalk   *connect.Client[v1.GetSpacewalkRequest, v1.GetSpacewalkResponse]
}

// ListSpacewalks calls spacewalk.v1.SpacewalkService.ListSpacewalks.
func (c *spacewalkServiceClient) ListSpacewalks(ctx context.Context, req *connect.Request[v1.ListSpacewalksRequest]) (*connect.Response[v1.ListSpacewalksResponse], error) {
	return c.listSpacewalks.CallUnary(ctx, req)
}

// GetSpacewalk calls spacewalk.v1.SpacewalkService.GetSpacewalk.
func (c *spacewalkServiceClient) GetSpacewalk(ctx context.Context, req *connect.Request[v1.GetSpacewalkRequest]) (*connect.Response[v1.GetSpacewalkResponse], error) {
	return c.getSpacewalk.CallUnary(ctx, req)
}

// SpacewalkServiceHandler is an implementation of the spacewalk.v1.SpacewalkService service.
type SpacewalkServiceHandler interface {
	ListSpacewalks(context.Context, *connect.Request[v1.ListSpacewalksRequest]) (*connect.Response[v1.ListSpacewalksResponse], error)
	GetSpacewalk(context.Context, *connect.Request[v1.GetSpacewalkRequest]) (*connect.Response[v1.GetSpacewalkResponse], error)
}

// NewSpacewalkServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSpacewalkServiceHandler(svc SpacewalkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	spacewalkServiceMethods := v1.File_spacewalk_v1_spacewalk_proto.Services().ByName("SpacewalkService").Methods()
	spacewalkServiceListSpacewalksHandler := connect.NewUnaryHandler(
		SpacewalkServiceListSpacewalksProcedure,
		svc.ListSpacewalks,
		connect.WithSchema(spacewalkServiceMethods.ByName("ListSpacewalks")),
		connect.WithHandlerOptions(opts...),
	)
	spacewalkServiceGetSpacewalkHandler := connect.NewUnaryHandler(
		SpacewalkServiceGetSpacewalkProcedure,
		svc.GetSpacewalk,
		connect.WithSchema(spacewalkServiceMethods.ByName("GetSpacewalk")),
		connect.WithHandlerOptions(opts...),
	)
	return "/spacewalk.v1.SpacewalkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SpacewalkServiceListSpacewalksProcedure:
			spacewalkServiceListSpacewalksHandler.ServeHTTP(w, r)
		case SpacewalkServiceGetSpacewalkProcedure:
			spacewalkServiceGetSpacewalkHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSpacewalkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSpacewalkServiceHandler struct{}

func (UnimplementedSpacewalkServiceHandler) ListSpacewalks(context.Context, *connect.Request[v1.ListSpacewalksRequest]) (*connect.Response[v1.ListSpacewalksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("spacewalk.v1.SpacewalkService.ListSpacewalks is not implemented"))
}

func (UnimplementedSpacewalkServiceHandler) GetSpacewalk(context.Context, *connect.Request[v1.GetSpacewalkRequest]) (*connect.Response[v1.GetSpacewalkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("spacewalk.v1.SpacewalkService.GetSpacewalk is not implemented"))
}
