// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: celestial_body/v1/celestial_body.proto

package celestial_bodyv1connect

import (
	v1 "com.gitlab/pobochiigo/bhole/proto/celestial_body/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CelestialBodyServiceName is the fully-qualified name of the CelestialBodyService service.
	CelestialBodyServiceName = "celestial_body.v1.CelestialBodyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CelestialBodyServiceListCelestialBodiesProcedure is the fully-qualified name of the
	// CelestialBodyService's ListCelestialBodies RPC.
	CelestialBodyServiceListCelestialBodiesProcedure = "/celestial_body.v1.CelestialBodyService/ListCelestialBodies"
	// CelestialBodyServiceGetCelestialBodyProcedure is the fully-qualified name of the
	// CelestialBodyService's GetCelestialBody RPC.
	CelestialBodyServiceGetCelestialBodyProcedure = "/celestial_body.v1.CelestialBodyService/GetCelestialBody"
)

// CelestialBodyServiceClient is a client for the celestial_body.v1.CelestialBodyService service.
type CelestialBodyServiceClient interface {
	ListCelestialBodies(context.Context, *connect.Request[v1.ListCelestialBodiesRequest]) (*connect.Response[v1.ListCelestialBodiesResponse], error)
	GetCelestialBody(context.Context, *connect.Request[v1.GetCelestialBodyRequest]) (*connect.Response[v1.GetCelestialBodyResponse], error)
}

// NewCelestialBodyServiceClient constructs a client for the celestial_body.v1.CelestialBodyService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCelestialBodyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CelestialBodyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	celestialBodyServiceMethods := v1.File_celestial_body_v1_celestial_body_proto.Services().ByName("CelestialBodyService").Methods()
	return &celestialBodyServiceClient{
		listCelestialBodies: connect.NewClient[v1.ListCelestialBodiesRequest, v1.ListCelestialBodiesResponse](
			httpClient,
			baseURL+CelestialBodyServiceListCelestialBodiesProcedure,
			connect.WithSchema(celestialBodyServiceMethods.ByName("ListCelestialBodies")),
			connect.WithClientOptions(opts...),
		),
		getCelestialBody: connect.NewClient[v1.GetCelestialBodyRequest, v1.GetCelestialBodyResponse](
			httpClient,
			baseURL+CelestialBodyServiceGetCelestialBodyProcedure,
			connect.WithSchema(celestialBodyServiceMethods.ByName("GetCelestialBody")),
			connect.WithClientOptions(opts...),
		),
	}
}

// celestialBodyServiceClient implements CelestialBodyServiceClient.
type celestialBodyServiceClient struct {
	listCelestialBodies *connect.Client[v1.ListCelestialBodiesRequest, v1.ListCelestialBodiesResponse]
	getCelestialBody    *connect.Client[v1.GetCelestialBodyRequest, v1.GetCelestialBodyResponse]
}

// ListCelestialBodies calls celestial_body.v1.CelestialBodyService.ListCelestialBodies.
func (c *celestialBodyServiceClient) ListCelestialBodies(ctx context.Context, req *connect.Request[v1.ListCelestialBodiesRequest]) (*connect.Response[v1.ListCelestialBodiesResponse], error) {
	return c.listCelestialBodies.CallUnary(ctx, req)
}

// GetCelestialBody calls celestial_body.v1.CelestialBodyService.GetCelestialBody.
func (c *celestialBodyServiceClient) GetCelestialBody(ctx context.Context, req *connect.Request[v1.GetCelestialBodyRequest]) (*connect.Response[v1.GetCelestialBodyResponse], error) {
	return c.getCelestialBody.CallUnary(ctx, req)
}

// CelestialBodyServiceHandler is an implementation of the celestial_body.v1.CelestialBodyService
// service.
type CelestialBodyServiceHandler interface {
	ListCelestialBodies(context.Context, *connect.Request[v1.ListCelestialBodiesRequest]) (*connect.Response[v1.ListCelestialBodiesResponse], error)
	GetCelestialBody(context.Context, *connect.Request[v1.GetCelestialBodyRequest]) (*connect.Response[v1.GetCelestialBodyResponse], error)
}

// NewCelestialBodyServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCelestialBodyServiceHandler(svc CelestialBodyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	celestialBodyServiceMethods := v1.File_celestial_body_v1_celestial_body_proto.Services().ByName("CelestialBodyService").Methods()
	celestialBodyServiceListCelestialBodiesHandler := connect.NewUnaryHandler(
		CelestialBodyServiceListCelestialBodiesProcedure,
		svc.ListCelestialBodies,
		connect.WithSchema(celestialBodyServiceMethods.ByName("ListCelestialBodies")),
		connect.WithHandlerOptions(opts...),
	)
	celestialBodyServiceGetCelestialBodyHandler := connect.NewUnaryHandler(
		CelestialBodyServiceGetCelestialBodyProcedure,
		svc.GetCelestialBody,
		connect.WithSchema(celestialBodyServiceMethods.ByName("GetCelestialBody")),
		connect.WithHandlerOptions(opts...),
	)
	return "/celestial_body.v1.CelestialBodyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CelestialBodyServiceListCelestialBodiesProcedure:
			celestialBodyServiceListCelestialBodiesHandler.ServeHTTP(w, r)
		case CelestialBodyServiceGetCelestialBodyProcedure:
			celestialBodyServiceGetCelestialBodyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCelestialBodyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCelestialBodyServiceHandler struct{}

func (UnimplementedCelestialBodyServiceHandler) ListCelestialBodies(context.Context, *connect.Request[v1.ListCelestialBodiesRequest]) (*connect.Response[v1.ListCelestialBodiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("celestial_body.v1.CelestialBodyService.ListCelestialBodies is not implemented"))
}

func (UnimplementedCelestialBodyServiceHandler) GetCelestialBody(context.Context, *connect.Request[v1.GetCelestialBodyRequest]) (*connect.Response[v1.GetCelestialBodyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("celestial_body.v1.CelestialBodyService.GetCelestialBody is not implemented"))
}
