// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: update/v1/update.proto

package updatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *string                `protobuf:"bytes,1,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	CreatedOn     string                 `protobuf:"bytes,3,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	Id            int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	InfoUrl       *string                `protobuf:"bytes,5,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	ProfileImage  *string                `protobuf:"bytes,6,opt,name=profile_image,json=profileImage,proto3,oneof" json:"profile_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_update_v1_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_update_v1_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_update_v1_update_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *Update) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *Update) GetCreatedOn() string {
	if x != nil {
		return x.CreatedOn
	}
	return ""
}

func (x *Update) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Update) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *Update) GetProfileImage() string {
	if x != nil && x.ProfileImage != nil {
		return *x.ProfileImage
	}
	return ""
}

type ListUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpdatesRequest) Reset() {
	*x = ListUpdatesRequest{}
	mi := &file_update_v1_update_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpdatesRequest) ProtoMessage() {}

func (x *ListUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_v1_update_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpdatesRequest.ProtoReflect.Descriptor instead.
func (*ListUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_update_v1_update_proto_rawDescGZIP(), []int{1}
}

func (x *ListUpdatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUpdatesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUpdatesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListUpdatesRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListUpdatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*Update              `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpdatesResponse) Reset() {
	*x = ListUpdatesResponse{}
	mi := &file_update_v1_update_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpdatesResponse) ProtoMessage() {}

func (x *ListUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_v1_update_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpdatesResponse.ProtoReflect.Descriptor instead.
func (*ListUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_update_v1_update_proto_rawDescGZIP(), []int{2}
}

func (x *ListUpdatesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListUpdatesResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListUpdatesResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListUpdatesResponse) GetResults() []*Update {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateRequest) Reset() {
	*x = GetUpdateRequest{}
	mi := &file_update_v1_update_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateRequest) ProtoMessage() {}

func (x *GetUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_v1_update_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateRequest.ProtoReflect.Descriptor instead.
func (*GetUpdateRequest) Descriptor() ([]byte, []int) {
	return file_update_v1_update_proto_rawDescGZIP(), []int{3}
}

func (x *GetUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUpdateRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *Update                `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpdateResponse) Reset() {
	*x = GetUpdateResponse{}
	mi := &file_update_v1_update_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpdateResponse) ProtoMessage() {}

func (x *GetUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_v1_update_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpdateResponse.ProtoReflect.Descriptor instead.
func (*GetUpdateResponse) Descriptor() ([]byte, []int) {
	return file_update_v1_update_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpdateResponse) GetUpdate() *Update {
	if x != nil {
		return x.Update
	}
	return nil
}

var File_update_v1_update_proto protoreflect.FileDescriptor

const file_update_v1_update_proto_rawDesc = "" +
	"\n" +
	"\x16update/v1/update.proto\x12\tupdate.v1\"\xfe\x01\n" +
	"\x06Update\x12\x1d\n" +
	"\acomment\x18\x01 \x01(\tH\x00R\acomment\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tH\x01R\tcreatedBy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_on\x18\x03 \x01(\tR\tcreatedOn\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\x12\x1e\n" +
	"\binfo_url\x18\x05 \x01(\tH\x02R\ainfoUrl\x88\x01\x01\x12(\n" +
	"\rprofile_image\x18\x06 \x01(\tH\x03R\fprofileImage\x88\x01\x01B\n" +
	"\n" +
	"\b_commentB\r\n" +
	"\v_created_byB\v\n" +
	"\t_info_urlB\x10\n" +
	"\x0e_profile_image\"n\n" +
	"\x12ListUpdatesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x88\x01\n" +
	"\x13ListUpdatesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12+\n" +
	"\aresults\x18\x04 \x03(\v2\x11.update.v1.UpdateR\aresults\"6\n" +
	"\x10GetUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\">\n" +
	"\x11GetUpdateResponse\x12)\n" +
	"\x06update\x18\x01 \x01(\v2\x11.update.v1.UpdateR\x06update2\xa5\x01\n" +
	"\rUpdateService\x12L\n" +
	"\vListUpdates\x12\x1d.update.v1.ListUpdatesRequest\x1a\x1e.update.v1.ListUpdatesResponse\x12F\n" +
	"\tGetUpdate\x12\x1b.update.v1.GetUpdateRequest\x1a\x1c.update.v1.GetUpdateResponseB6Z4github.com/pobochiigo/bhole/proto/update/v1;updatev1b\x06proto3"

var (
	file_update_v1_update_proto_rawDescOnce sync.Once
	file_update_v1_update_proto_rawDescData []byte
)

func file_update_v1_update_proto_rawDescGZIP() []byte {
	file_update_v1_update_proto_rawDescOnce.Do(func() {
		file_update_v1_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_v1_update_proto_rawDesc), len(file_update_v1_update_proto_rawDesc)))
	})
	return file_update_v1_update_proto_rawDescData
}

var file_update_v1_update_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_update_v1_update_proto_goTypes = []any{
	(*Update)(nil),              // 0: update.v1.Update
	(*ListUpdatesRequest)(nil),  // 1: update.v1.ListUpdatesRequest
	(*ListUpdatesResponse)(nil), // 2: update.v1.ListUpdatesResponse
	(*GetUpdateRequest)(nil),    // 3: update.v1.GetUpdateRequest
	(*GetUpdateResponse)(nil),   // 4: update.v1.GetUpdateResponse
}
var file_update_v1_update_proto_depIdxs = []int32{
	0, // 0: update.v1.ListUpdatesResponse.results:type_name -> update.v1.Update
	0, // 1: update.v1.GetUpdateResponse.update:type_name -> update.v1.Update
	1, // 2: update.v1.UpdateService.ListUpdates:input_type -> update.v1.ListUpdatesRequest
	3, // 3: update.v1.UpdateService.GetUpdate:input_type -> update.v1.GetUpdateRequest
	2, // 4: update.v1.UpdateService.ListUpdates:output_type -> update.v1.ListUpdatesResponse
	4, // 5: update.v1.UpdateService.GetUpdate:output_type -> update.v1.GetUpdateResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_update_v1_update_proto_init() }
func file_update_v1_update_proto_init() {
	if File_update_v1_update_proto != nil {
		return
	}
	file_update_v1_update_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_v1_update_proto_rawDesc), len(file_update_v1_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_update_v1_update_proto_goTypes,
		DependencyIndexes: file_update_v1_update_proto_depIdxs,
		MessageInfos:      file_update_v1_update_proto_msgTypes,
	}.Build()
	File_update_v1_update_proto = out.File
	file_update_v1_update_proto_goTypes = nil
	file_update_v1_update_proto_depIdxs = nil
}
