// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pad/v1/pad.proto

package padv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgencyNormal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Administrator *string                `protobuf:"bytes,2,opt,name=administrator,proto3,oneof" json:"administrator,omitempty"`
	Country       []*Country             `protobuf:"bytes,3,rep,name=country,proto3" json:"country,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Featured      bool                   `protobuf:"varint,5,opt,name=featured,proto3" json:"featured,omitempty"`
	FoundingYear  *int32                 `protobuf:"varint,6,opt,name=founding_year,json=foundingYear,proto3,oneof" json:"founding_year,omitempty"`
	Id            int32                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Image         *Image                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Launchers     string                 `protobuf:"bytes,9,opt,name=launchers,proto3" json:"launchers,omitempty"`
	Logo          *Image                 `protobuf:"bytes,10,opt,name=logo,proto3" json:"logo,omitempty"`
	Name          string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	Parent        *string                `protobuf:"bytes,12,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,13,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SocialLogo    *Image                 `protobuf:"bytes,14,opt,name=social_logo,json=socialLogo,proto3" json:"social_logo,omitempty"`
	Spacecraft    string                 `protobuf:"bytes,15,opt,name=spacecraft,proto3" json:"spacecraft,omitempty"`
	Type          *AgencyType            `protobuf:"bytes,16,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,17,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyNormal) Reset() {
	*x = AgencyNormal{}
	mi := &file_pad_v1_pad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyNormal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyNormal) ProtoMessage() {}

func (x *AgencyNormal) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyNormal.ProtoReflect.Descriptor instead.
func (*AgencyNormal) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{0}
}

func (x *AgencyNormal) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyNormal) GetAdministrator() string {
	if x != nil && x.Administrator != nil {
		return *x.Administrator
	}
	return ""
}

func (x *AgencyNormal) GetCountry() []*Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *AgencyNormal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AgencyNormal) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *AgencyNormal) GetFoundingYear() int32 {
	if x != nil && x.FoundingYear != nil {
		return *x.FoundingYear
	}
	return 0
}

func (x *AgencyNormal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyNormal) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *AgencyNormal) GetLaunchers() string {
	if x != nil {
		return x.Launchers
	}
	return ""
}

func (x *AgencyNormal) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *AgencyNormal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyNormal) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *AgencyNormal) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyNormal) GetSocialLogo() *Image {
	if x != nil {
		return x.SocialLogo
	}
	return nil
}

func (x *AgencyNormal) GetSpacecraft() string {
	if x != nil {
		return x.Spacecraft
	}
	return ""
}

func (x *AgencyNormal) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyNormal) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgencyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyType) Reset() {
	*x = AgencyType{}
	mi := &file_pad_v1_pad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyType) ProtoMessage() {}

func (x *AgencyType) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyType.ProtoReflect.Descriptor instead.
func (*AgencyType) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{1}
}

func (x *AgencyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CelestialBodyDetailed struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Atmosphere             bool                   `protobuf:"varint,1,opt,name=atmosphere,proto3" json:"atmosphere,omitempty"`
	Description            *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Diameter               *float32               `protobuf:"fixed32,3,opt,name=diameter,proto3,oneof" json:"diameter,omitempty"`
	FailedLandings         int32                  `protobuf:"varint,4,opt,name=failed_landings,json=failedLandings,proto3" json:"failed_landings,omitempty"`
	FailedLaunches         int32                  `protobuf:"varint,5,opt,name=failed_launches,json=failedLaunches,proto3" json:"failed_launches,omitempty"`
	Gravity                *float32               `protobuf:"fixed32,6,opt,name=gravity,proto3,oneof" json:"gravity,omitempty"`
	Id                     int32                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	Image                  *Image                 `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	LengthOfDay            *string                `protobuf:"bytes,9,opt,name=length_of_day,json=lengthOfDay,proto3,oneof" json:"length_of_day,omitempty"`
	Mass                   *float32               `protobuf:"fixed32,10,opt,name=mass,proto3,oneof" json:"mass,omitempty"`
	Name                   string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode           string                 `protobuf:"bytes,12,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SuccessfulLandings     int32                  `protobuf:"varint,13,opt,name=successful_landings,json=successfulLandings,proto3" json:"successful_landings,omitempty"`
	SuccessfulLaunches     int32                  `protobuf:"varint,14,opt,name=successful_launches,json=successfulLaunches,proto3" json:"successful_launches,omitempty"`
	TotalAttemptedLandings int32                  `protobuf:"varint,15,opt,name=total_attempted_landings,json=totalAttemptedLandings,proto3" json:"total_attempted_landings,omitempty"`
	TotalAttemptedLaunches int32                  `protobuf:"varint,16,opt,name=total_attempted_launches,json=totalAttemptedLaunches,proto3" json:"total_attempted_launches,omitempty"`
	Type                   *CelestialBodyType     `protobuf:"bytes,17,opt,name=type,proto3" json:"type,omitempty"`
	WikiUrl                *string                `protobuf:"bytes,18,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CelestialBodyDetailed) Reset() {
	*x = CelestialBodyDetailed{}
	mi := &file_pad_v1_pad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelestialBodyDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelestialBodyDetailed) ProtoMessage() {}

func (x *CelestialBodyDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelestialBodyDetailed.ProtoReflect.Descriptor instead.
func (*CelestialBodyDetailed) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{2}
}

func (x *CelestialBodyDetailed) GetAtmosphere() bool {
	if x != nil {
		return x.Atmosphere
	}
	return false
}

func (x *CelestialBodyDetailed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CelestialBodyDetailed) GetDiameter() float32 {
	if x != nil && x.Diameter != nil {
		return *x.Diameter
	}
	return 0
}

func (x *CelestialBodyDetailed) GetFailedLandings() int32 {
	if x != nil {
		return x.FailedLandings
	}
	return 0
}

func (x *CelestialBodyDetailed) GetFailedLaunches() int32 {
	if x != nil {
		return x.FailedLaunches
	}
	return 0
}

func (x *CelestialBodyDetailed) GetGravity() float32 {
	if x != nil && x.Gravity != nil {
		return *x.Gravity
	}
	return 0
}

func (x *CelestialBodyDetailed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CelestialBodyDetailed) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CelestialBodyDetailed) GetLengthOfDay() string {
	if x != nil && x.LengthOfDay != nil {
		return *x.LengthOfDay
	}
	return ""
}

func (x *CelestialBodyDetailed) GetMass() float32 {
	if x != nil && x.Mass != nil {
		return *x.Mass
	}
	return 0
}

func (x *CelestialBodyDetailed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CelestialBodyDetailed) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *CelestialBodyDetailed) GetSuccessfulLandings() int32 {
	if x != nil {
		return x.SuccessfulLandings
	}
	return 0
}

func (x *CelestialBodyDetailed) GetSuccessfulLaunches() int32 {
	if x != nil {
		return x.SuccessfulLaunches
	}
	return 0
}

func (x *CelestialBodyDetailed) GetTotalAttemptedLandings() int32 {
	if x != nil {
		return x.TotalAttemptedLandings
	}
	return 0
}

func (x *CelestialBodyDetailed) GetTotalAttemptedLaunches() int32 {
	if x != nil {
		return x.TotalAttemptedLaunches
	}
	return 0
}

func (x *CelestialBodyDetailed) GetType() *CelestialBodyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *CelestialBodyDetailed) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type CelestialBodyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CelestialBodyType) Reset() {
	*x = CelestialBodyType{}
	mi := &file_pad_v1_pad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CelestialBodyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelestialBodyType) ProtoMessage() {}

func (x *CelestialBodyType) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelestialBodyType.ProtoReflect.Descriptor instead.
func (*CelestialBodyType) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{3}
}

func (x *CelestialBodyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CelestialBodyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Country struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Alpha_2Code             string                 `protobuf:"bytes,1,opt,name=alpha_2_code,json=alpha2Code,proto3" json:"alpha_2_code,omitempty"`
	Alpha_3Code             string                 `protobuf:"bytes,2,opt,name=alpha_3_code,json=alpha3Code,proto3" json:"alpha_3_code,omitempty"`
	Id                      int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NationalityName         string                 `protobuf:"bytes,5,opt,name=nationality_name,json=nationalityName,proto3" json:"nationality_name,omitempty"`
	NationalityNameComposed string                 `protobuf:"bytes,6,opt,name=nationality_name_composed,json=nationalityNameComposed,proto3" json:"nationality_name_composed,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_pad_v1_pad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{4}
}

func (x *Country) GetAlpha_2Code() string {
	if x != nil {
		return x.Alpha_2Code
	}
	return ""
}

func (x *Country) GetAlpha_3Code() string {
	if x != nil {
		return x.Alpha_3Code
	}
	return ""
}

func (x *Country) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetNationalityName() string {
	if x != nil {
		return x.NationalityName
	}
	return ""
}

func (x *Country) GetNationalityNameComposed() string {
	if x != nil {
		return x.NationalityNameComposed
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credit        *string                `protobuf:"bytes,1,opt,name=credit,proto3,oneof" json:"credit,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	License       *ImageLicense          `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SingleUse     bool                   `protobuf:"varint,6,opt,name=single_use,json=singleUse,proto3" json:"single_use,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Variants      []*ImageVariant        `protobuf:"bytes,8,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_pad_v1_pad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{5}
}

func (x *Image) GetCredit() string {
	if x != nil && x.Credit != nil {
		return *x.Credit
	}
	return ""
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Image) GetLicense() *ImageLicense {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetSingleUse() bool {
	if x != nil {
		return x.SingleUse
	}
	return false
}

func (x *Image) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Image) GetVariants() []*ImageVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ImageLicense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          *string                `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageLicense) Reset() {
	*x = ImageLicense{}
	mi := &file_pad_v1_pad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageLicense) ProtoMessage() {}

func (x *ImageLicense) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageLicense.ProtoReflect.Descriptor instead.
func (*ImageLicense) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{6}
}

func (x *ImageLicense) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageLicense) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *ImageLicense) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageLicense) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type          *ImageVariantType      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariant) Reset() {
	*x = ImageVariant{}
	mi := &file_pad_v1_pad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariant) ProtoMessage() {}

func (x *ImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariant.ProtoReflect.Descriptor instead.
func (*ImageVariant) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{7}
}

func (x *ImageVariant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariant) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageVariant) GetType() *ImageVariantType {
	if x != nil {
		return x.Type
	}
	return nil
}

type ImageVariantType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariantType) Reset() {
	*x = ImageVariantType{}
	mi := &file_pad_v1_pad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariantType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariantType) ProtoMessage() {}

func (x *ImageVariantType) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariantType.ProtoReflect.Descriptor instead.
func (*ImageVariantType) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{8}
}

func (x *ImageVariantType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariantType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Location struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Active            bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	CelestialBody     *CelestialBodyDetailed `protobuf:"bytes,2,opt,name=celestial_body,json=celestialBody,proto3" json:"celestial_body,omitempty"`
	Country           *Country               `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Description       *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Id                int32                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Image             *Image                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Latitude          *float32               `protobuf:"fixed32,7,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude         *float32               `protobuf:"fixed32,8,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	MapImage          *string                `protobuf:"bytes,9,opt,name=map_image,json=mapImage,proto3,oneof" json:"map_image,omitempty"`
	Name              string                 `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode      string                 `protobuf:"bytes,11,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	TimezoneName      string                 `protobuf:"bytes,12,opt,name=timezone_name,json=timezoneName,proto3" json:"timezone_name,omitempty"`
	TotalLandingCount *int32                 `protobuf:"varint,13,opt,name=total_landing_count,json=totalLandingCount,proto3,oneof" json:"total_landing_count,omitempty"`
	TotalLaunchCount  *int32                 `protobuf:"varint,14,opt,name=total_launch_count,json=totalLaunchCount,proto3,oneof" json:"total_launch_count,omitempty"`
	Url               string                 `protobuf:"bytes,15,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_pad_v1_pad_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{9}
}

func (x *Location) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Location) GetCelestialBody() *CelestialBodyDetailed {
	if x != nil {
		return x.CelestialBody
	}
	return nil
}

func (x *Location) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *Location) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Location) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Location) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Location) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Location) GetMapImage() string {
	if x != nil && x.MapImage != nil {
		return *x.MapImage
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *Location) GetTimezoneName() string {
	if x != nil {
		return x.TimezoneName
	}
	return ""
}

func (x *Location) GetTotalLandingCount() int32 {
	if x != nil && x.TotalLandingCount != nil {
		return *x.TotalLandingCount
	}
	return 0
}

func (x *Location) GetTotalLaunchCount() int32 {
	if x != nil && x.TotalLaunchCount != nil {
		return *x.TotalLaunchCount
	}
	return 0
}

func (x *Location) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Pad struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Active                    bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Agencies                  []*AgencyNormal        `protobuf:"bytes,2,rep,name=agencies,proto3" json:"agencies,omitempty"`
	Country                   *Country               `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Description               *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FastestTurnaround         *string                `protobuf:"bytes,5,opt,name=fastest_turnaround,json=fastestTurnaround,proto3,oneof" json:"fastest_turnaround,omitempty"`
	Id                        int32                  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	Image                     *Image                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl                   *string                `protobuf:"bytes,8,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	Latitude                  *float32               `protobuf:"fixed32,9,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Location                  *Location              `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	Longitude                 *float32               `protobuf:"fixed32,11,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	MapImage                  *string                `protobuf:"bytes,12,opt,name=map_image,json=mapImage,proto3,oneof" json:"map_image,omitempty"`
	MapUrl                    *string                `protobuf:"bytes,13,opt,name=map_url,json=mapUrl,proto3,oneof" json:"map_url,omitempty"`
	Name                      string                 `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	OrbitalLaunchAttemptCount *int32                 `protobuf:"varint,15,opt,name=orbital_launch_attempt_count,json=orbitalLaunchAttemptCount,proto3,oneof" json:"orbital_launch_attempt_count,omitempty"`
	TotalLaunchCount          *int32                 `protobuf:"varint,16,opt,name=total_launch_count,json=totalLaunchCount,proto3,oneof" json:"total_launch_count,omitempty"`
	Url                       string                 `protobuf:"bytes,17,opt,name=url,proto3" json:"url,omitempty"`
	WikiUrl                   *string                `protobuf:"bytes,18,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Pad) Reset() {
	*x = Pad{}
	mi := &file_pad_v1_pad_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pad) ProtoMessage() {}

func (x *Pad) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pad.ProtoReflect.Descriptor instead.
func (*Pad) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{10}
}

func (x *Pad) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Pad) GetAgencies() []*AgencyNormal {
	if x != nil {
		return x.Agencies
	}
	return nil
}

func (x *Pad) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *Pad) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Pad) GetFastestTurnaround() string {
	if x != nil && x.FastestTurnaround != nil {
		return *x.FastestTurnaround
	}
	return ""
}

func (x *Pad) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pad) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Pad) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *Pad) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Pad) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Pad) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Pad) GetMapImage() string {
	if x != nil && x.MapImage != nil {
		return *x.MapImage
	}
	return ""
}

func (x *Pad) GetMapUrl() string {
	if x != nil && x.MapUrl != nil {
		return *x.MapUrl
	}
	return ""
}

func (x *Pad) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pad) GetOrbitalLaunchAttemptCount() int32 {
	if x != nil && x.OrbitalLaunchAttemptCount != nil {
		return *x.OrbitalLaunchAttemptCount
	}
	return 0
}

func (x *Pad) GetTotalLaunchCount() int32 {
	if x != nil && x.TotalLaunchCount != nil {
		return *x.TotalLaunchCount
	}
	return 0
}

func (x *Pad) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Pad) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type ListPadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPadsRequest) Reset() {
	*x = ListPadsRequest{}
	mi := &file_pad_v1_pad_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPadsRequest) ProtoMessage() {}

func (x *ListPadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPadsRequest.ProtoReflect.Descriptor instead.
func (*ListPadsRequest) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{11}
}

func (x *ListPadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPadsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPadsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListPadsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListPadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*Pad                 `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPadsResponse) Reset() {
	*x = ListPadsResponse{}
	mi := &file_pad_v1_pad_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPadsResponse) ProtoMessage() {}

func (x *ListPadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPadsResponse.ProtoReflect.Descriptor instead.
func (*ListPadsResponse) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{12}
}

func (x *ListPadsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListPadsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListPadsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListPadsResponse) GetResults() []*Pad {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetPadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPadRequest) Reset() {
	*x = GetPadRequest{}
	mi := &file_pad_v1_pad_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPadRequest) ProtoMessage() {}

func (x *GetPadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPadRequest.ProtoReflect.Descriptor instead.
func (*GetPadRequest) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{13}
}

func (x *GetPadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPadRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetPadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pad           *Pad                   `protobuf:"bytes,1,opt,name=pad,proto3" json:"pad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPadResponse) Reset() {
	*x = GetPadResponse{}
	mi := &file_pad_v1_pad_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPadResponse) ProtoMessage() {}

func (x *GetPadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pad_v1_pad_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPadResponse.ProtoReflect.Descriptor instead.
func (*GetPadResponse) Descriptor() ([]byte, []int) {
	return file_pad_v1_pad_proto_rawDescGZIP(), []int{14}
}

func (x *GetPadResponse) GetPad() *Pad {
	if x != nil {
		return x.Pad
	}
	return nil
}

var File_pad_v1_pad_proto protoreflect.FileDescriptor

const file_pad_v1_pad_proto_rawDesc = "" +
	"\n" +
	"\x10pad/v1/pad.proto\x12\x06pad.v1\"\xfe\x04\n" +
	"\fAgencyNormal\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12)\n" +
	"\radministrator\x18\x02 \x01(\tH\x00R\radministrator\x88\x01\x01\x12)\n" +
	"\acountry\x18\x03 \x03(\v2\x0f.pad.v1.CountryR\acountry\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1a\n" +
	"\bfeatured\x18\x05 \x01(\bR\bfeatured\x12(\n" +
	"\rfounding_year\x18\x06 \x01(\x05H\x02R\ffoundingYear\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\a \x01(\x05R\x02id\x12#\n" +
	"\x05image\x18\b \x01(\v2\r.pad.v1.ImageR\x05image\x12\x1c\n" +
	"\tlaunchers\x18\t \x01(\tR\tlaunchers\x12!\n" +
	"\x04logo\x18\n" +
	" \x01(\v2\r.pad.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12\x1b\n" +
	"\x06parent\x18\f \x01(\tH\x03R\x06parent\x88\x01\x01\x12#\n" +
	"\rresponse_mode\x18\r \x01(\tR\fresponseMode\x12.\n" +
	"\vsocial_logo\x18\x0e \x01(\v2\r.pad.v1.ImageR\n" +
	"socialLogo\x12\x1e\n" +
	"\n" +
	"spacecraft\x18\x0f \x01(\tR\n" +
	"spacecraft\x12&\n" +
	"\x04type\x18\x10 \x01(\v2\x12.pad.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x11 \x01(\tR\x03urlB\x10\n" +
	"\x0e_administratorB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_founding_yearB\t\n" +
	"\a_parent\"0\n" +
	"\n" +
	"AgencyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x96\x06\n" +
	"\x15CelestialBodyDetailed\x12\x1e\n" +
	"\n" +
	"atmosphere\x18\x01 \x01(\bR\n" +
	"atmosphere\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bdiameter\x18\x03 \x01(\x02H\x01R\bdiameter\x88\x01\x01\x12'\n" +
	"\x0ffailed_landings\x18\x04 \x01(\x05R\x0efailedLandings\x12'\n" +
	"\x0ffailed_launches\x18\x05 \x01(\x05R\x0efailedLaunches\x12\x1d\n" +
	"\agravity\x18\x06 \x01(\x02H\x02R\agravity\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\a \x01(\x05R\x02id\x12#\n" +
	"\x05image\x18\b \x01(\v2\r.pad.v1.ImageR\x05image\x12'\n" +
	"\rlength_of_day\x18\t \x01(\tH\x03R\vlengthOfDay\x88\x01\x01\x12\x17\n" +
	"\x04mass\x18\n" +
	" \x01(\x02H\x04R\x04mass\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\f \x01(\tR\fresponseMode\x12/\n" +
	"\x13successful_landings\x18\r \x01(\x05R\x12successfulLandings\x12/\n" +
	"\x13successful_launches\x18\x0e \x01(\x05R\x12successfulLaunches\x128\n" +
	"\x18total_attempted_landings\x18\x0f \x01(\x05R\x16totalAttemptedLandings\x128\n" +
	"\x18total_attempted_launches\x18\x10 \x01(\x05R\x16totalAttemptedLaunches\x12-\n" +
	"\x04type\x18\x11 \x01(\v2\x19.pad.v1.CelestialBodyTypeR\x04type\x12\x1e\n" +
	"\bwiki_url\x18\x12 \x01(\tH\x05R\awikiUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_diameterB\n" +
	"\n" +
	"\b_gravityB\x10\n" +
	"\x0e_length_of_dayB\a\n" +
	"\x05_massB\v\n" +
	"\t_wiki_url\"7\n" +
	"\x11CelestialBodyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd8\x01\n" +
	"\aCountry\x12 \n" +
	"\falpha_2_code\x18\x01 \x01(\tR\n" +
	"alpha2Code\x12 \n" +
	"\falpha_3_code\x18\x02 \x01(\tR\n" +
	"alpha3Code\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x10nationality_name\x18\x05 \x01(\tR\x0fnationalityName\x12:\n" +
	"\x19nationality_name_composed\x18\x06 \x01(\tR\x17nationalityNameComposed\"\x96\x02\n" +
	"\x05Image\x12\x1b\n" +
	"\x06credit\x18\x01 \x01(\tH\x00R\x06credit\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12.\n" +
	"\alicense\x18\x04 \x01(\v2\x14.pad.v1.ImageLicenseR\alicense\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"single_use\x18\x06 \x01(\bR\tsingleUse\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x120\n" +
	"\bvariants\x18\b \x03(\v2\x14.pad.v1.ImageVariantR\bvariantsB\t\n" +
	"\a_credit\"p\n" +
	"\fImageLicense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04link\x18\x02 \x01(\tH\x00R\x04link\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB\a\n" +
	"\x05_link\"i\n" +
	"\fImageVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12,\n" +
	"\x04type\x18\x03 \x01(\v2\x18.pad.v1.ImageVariantTypeR\x04type\"6\n" +
	"\x10ImageVariantType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x95\x05\n" +
	"\bLocation\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12D\n" +
	"\x0ecelestial_body\x18\x02 \x01(\v2\x1d.pad.v1.CelestialBodyDetailedR\rcelestialBody\x12)\n" +
	"\acountry\x18\x03 \x01(\v2\x0f.pad.v1.CountryR\acountry\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x05R\x02id\x12#\n" +
	"\x05image\x18\x06 \x01(\v2\r.pad.v1.ImageR\x05image\x12\x1f\n" +
	"\blatitude\x18\a \x01(\x02H\x01R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\b \x01(\x02H\x02R\tlongitude\x88\x01\x01\x12 \n" +
	"\tmap_image\x18\t \x01(\tH\x03R\bmapImage\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\v \x01(\tR\fresponseMode\x12#\n" +
	"\rtimezone_name\x18\f \x01(\tR\ftimezoneName\x123\n" +
	"\x13total_landing_count\x18\r \x01(\x05H\x04R\x11totalLandingCount\x88\x01\x01\x121\n" +
	"\x12total_launch_count\x18\x0e \x01(\x05H\x05R\x10totalLaunchCount\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\x0f \x01(\tR\x03urlB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\f\n" +
	"\n" +
	"_map_imageB\x16\n" +
	"\x14_total_landing_countB\x15\n" +
	"\x13_total_launch_count\"\xc9\x06\n" +
	"\x03Pad\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x120\n" +
	"\bagencies\x18\x02 \x03(\v2\x14.pad.v1.AgencyNormalR\bagencies\x12)\n" +
	"\acountry\x18\x03 \x01(\v2\x0f.pad.v1.CountryR\acountry\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x122\n" +
	"\x12fastest_turnaround\x18\x05 \x01(\tH\x01R\x11fastestTurnaround\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x05R\x02id\x12#\n" +
	"\x05image\x18\a \x01(\v2\r.pad.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\b \x01(\tH\x02R\ainfoUrl\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\t \x01(\x02H\x03R\blatitude\x88\x01\x01\x12,\n" +
	"\blocation\x18\n" +
	" \x01(\v2\x10.pad.v1.LocationR\blocation\x12!\n" +
	"\tlongitude\x18\v \x01(\x02H\x04R\tlongitude\x88\x01\x01\x12 \n" +
	"\tmap_image\x18\f \x01(\tH\x05R\bmapImage\x88\x01\x01\x12\x1c\n" +
	"\amap_url\x18\r \x01(\tH\x06R\x06mapUrl\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12D\n" +
	"\x1corbital_launch_attempt_count\x18\x0f \x01(\x05H\aR\x19orbitalLaunchAttemptCount\x88\x01\x01\x121\n" +
	"\x12total_launch_count\x18\x10 \x01(\x05H\bR\x10totalLaunchCount\x88\x01\x01\x12\x10\n" +
	"\x03url\x18\x11 \x01(\tR\x03url\x12\x1e\n" +
	"\bwiki_url\x18\x12 \x01(\tH\tR\awikiUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x15\n" +
	"\x13_fastest_turnaroundB\v\n" +
	"\t_info_urlB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\f\n" +
	"\n" +
	"_map_imageB\n" +
	"\n" +
	"\b_map_urlB\x1f\n" +
	"\x1d_orbital_launch_attempt_countB\x15\n" +
	"\x13_total_launch_countB\v\n" +
	"\t_wiki_url\"k\n" +
	"\x0fListPadsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x7f\n" +
	"\x10ListPadsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12%\n" +
	"\aresults\x18\x04 \x03(\v2\v.pad.v1.PadR\aresults\"3\n" +
	"\rGetPadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"/\n" +
	"\x0eGetPadResponse\x12\x1d\n" +
	"\x03pad\x18\x01 \x01(\v2\v.pad.v1.PadR\x03pad2\x84\x01\n" +
	"\n" +
	"PadService\x12=\n" +
	"\bListPads\x12\x17.pad.v1.ListPadsRequest\x1a\x18.pad.v1.ListPadsResponse\x127\n" +
	"\x06GetPad\x12\x15.pad.v1.GetPadRequest\x1a\x16.pad.v1.GetPadResponseB0Z.github.com/pobochiigo/bhole/proto/pad/v1;padv1b\x06proto3"

var (
	file_pad_v1_pad_proto_rawDescOnce sync.Once
	file_pad_v1_pad_proto_rawDescData []byte
)

func file_pad_v1_pad_proto_rawDescGZIP() []byte {
	file_pad_v1_pad_proto_rawDescOnce.Do(func() {
		file_pad_v1_pad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pad_v1_pad_proto_rawDesc), len(file_pad_v1_pad_proto_rawDesc)))
	})
	return file_pad_v1_pad_proto_rawDescData
}

var file_pad_v1_pad_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pad_v1_pad_proto_goTypes = []any{
	(*AgencyNormal)(nil),          // 0: pad.v1.AgencyNormal
	(*AgencyType)(nil),            // 1: pad.v1.AgencyType
	(*CelestialBodyDetailed)(nil), // 2: pad.v1.CelestialBodyDetailed
	(*CelestialBodyType)(nil),     // 3: pad.v1.CelestialBodyType
	(*Country)(nil),               // 4: pad.v1.Country
	(*Image)(nil),                 // 5: pad.v1.Image
	(*ImageLicense)(nil),          // 6: pad.v1.ImageLicense
	(*ImageVariant)(nil),          // 7: pad.v1.ImageVariant
	(*ImageVariantType)(nil),      // 8: pad.v1.ImageVariantType
	(*Location)(nil),              // 9: pad.v1.Location
	(*Pad)(nil),                   // 10: pad.v1.Pad
	(*ListPadsRequest)(nil),       // 11: pad.v1.ListPadsRequest
	(*ListPadsResponse)(nil),      // 12: pad.v1.ListPadsResponse
	(*GetPadRequest)(nil),         // 13: pad.v1.GetPadRequest
	(*GetPadResponse)(nil),        // 14: pad.v1.GetPadResponse
}
var file_pad_v1_pad_proto_depIdxs = []int32{
	4,  // 0: pad.v1.AgencyNormal.country:type_name -> pad.v1.Country
	5,  // 1: pad.v1.AgencyNormal.image:type_name -> pad.v1.Image
	5,  // 2: pad.v1.AgencyNormal.logo:type_name -> pad.v1.Image
	5,  // 3: pad.v1.AgencyNormal.social_logo:type_name -> pad.v1.Image
	1,  // 4: pad.v1.AgencyNormal.type:type_name -> pad.v1.AgencyType
	5,  // 5: pad.v1.CelestialBodyDetailed.image:type_name -> pad.v1.Image
	3,  // 6: pad.v1.CelestialBodyDetailed.type:type_name -> pad.v1.CelestialBodyType
	6,  // 7: pad.v1.Image.license:type_name -> pad.v1.ImageLicense
	7,  // 8: pad.v1.Image.variants:type_name -> pad.v1.ImageVariant
	8,  // 9: pad.v1.ImageVariant.type:type_name -> pad.v1.ImageVariantType
	2,  // 10: pad.v1.Location.celestial_body:type_name -> pad.v1.CelestialBodyDetailed
	4,  // 11: pad.v1.Location.country:type_name -> pad.v1.Country
	5,  // 12: pad.v1.Location.image:type_name -> pad.v1.Image
	0,  // 13: pad.v1.Pad.agencies:type_name -> pad.v1.AgencyNormal
	4,  // 14: pad.v1.Pad.country:type_name -> pad.v1.Country
	5,  // 15: pad.v1.Pad.image:type_name -> pad.v1.Image
	9,  // 16: pad.v1.Pad.location:type_name -> pad.v1.Location
	10, // 17: pad.v1.ListPadsResponse.results:type_name -> pad.v1.Pad
	10, // 18: pad.v1.GetPadResponse.pad:type_name -> pad.v1.Pad
	11, // 19: pad.v1.PadService.ListPads:input_type -> pad.v1.ListPadsRequest
	13, // 20: pad.v1.PadService.GetPad:input_type -> pad.v1.GetPadRequest
	12, // 21: pad.v1.PadService.ListPads:output_type -> pad.v1.ListPadsResponse
	14, // 22: pad.v1.PadService.GetPad:output_type -> pad.v1.GetPadResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pad_v1_pad_proto_init() }
func file_pad_v1_pad_proto_init() {
	if File_pad_v1_pad_proto != nil {
		return
	}
	file_pad_v1_pad_proto_msgTypes[0].OneofWrappers = []any{}
	file_pad_v1_pad_proto_msgTypes[2].OneofWrappers = []any{}
	file_pad_v1_pad_proto_msgTypes[5].OneofWrappers = []any{}
	file_pad_v1_pad_proto_msgTypes[6].OneofWrappers = []any{}
	file_pad_v1_pad_proto_msgTypes[9].OneofWrappers = []any{}
	file_pad_v1_pad_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pad_v1_pad_proto_rawDesc), len(file_pad_v1_pad_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pad_v1_pad_proto_goTypes,
		DependencyIndexes: file_pad_v1_pad_proto_depIdxs,
		MessageInfos:      file_pad_v1_pad_proto_msgTypes,
	}.Build()
	File_pad_v1_pad_proto = out.File
	file_pad_v1_pad_proto_goTypes = nil
	file_pad_v1_pad_proto_depIdxs = nil
}
