// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: location/v1/location.proto

package locationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pobochiigo/bhole/proto/location/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LocationServiceName is the fully-qualified name of the LocationService service.
	LocationServiceName = "location.v1.LocationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LocationServiceListLocationsProcedure is the fully-qualified name of the LocationService's
	// ListLocations RPC.
	LocationServiceListLocationsProcedure = "/location.v1.LocationService/ListLocations"
	// LocationServiceGetLocationProcedure is the fully-qualified name of the LocationService's
	// GetLocation RPC.
	LocationServiceGetLocationProcedure = "/location.v1.LocationService/GetLocation"
)

// LocationServiceClient is a client for the location.v1.LocationService service.
type LocationServiceClient interface {
	ListLocations(context.Context, *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error)
	GetLocation(context.Context, *connect.Request[v1.GetLocationRequest]) (*connect.Response[v1.GetLocationResponse], error)
}

// NewLocationServiceClient constructs a client for the location.v1.LocationService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLocationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LocationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	locationServiceMethods := v1.File_location_v1_location_proto.Services().ByName("LocationService").Methods()
	return &locationServiceClient{
		listLocations: connect.NewClient[v1.ListLocationsRequest, v1.ListLocationsResponse](
			httpClient,
			baseURL+LocationServiceListLocationsProcedure,
			connect.WithSchema(locationServiceMethods.ByName("ListLocations")),
			connect.WithClientOptions(opts...),
		),
		getLocation: connect.NewClient[v1.GetLocationRequest, v1.GetLocationResponse](
			httpClient,
			baseURL+LocationServiceGetLocationProcedure,
			connect.WithSchema(locationServiceMethods.ByName("GetLocation")),
			connect.WithClientOptions(opts...),
		),
	}
}

// locationServiceClient implements LocationServiceClient.
type locationServiceClient struct {
	listLocations *connect.Client[v1.ListLocationsRequest, v1.ListLocationsResponse]
	getLocation   *connect.Client[v1.GetLocationRequest, v1.GetLocationResponse]
}

// ListLocations calls location.v1.LocationService.ListLocations.
func (c *locationServiceClient) ListLocations(ctx context.Context, req *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error) {
	return c.listLocations.CallUnary(ctx, req)
}

// GetLocation calls location.v1.LocationService.GetLocation.
func (c *locationServiceClient) GetLocation(ctx context.Context, req *connect.Request[v1.GetLocationRequest]) (*connect.Response[v1.GetLocationResponse], error) {
	return c.getLocation.CallUnary(ctx, req)
}

// LocationServiceHandler is an implementation of the location.v1.LocationService service.
type LocationServiceHandler interface {
	ListLocations(context.Context, *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error)
	GetLocation(context.Context, *connect.Request[v1.GetLocationRequest]) (*connect.Response[v1.GetLocationResponse], error)
}

// NewLocationServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLocationServiceHandler(svc LocationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	locationServiceMethods := v1.File_location_v1_location_proto.Services().ByName("LocationService").Methods()
	locationServiceListLocationsHandler := connect.NewUnaryHandler(
		LocationServiceListLocationsProcedure,
		svc.ListLocations,
		connect.WithSchema(locationServiceMethods.ByName("ListLocations")),
		connect.WithHandlerOptions(opts...),
	)
	locationServiceGetLocationHandler := connect.NewUnaryHandler(
		LocationServiceGetLocationProcedure,
		svc.GetLocation,
		connect.WithSchema(locationServiceMethods.ByName("GetLocation")),
		connect.WithHandlerOptions(opts...),
	)
	return "/location.v1.LocationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LocationServiceListLocationsProcedure:
			locationServiceListLocationsHandler.ServeHTTP(w, r)
		case LocationServiceGetLocationProcedure:
			locationServiceGetLocationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLocationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLocationServiceHandler struct{}

func (UnimplementedLocationServiceHandler) ListLocations(context.Context, *connect.Request[v1.ListLocationsRequest]) (*connect.Response[v1.ListLocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("location.v1.LocationService.ListLocations is not implemented"))
}

func (UnimplementedLocationServiceHandler) GetLocation(context.Context, *connect.Request[v1.GetLocationRequest]) (*connect.Response[v1.GetLocationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("location.v1.LocationService.GetLocation is not implemented"))
}
