// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: landing/v1/landing.proto

package landingv1connect

import (
	v1 "com.gitlab/pobochiigo/bhole/proto/landing/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LandingServiceName is the fully-qualified name of the LandingService service.
	LandingServiceName = "landing.v1.LandingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LandingServiceListLandingsProcedure is the fully-qualified name of the LandingService's
	// ListLandings RPC.
	LandingServiceListLandingsProcedure = "/landing.v1.LandingService/ListLandings"
	// LandingServiceGetLandingProcedure is the fully-qualified name of the LandingService's GetLanding
	// RPC.
	LandingServiceGetLandingProcedure = "/landing.v1.LandingService/GetLanding"
)

// LandingServiceClient is a client for the landing.v1.LandingService service.
type LandingServiceClient interface {
	ListLandings(context.Context, *connect.Request[v1.ListLandingsRequest]) (*connect.Response[v1.ListLandingsResponse], error)
	GetLanding(context.Context, *connect.Request[v1.GetLandingRequest]) (*connect.Response[v1.GetLandingResponse], error)
}

// NewLandingServiceClient constructs a client for the landing.v1.LandingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLandingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LandingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	landingServiceMethods := v1.File_landing_v1_landing_proto.Services().ByName("LandingService").Methods()
	return &landingServiceClient{
		listLandings: connect.NewClient[v1.ListLandingsRequest, v1.ListLandingsResponse](
			httpClient,
			baseURL+LandingServiceListLandingsProcedure,
			connect.WithSchema(landingServiceMethods.ByName("ListLandings")),
			connect.WithClientOptions(opts...),
		),
		getLanding: connect.NewClient[v1.GetLandingRequest, v1.GetLandingResponse](
			httpClient,
			baseURL+LandingServiceGetLandingProcedure,
			connect.WithSchema(landingServiceMethods.ByName("GetLanding")),
			connect.WithClientOptions(opts...),
		),
	}
}

// landingServiceClient implements LandingServiceClient.
type landingServiceClient struct {
	listLandings *connect.Client[v1.ListLandingsRequest, v1.ListLandingsResponse]
	getLanding   *connect.Client[v1.GetLandingRequest, v1.GetLandingResponse]
}

// ListLandings calls landing.v1.LandingService.ListLandings.
func (c *landingServiceClient) ListLandings(ctx context.Context, req *connect.Request[v1.ListLandingsRequest]) (*connect.Response[v1.ListLandingsResponse], error) {
	return c.listLandings.CallUnary(ctx, req)
}

// GetLanding calls landing.v1.LandingService.GetLanding.
func (c *landingServiceClient) GetLanding(ctx context.Context, req *connect.Request[v1.GetLandingRequest]) (*connect.Response[v1.GetLandingResponse], error) {
	return c.getLanding.CallUnary(ctx, req)
}

// LandingServiceHandler is an implementation of the landing.v1.LandingService service.
type LandingServiceHandler interface {
	ListLandings(context.Context, *connect.Request[v1.ListLandingsRequest]) (*connect.Response[v1.ListLandingsResponse], error)
	GetLanding(context.Context, *connect.Request[v1.GetLandingRequest]) (*connect.Response[v1.GetLandingResponse], error)
}

// NewLandingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLandingServiceHandler(svc LandingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	landingServiceMethods := v1.File_landing_v1_landing_proto.Services().ByName("LandingService").Methods()
	landingServiceListLandingsHandler := connect.NewUnaryHandler(
		LandingServiceListLandingsProcedure,
		svc.ListLandings,
		connect.WithSchema(landingServiceMethods.ByName("ListLandings")),
		connect.WithHandlerOptions(opts...),
	)
	landingServiceGetLandingHandler := connect.NewUnaryHandler(
		LandingServiceGetLandingProcedure,
		svc.GetLanding,
		connect.WithSchema(landingServiceMethods.ByName("GetLanding")),
		connect.WithHandlerOptions(opts...),
	)
	return "/landing.v1.LandingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LandingServiceListLandingsProcedure:
			landingServiceListLandingsHandler.ServeHTTP(w, r)
		case LandingServiceGetLandingProcedure:
			landingServiceGetLandingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLandingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLandingServiceHandler struct{}

func (UnimplementedLandingServiceHandler) ListLandings(context.Context, *connect.Request[v1.ListLandingsRequest]) (*connect.Response[v1.ListLandingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("landing.v1.LandingService.ListLandings is not implemented"))
}

func (UnimplementedLandingServiceHandler) GetLanding(context.Context, *connect.Request[v1.GetLandingRequest]) (*connect.Response[v1.GetLandingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("landing.v1.LandingService.GetLanding is not implemented"))
}
