// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/astronaut/v1/astronaut.proto

package astronautv1connect

import (
	v1 "com.gitlab/pobochiigo/bhole/proto/astronaut/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AstronautServiceName is the fully-qualified name of the AstronautService service.
	AstronautServiceName = "astronaut.v1.AstronautService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AstronautServiceListAstronautsProcedure is the fully-qualified name of the AstronautService's
	// ListAstronauts RPC.
	AstronautServiceListAstronautsProcedure = "/astronaut.v1.AstronautService/ListAstronauts"
	// AstronautServiceGetAstronautProcedure is the fully-qualified name of the AstronautService's
	// GetAstronaut RPC.
	AstronautServiceGetAstronautProcedure = "/astronaut.v1.AstronautService/GetAstronaut"
)

// AstronautServiceClient is a client for the astronaut.v1.AstronautService service.
type AstronautServiceClient interface {
	ListAstronauts(context.Context, *connect.Request[v1.ListAstronautsRequest]) (*connect.Response[v1.ListAstronautsResponse], error)
	GetAstronaut(context.Context, *connect.Request[v1.GetAstronautRequest]) (*connect.Response[v1.GetAstronautResponse], error)
}

// NewAstronautServiceClient constructs a client for the astronaut.v1.AstronautService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAstronautServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AstronautServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	astronautServiceMethods := v1.File_proto_astronaut_v1_astronaut_proto.Services().ByName("AstronautService").Methods()
	return &astronautServiceClient{
		listAstronauts: connect.NewClient[v1.ListAstronautsRequest, v1.ListAstronautsResponse](
			httpClient,
			baseURL+AstronautServiceListAstronautsProcedure,
			connect.WithSchema(astronautServiceMethods.ByName("ListAstronauts")),
			connect.WithClientOptions(opts...),
		),
		getAstronaut: connect.NewClient[v1.GetAstronautRequest, v1.GetAstronautResponse](
			httpClient,
			baseURL+AstronautServiceGetAstronautProcedure,
			connect.WithSchema(astronautServiceMethods.ByName("GetAstronaut")),
			connect.WithClientOptions(opts...),
		),
	}
}

// astronautServiceClient implements AstronautServiceClient.
type astronautServiceClient struct {
	listAstronauts *connect.Client[v1.ListAstronautsRequest, v1.ListAstronautsResponse]
	getAstronaut   *connect.Client[v1.GetAstronautRequest, v1.GetAstronautResponse]
}

// ListAstronauts calls astronaut.v1.AstronautService.ListAstronauts.
func (c *astronautServiceClient) ListAstronauts(ctx context.Context, req *connect.Request[v1.ListAstronautsRequest]) (*connect.Response[v1.ListAstronautsResponse], error) {
	return c.listAstronauts.CallUnary(ctx, req)
}

// GetAstronaut calls astronaut.v1.AstronautService.GetAstronaut.
func (c *astronautServiceClient) GetAstronaut(ctx context.Context, req *connect.Request[v1.GetAstronautRequest]) (*connect.Response[v1.GetAstronautResponse], error) {
	return c.getAstronaut.CallUnary(ctx, req)
}

// AstronautServiceHandler is an implementation of the astronaut.v1.AstronautService service.
type AstronautServiceHandler interface {
	ListAstronauts(context.Context, *connect.Request[v1.ListAstronautsRequest]) (*connect.Response[v1.ListAstronautsResponse], error)
	GetAstronaut(context.Context, *connect.Request[v1.GetAstronautRequest]) (*connect.Response[v1.GetAstronautResponse], error)
}

// NewAstronautServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAstronautServiceHandler(svc AstronautServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	astronautServiceMethods := v1.File_proto_astronaut_v1_astronaut_proto.Services().ByName("AstronautService").Methods()
	astronautServiceListAstronautsHandler := connect.NewUnaryHandler(
		AstronautServiceListAstronautsProcedure,
		svc.ListAstronauts,
		connect.WithSchema(astronautServiceMethods.ByName("ListAstronauts")),
		connect.WithHandlerOptions(opts...),
	)
	astronautServiceGetAstronautHandler := connect.NewUnaryHandler(
		AstronautServiceGetAstronautProcedure,
		svc.GetAstronaut,
		connect.WithSchema(astronautServiceMethods.ByName("GetAstronaut")),
		connect.WithHandlerOptions(opts...),
	)
	return "/astronaut.v1.AstronautService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AstronautServiceListAstronautsProcedure:
			astronautServiceListAstronautsHandler.ServeHTTP(w, r)
		case AstronautServiceGetAstronautProcedure:
			astronautServiceGetAstronautHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAstronautServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAstronautServiceHandler struct{}

func (UnimplementedAstronautServiceHandler) ListAstronauts(context.Context, *connect.Request[v1.ListAstronautsRequest]) (*connect.Response[v1.ListAstronautsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("astronaut.v1.AstronautService.ListAstronauts is not implemented"))
}

func (UnimplementedAstronautServiceHandler) GetAstronaut(context.Context, *connect.Request[v1.GetAstronautRequest]) (*connect.Response[v1.GetAstronautResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("astronaut.v1.AstronautService.GetAstronaut is not implemented"))
}
