// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astronaut/v1/astronaut.proto

package astronautv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgencyMini struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,4,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	Type          *AgencyType            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyMini) Reset() {
	*x = AgencyMini{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyMini) ProtoMessage() {}

func (x *AgencyMini) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyMini.ProtoReflect.Descriptor instead.
func (*AgencyMini) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{0}
}

func (x *AgencyMini) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyMini) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyMini) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyMini) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyMini) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyMini) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgencyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyType) Reset() {
	*x = AgencyType{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyType) ProtoMessage() {}

func (x *AgencyType) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyType.ProtoReflect.Descriptor instead.
func (*AgencyType) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{1}
}

func (x *AgencyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Astronaut struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Age              *int32                 `protobuf:"varint,1,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Agency           *AgencyMini            `protobuf:"bytes,2,opt,name=agency,proto3" json:"agency,omitempty"`
	Bio              string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	DateOfBirth      *string                `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"`
	DateOfDeath      *string                `protobuf:"bytes,5,opt,name=date_of_death,json=dateOfDeath,proto3,oneof" json:"date_of_death,omitempty"`
	EvaTime          string                 `protobuf:"bytes,6,opt,name=eva_time,json=evaTime,proto3" json:"eva_time,omitempty"`
	FirstFlight      *string                `protobuf:"bytes,7,opt,name=first_flight,json=firstFlight,proto3,oneof" json:"first_flight,omitempty"`
	Id               int32                  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	Image            *Image                 `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	InSpace          bool                   `protobuf:"varint,10,opt,name=in_space,json=inSpace,proto3" json:"in_space,omitempty"`
	LastFlight       *string                `protobuf:"bytes,11,opt,name=last_flight,json=lastFlight,proto3,oneof" json:"last_flight,omitempty"`
	Name             string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Nationality      []*Country             `protobuf:"bytes,13,rep,name=nationality,proto3" json:"nationality,omitempty"`
	ResponseMode     string                 `protobuf:"bytes,14,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SocialMediaLinks []*SocialMediaLink     `protobuf:"bytes,15,rep,name=social_media_links,json=socialMediaLinks,proto3" json:"social_media_links,omitempty"`
	Status           *AstronautStatus       `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	TimeInSpace      *string                `protobuf:"bytes,17,opt,name=time_in_space,json=timeInSpace,proto3,oneof" json:"time_in_space,omitempty"`
	Type             *AstronautType         `protobuf:"bytes,18,opt,name=type,proto3" json:"type,omitempty"`
	Url              string                 `protobuf:"bytes,19,opt,name=url,proto3" json:"url,omitempty"`
	Wiki             *string                `protobuf:"bytes,20,opt,name=wiki,proto3,oneof" json:"wiki,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Astronaut) Reset() {
	*x = Astronaut{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Astronaut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Astronaut) ProtoMessage() {}

func (x *Astronaut) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Astronaut.ProtoReflect.Descriptor instead.
func (*Astronaut) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{2}
}

func (x *Astronaut) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *Astronaut) GetAgency() *AgencyMini {
	if x != nil {
		return x.Agency
	}
	return nil
}

func (x *Astronaut) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Astronaut) GetDateOfBirth() string {
	if x != nil && x.DateOfBirth != nil {
		return *x.DateOfBirth
	}
	return ""
}

func (x *Astronaut) GetDateOfDeath() string {
	if x != nil && x.DateOfDeath != nil {
		return *x.DateOfDeath
	}
	return ""
}

func (x *Astronaut) GetEvaTime() string {
	if x != nil {
		return x.EvaTime
	}
	return ""
}

func (x *Astronaut) GetFirstFlight() string {
	if x != nil && x.FirstFlight != nil {
		return *x.FirstFlight
	}
	return ""
}

func (x *Astronaut) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Astronaut) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Astronaut) GetInSpace() bool {
	if x != nil {
		return x.InSpace
	}
	return false
}

func (x *Astronaut) GetLastFlight() string {
	if x != nil && x.LastFlight != nil {
		return *x.LastFlight
	}
	return ""
}

func (x *Astronaut) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Astronaut) GetNationality() []*Country {
	if x != nil {
		return x.Nationality
	}
	return nil
}

func (x *Astronaut) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *Astronaut) GetSocialMediaLinks() []*SocialMediaLink {
	if x != nil {
		return x.SocialMediaLinks
	}
	return nil
}

func (x *Astronaut) GetStatus() *AstronautStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Astronaut) GetTimeInSpace() string {
	if x != nil && x.TimeInSpace != nil {
		return *x.TimeInSpace
	}
	return ""
}

func (x *Astronaut) GetType() *AstronautType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Astronaut) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Astronaut) GetWiki() string {
	if x != nil && x.Wiki != nil {
		return *x.Wiki
	}
	return ""
}

type AstronautStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstronautStatus) Reset() {
	*x = AstronautStatus{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstronautStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstronautStatus) ProtoMessage() {}

func (x *AstronautStatus) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstronautStatus.ProtoReflect.Descriptor instead.
func (*AstronautStatus) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{3}
}

func (x *AstronautStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AstronautStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AstronautType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AstronautType) Reset() {
	*x = AstronautType{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AstronautType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AstronautType) ProtoMessage() {}

func (x *AstronautType) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AstronautType.ProtoReflect.Descriptor instead.
func (*AstronautType) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{4}
}

func (x *AstronautType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AstronautType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Country struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Alpha_2Code             string                 `protobuf:"bytes,1,opt,name=alpha_2_code,json=alpha2Code,proto3" json:"alpha_2_code,omitempty"`
	Alpha_3Code             string                 `protobuf:"bytes,2,opt,name=alpha_3_code,json=alpha3Code,proto3" json:"alpha_3_code,omitempty"`
	Id                      int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NationalityName         string                 `protobuf:"bytes,5,opt,name=nationality_name,json=nationalityName,proto3" json:"nationality_name,omitempty"`
	NationalityNameComposed string                 `protobuf:"bytes,6,opt,name=nationality_name_composed,json=nationalityNameComposed,proto3" json:"nationality_name_composed,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{5}
}

func (x *Country) GetAlpha_2Code() string {
	if x != nil {
		return x.Alpha_2Code
	}
	return ""
}

func (x *Country) GetAlpha_3Code() string {
	if x != nil {
		return x.Alpha_3Code
	}
	return ""
}

func (x *Country) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetNationalityName() string {
	if x != nil {
		return x.NationalityName
	}
	return ""
}

func (x *Country) GetNationalityNameComposed() string {
	if x != nil {
		return x.NationalityNameComposed
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credit        *string                `protobuf:"bytes,1,opt,name=credit,proto3,oneof" json:"credit,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	License       *ImageLicense          `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SingleUse     bool                   `protobuf:"varint,6,opt,name=single_use,json=singleUse,proto3" json:"single_use,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Variants      []*ImageVariant        `protobuf:"bytes,8,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{6}
}

func (x *Image) GetCredit() string {
	if x != nil && x.Credit != nil {
		return *x.Credit
	}
	return ""
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Image) GetLicense() *ImageLicense {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetSingleUse() bool {
	if x != nil {
		return x.SingleUse
	}
	return false
}

func (x *Image) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Image) GetVariants() []*ImageVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ImageLicense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          *string                `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageLicense) Reset() {
	*x = ImageLicense{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageLicense) ProtoMessage() {}

func (x *ImageLicense) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageLicense.ProtoReflect.Descriptor instead.
func (*ImageLicense) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{7}
}

func (x *ImageLicense) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageLicense) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *ImageLicense) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageLicense) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type          *ImageVariantType      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariant) Reset() {
	*x = ImageVariant{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariant) ProtoMessage() {}

func (x *ImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariant.ProtoReflect.Descriptor instead.
func (*ImageVariant) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{8}
}

func (x *ImageVariant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariant) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageVariant) GetType() *ImageVariantType {
	if x != nil {
		return x.Type
	}
	return nil
}

type ImageVariantType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariantType) Reset() {
	*x = ImageVariantType{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariantType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariantType) ProtoMessage() {}

func (x *ImageVariantType) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariantType.ProtoReflect.Descriptor instead.
func (*ImageVariantType) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{9}
}

func (x *ImageVariantType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariantType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SocialMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Logo          *Image                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMedia) Reset() {
	*x = SocialMedia{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMedia) ProtoMessage() {}

func (x *SocialMedia) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMedia.ProtoReflect.Descriptor instead.
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{10}
}

func (x *SocialMedia) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMedia) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *SocialMedia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SocialMedia) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type SocialMediaLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SocialMedia   *SocialMedia           `protobuf:"bytes,2,opt,name=social_media,json=socialMedia,proto3" json:"social_media,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMediaLink) Reset() {
	*x = SocialMediaLink{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMediaLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMediaLink) ProtoMessage() {}

func (x *SocialMediaLink) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMediaLink.ProtoReflect.Descriptor instead.
func (*SocialMediaLink) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{11}
}

func (x *SocialMediaLink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMediaLink) GetSocialMedia() *SocialMedia {
	if x != nil {
		return x.SocialMedia
	}
	return nil
}

func (x *SocialMediaLink) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ListAstronautsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAstronautsRequest) Reset() {
	*x = ListAstronautsRequest{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAstronautsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAstronautsRequest) ProtoMessage() {}

func (x *ListAstronautsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAstronautsRequest.ProtoReflect.Descriptor instead.
func (*ListAstronautsRequest) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{12}
}

func (x *ListAstronautsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAstronautsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAstronautsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListAstronautsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListAstronautsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*Astronaut           `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAstronautsResponse) Reset() {
	*x = ListAstronautsResponse{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAstronautsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAstronautsResponse) ProtoMessage() {}

func (x *ListAstronautsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAstronautsResponse.ProtoReflect.Descriptor instead.
func (*ListAstronautsResponse) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{13}
}

func (x *ListAstronautsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListAstronautsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListAstronautsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListAstronautsResponse) GetResults() []*Astronaut {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetAstronautRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAstronautRequest) Reset() {
	*x = GetAstronautRequest{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAstronautRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAstronautRequest) ProtoMessage() {}

func (x *GetAstronautRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAstronautRequest.ProtoReflect.Descriptor instead.
func (*GetAstronautRequest) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{14}
}

func (x *GetAstronautRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAstronautRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetAstronautResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Astronaut     *Astronaut             `protobuf:"bytes,1,opt,name=astronaut,proto3" json:"astronaut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAstronautResponse) Reset() {
	*x = GetAstronautResponse{}
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAstronautResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAstronautResponse) ProtoMessage() {}

func (x *GetAstronautResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astronaut_v1_astronaut_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAstronautResponse.ProtoReflect.Descriptor instead.
func (*GetAstronautResponse) Descriptor() ([]byte, []int) {
	return file_astronaut_v1_astronaut_proto_rawDescGZIP(), []int{15}
}

func (x *GetAstronautResponse) GetAstronaut() *Astronaut {
	if x != nil {
		return x.Astronaut
	}
	return nil
}

var File_astronaut_v1_astronaut_proto protoreflect.FileDescriptor

const file_astronaut_v1_astronaut_proto_rawDesc = "" +
	"\n" +
	"\x1castronaut/v1/astronaut.proto\x12\fastronaut.v1\"\xad\x01\n" +
	"\n" +
	"AgencyMini\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\x04 \x01(\tR\fresponseMode\x12,\n" +
	"\x04type\x18\x05 \x01(\v2\x18.astronaut.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"0\n" +
	"\n" +
	"AgencyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xda\x06\n" +
	"\tAstronaut\x12\x15\n" +
	"\x03age\x18\x01 \x01(\x05H\x00R\x03age\x88\x01\x01\x120\n" +
	"\x06agency\x18\x02 \x01(\v2\x18.astronaut.v1.AgencyMiniR\x06agency\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12'\n" +
	"\rdate_of_birth\x18\x04 \x01(\tH\x01R\vdateOfBirth\x88\x01\x01\x12'\n" +
	"\rdate_of_death\x18\x05 \x01(\tH\x02R\vdateOfDeath\x88\x01\x01\x12\x19\n" +
	"\beva_time\x18\x06 \x01(\tR\aevaTime\x12&\n" +
	"\ffirst_flight\x18\a \x01(\tH\x03R\vfirstFlight\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\b \x01(\x05R\x02id\x12)\n" +
	"\x05image\x18\t \x01(\v2\x13.astronaut.v1.ImageR\x05image\x12\x19\n" +
	"\bin_space\x18\n" +
	" \x01(\bR\ainSpace\x12$\n" +
	"\vlast_flight\x18\v \x01(\tH\x04R\n" +
	"lastFlight\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x127\n" +
	"\vnationality\x18\r \x03(\v2\x15.astronaut.v1.CountryR\vnationality\x12#\n" +
	"\rresponse_mode\x18\x0e \x01(\tR\fresponseMode\x12K\n" +
	"\x12social_media_links\x18\x0f \x03(\v2\x1d.astronaut.v1.SocialMediaLinkR\x10socialMediaLinks\x125\n" +
	"\x06status\x18\x10 \x01(\v2\x1d.astronaut.v1.AstronautStatusR\x06status\x12'\n" +
	"\rtime_in_space\x18\x11 \x01(\tH\x05R\vtimeInSpace\x88\x01\x01\x12/\n" +
	"\x04type\x18\x12 \x01(\v2\x1b.astronaut.v1.AstronautTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x13 \x01(\tR\x03url\x12\x17\n" +
	"\x04wiki\x18\x14 \x01(\tH\x06R\x04wiki\x88\x01\x01B\x06\n" +
	"\x04_ageB\x10\n" +
	"\x0e_date_of_birthB\x10\n" +
	"\x0e_date_of_deathB\x0f\n" +
	"\r_first_flightB\x0e\n" +
	"\f_last_flightB\x10\n" +
	"\x0e_time_in_spaceB\a\n" +
	"\x05_wiki\"5\n" +
	"\x0fAstronautStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\rAstronautType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd8\x01\n" +
	"\aCountry\x12 \n" +
	"\falpha_2_code\x18\x01 \x01(\tR\n" +
	"alpha2Code\x12 \n" +
	"\falpha_3_code\x18\x02 \x01(\tR\n" +
	"alpha3Code\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x10nationality_name\x18\x05 \x01(\tR\x0fnationalityName\x12:\n" +
	"\x19nationality_name_composed\x18\x06 \x01(\tR\x17nationalityNameComposed\"\xa2\x02\n" +
	"\x05Image\x12\x1b\n" +
	"\x06credit\x18\x01 \x01(\tH\x00R\x06credit\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x124\n" +
	"\alicense\x18\x04 \x01(\v2\x1a.astronaut.v1.ImageLicenseR\alicense\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"single_use\x18\x06 \x01(\bR\tsingleUse\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x126\n" +
	"\bvariants\x18\b \x03(\v2\x1a.astronaut.v1.ImageVariantR\bvariantsB\t\n" +
	"\a_credit\"p\n" +
	"\fImageLicense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04link\x18\x02 \x01(\tH\x00R\x04link\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB\a\n" +
	"\x05_link\"o\n" +
	"\fImageVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x122\n" +
	"\x04type\x18\x03 \x01(\v2\x1e.astronaut.v1.ImageVariantTypeR\x04type\"6\n" +
	"\x10ImageVariantType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"y\n" +
	"\vSocialMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12'\n" +
	"\x04logo\x18\x02 \x01(\v2\x13.astronaut.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"~\n" +
	"\x0fSocialMediaLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12<\n" +
	"\fsocial_media\x18\x02 \x01(\v2\x19.astronaut.v1.SocialMediaR\vsocialMedia\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"q\n" +
	"\x15ListAstronautsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x91\x01\n" +
	"\x16ListAstronautsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x121\n" +
	"\aresults\x18\x04 \x03(\v2\x17.astronaut.v1.AstronautR\aresults\"9\n" +
	"\x13GetAstronautRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"M\n" +
	"\x14GetAstronautResponse\x125\n" +
	"\tastronaut\x18\x01 \x01(\v2\x17.astronaut.v1.AstronautR\tastronaut2\xc6\x01\n" +
	"\x10AstronautService\x12[\n" +
	"\x0eListAstronauts\x12#.astronaut.v1.ListAstronautsRequest\x1a$.astronaut.v1.ListAstronautsResponse\x12U\n" +
	"\fGetAstronaut\x12!.astronaut.v1.GetAstronautRequest\x1a\".astronaut.v1.GetAstronautResponseB<Z:github.com/pobochiigo/bhole/proto/astronaut/v1;astronautv1b\x06proto3"

var (
	file_astronaut_v1_astronaut_proto_rawDescOnce sync.Once
	file_astronaut_v1_astronaut_proto_rawDescData []byte
)

func file_astronaut_v1_astronaut_proto_rawDescGZIP() []byte {
	file_astronaut_v1_astronaut_proto_rawDescOnce.Do(func() {
		file_astronaut_v1_astronaut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astronaut_v1_astronaut_proto_rawDesc), len(file_astronaut_v1_astronaut_proto_rawDesc)))
	})
	return file_astronaut_v1_astronaut_proto_rawDescData
}

var file_astronaut_v1_astronaut_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_astronaut_v1_astronaut_proto_goTypes = []any{
	(*AgencyMini)(nil),             // 0: astronaut.v1.AgencyMini
	(*AgencyType)(nil),             // 1: astronaut.v1.AgencyType
	(*Astronaut)(nil),              // 2: astronaut.v1.Astronaut
	(*AstronautStatus)(nil),        // 3: astronaut.v1.AstronautStatus
	(*AstronautType)(nil),          // 4: astronaut.v1.AstronautType
	(*Country)(nil),                // 5: astronaut.v1.Country
	(*Image)(nil),                  // 6: astronaut.v1.Image
	(*ImageLicense)(nil),           // 7: astronaut.v1.ImageLicense
	(*ImageVariant)(nil),           // 8: astronaut.v1.ImageVariant
	(*ImageVariantType)(nil),       // 9: astronaut.v1.ImageVariantType
	(*SocialMedia)(nil),            // 10: astronaut.v1.SocialMedia
	(*SocialMediaLink)(nil),        // 11: astronaut.v1.SocialMediaLink
	(*ListAstronautsRequest)(nil),  // 12: astronaut.v1.ListAstronautsRequest
	(*ListAstronautsResponse)(nil), // 13: astronaut.v1.ListAstronautsResponse
	(*GetAstronautRequest)(nil),    // 14: astronaut.v1.GetAstronautRequest
	(*GetAstronautResponse)(nil),   // 15: astronaut.v1.GetAstronautResponse
}
var file_astronaut_v1_astronaut_proto_depIdxs = []int32{
	1,  // 0: astronaut.v1.AgencyMini.type:type_name -> astronaut.v1.AgencyType
	0,  // 1: astronaut.v1.Astronaut.agency:type_name -> astronaut.v1.AgencyMini
	6,  // 2: astronaut.v1.Astronaut.image:type_name -> astronaut.v1.Image
	5,  // 3: astronaut.v1.Astronaut.nationality:type_name -> astronaut.v1.Country
	11, // 4: astronaut.v1.Astronaut.social_media_links:type_name -> astronaut.v1.SocialMediaLink
	3,  // 5: astronaut.v1.Astronaut.status:type_name -> astronaut.v1.AstronautStatus
	4,  // 6: astronaut.v1.Astronaut.type:type_name -> astronaut.v1.AstronautType
	7,  // 7: astronaut.v1.Image.license:type_name -> astronaut.v1.ImageLicense
	8,  // 8: astronaut.v1.Image.variants:type_name -> astronaut.v1.ImageVariant
	9,  // 9: astronaut.v1.ImageVariant.type:type_name -> astronaut.v1.ImageVariantType
	6,  // 10: astronaut.v1.SocialMedia.logo:type_name -> astronaut.v1.Image
	10, // 11: astronaut.v1.SocialMediaLink.social_media:type_name -> astronaut.v1.SocialMedia
	2,  // 12: astronaut.v1.ListAstronautsResponse.results:type_name -> astronaut.v1.Astronaut
	2,  // 13: astronaut.v1.GetAstronautResponse.astronaut:type_name -> astronaut.v1.Astronaut
	12, // 14: astronaut.v1.AstronautService.ListAstronauts:input_type -> astronaut.v1.ListAstronautsRequest
	14, // 15: astronaut.v1.AstronautService.GetAstronaut:input_type -> astronaut.v1.GetAstronautRequest
	13, // 16: astronaut.v1.AstronautService.ListAstronauts:output_type -> astronaut.v1.ListAstronautsResponse
	15, // 17: astronaut.v1.AstronautService.GetAstronaut:output_type -> astronaut.v1.GetAstronautResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_astronaut_v1_astronaut_proto_init() }
func file_astronaut_v1_astronaut_proto_init() {
	if File_astronaut_v1_astronaut_proto != nil {
		return
	}
	file_astronaut_v1_astronaut_proto_msgTypes[2].OneofWrappers = []any{}
	file_astronaut_v1_astronaut_proto_msgTypes[6].OneofWrappers = []any{}
	file_astronaut_v1_astronaut_proto_msgTypes[7].OneofWrappers = []any{}
	file_astronaut_v1_astronaut_proto_msgTypes[10].OneofWrappers = []any{}
	file_astronaut_v1_astronaut_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astronaut_v1_astronaut_proto_rawDesc), len(file_astronaut_v1_astronaut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astronaut_v1_astronaut_proto_goTypes,
		DependencyIndexes: file_astronaut_v1_astronaut_proto_depIdxs,
		MessageInfos:      file_astronaut_v1_astronaut_proto_msgTypes,
	}.Build()
	File_astronaut_v1_astronaut_proto = out.File
	file_astronaut_v1_astronaut_proto_goTypes = nil
	file_astronaut_v1_astronaut_proto_depIdxs = nil
}
