// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: update/v1/update.proto

package updatev1connect

import (
	v1 "com.gitlab/pobochiigo/bhole/proto/update/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UpdateServiceName is the fully-qualified name of the UpdateService service.
	UpdateServiceName = "update.v1.UpdateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UpdateServiceListUpdatesProcedure is the fully-qualified name of the UpdateService's ListUpdates
	// RPC.
	UpdateServiceListUpdatesProcedure = "/update.v1.UpdateService/ListUpdates"
	// UpdateServiceGetUpdateProcedure is the fully-qualified name of the UpdateService's GetUpdate RPC.
	UpdateServiceGetUpdateProcedure = "/update.v1.UpdateService/GetUpdate"
)

// UpdateServiceClient is a client for the update.v1.UpdateService service.
type UpdateServiceClient interface {
	ListUpdates(context.Context, *connect.Request[v1.ListUpdatesRequest]) (*connect.Response[v1.ListUpdatesResponse], error)
	GetUpdate(context.Context, *connect.Request[v1.GetUpdateRequest]) (*connect.Response[v1.GetUpdateResponse], error)
}

// NewUpdateServiceClient constructs a client for the update.v1.UpdateService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUpdateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UpdateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	updateServiceMethods := v1.File_update_v1_update_proto.Services().ByName("UpdateService").Methods()
	return &updateServiceClient{
		listUpdates: connect.NewClient[v1.ListUpdatesRequest, v1.ListUpdatesResponse](
			httpClient,
			baseURL+UpdateServiceListUpdatesProcedure,
			connect.WithSchema(updateServiceMethods.ByName("ListUpdates")),
			connect.WithClientOptions(opts...),
		),
		getUpdate: connect.NewClient[v1.GetUpdateRequest, v1.GetUpdateResponse](
			httpClient,
			baseURL+UpdateServiceGetUpdateProcedure,
			connect.WithSchema(updateServiceMethods.ByName("GetUpdate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// updateServiceClient implements UpdateServiceClient.
type updateServiceClient struct {
	listUpdates *connect.Client[v1.ListUpdatesRequest, v1.ListUpdatesResponse]
	getUpdate   *connect.Client[v1.GetUpdateRequest, v1.GetUpdateResponse]
}

// ListUpdates calls update.v1.UpdateService.ListUpdates.
func (c *updateServiceClient) ListUpdates(ctx context.Context, req *connect.Request[v1.ListUpdatesRequest]) (*connect.Response[v1.ListUpdatesResponse], error) {
	return c.listUpdates.CallUnary(ctx, req)
}

// GetUpdate calls update.v1.UpdateService.GetUpdate.
func (c *updateServiceClient) GetUpdate(ctx context.Context, req *connect.Request[v1.GetUpdateRequest]) (*connect.Response[v1.GetUpdateResponse], error) {
	return c.getUpdate.CallUnary(ctx, req)
}

// UpdateServiceHandler is an implementation of the update.v1.UpdateService service.
type UpdateServiceHandler interface {
	ListUpdates(context.Context, *connect.Request[v1.ListUpdatesRequest]) (*connect.Response[v1.ListUpdatesResponse], error)
	GetUpdate(context.Context, *connect.Request[v1.GetUpdateRequest]) (*connect.Response[v1.GetUpdateResponse], error)
}

// NewUpdateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUpdateServiceHandler(svc UpdateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	updateServiceMethods := v1.File_update_v1_update_proto.Services().ByName("UpdateService").Methods()
	updateServiceListUpdatesHandler := connect.NewUnaryHandler(
		UpdateServiceListUpdatesProcedure,
		svc.ListUpdates,
		connect.WithSchema(updateServiceMethods.ByName("ListUpdates")),
		connect.WithHandlerOptions(opts...),
	)
	updateServiceGetUpdateHandler := connect.NewUnaryHandler(
		UpdateServiceGetUpdateProcedure,
		svc.GetUpdate,
		connect.WithSchema(updateServiceMethods.ByName("GetUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/update.v1.UpdateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UpdateServiceListUpdatesProcedure:
			updateServiceListUpdatesHandler.ServeHTTP(w, r)
		case UpdateServiceGetUpdateProcedure:
			updateServiceGetUpdateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUpdateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUpdateServiceHandler struct{}

func (UnimplementedUpdateServiceHandler) ListUpdates(context.Context, *connect.Request[v1.ListUpdatesRequest]) (*connect.Response[v1.ListUpdatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("update.v1.UpdateService.ListUpdates is not implemented"))
}

func (UnimplementedUpdateServiceHandler) GetUpdate(context.Context, *connect.Request[v1.GetUpdateRequest]) (*connect.Response[v1.GetUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("update.v1.UpdateService.GetUpdate is not implemented"))
}
