// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payload/v1/payload.proto

package payloadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgencyDetailed struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev                        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Administrator                 *string                `protobuf:"bytes,2,opt,name=administrator,proto3,oneof" json:"administrator,omitempty"`
	AttemptedLandings             *int32                 `protobuf:"varint,3,opt,name=attempted_landings,json=attemptedLandings,proto3,oneof" json:"attempted_landings,omitempty"`
	AttemptedLandingsPayload      *int32                 `protobuf:"varint,4,opt,name=attempted_landings_payload,json=attemptedLandingsPayload,proto3,oneof" json:"attempted_landings_payload,omitempty"`
	AttemptedLandingsSpacecraft   *int32                 `protobuf:"varint,5,opt,name=attempted_landings_spacecraft,json=attemptedLandingsSpacecraft,proto3,oneof" json:"attempted_landings_spacecraft,omitempty"`
	ConsecutiveSuccessfulLandings *int32                 `protobuf:"varint,6,opt,name=consecutive_successful_landings,json=consecutiveSuccessfulLandings,proto3,oneof" json:"consecutive_successful_landings,omitempty"`
	ConsecutiveSuccessfulLaunches *int32                 `protobuf:"varint,7,opt,name=consecutive_successful_launches,json=consecutiveSuccessfulLaunches,proto3,oneof" json:"consecutive_successful_launches,omitempty"`
	Country                       []*Country             `protobuf:"bytes,8,rep,name=country,proto3" json:"country,omitempty"`
	Description                   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	FailedLandings                *int32                 `protobuf:"varint,10,opt,name=failed_landings,json=failedLandings,proto3,oneof" json:"failed_landings,omitempty"`
	FailedLandingsPayload         *int32                 `protobuf:"varint,11,opt,name=failed_landings_payload,json=failedLandingsPayload,proto3,oneof" json:"failed_landings_payload,omitempty"`
	FailedLandingsSpacecraft      *int32                 `protobuf:"varint,12,opt,name=failed_landings_spacecraft,json=failedLandingsSpacecraft,proto3,oneof" json:"failed_landings_spacecraft,omitempty"`
	FailedLaunches                *int32                 `protobuf:"varint,13,opt,name=failed_launches,json=failedLaunches,proto3,oneof" json:"failed_launches,omitempty"`
	Featured                      bool                   `protobuf:"varint,14,opt,name=featured,proto3" json:"featured,omitempty"`
	FoundingYear                  *int32                 `protobuf:"varint,15,opt,name=founding_year,json=foundingYear,proto3,oneof" json:"founding_year,omitempty"`
	Id                            int32                  `protobuf:"varint,16,opt,name=id,proto3" json:"id,omitempty"`
	Image                         *Image                 `protobuf:"bytes,17,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl                       *string                `protobuf:"bytes,18,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	Launchers                     string                 `protobuf:"bytes,19,opt,name=launchers,proto3" json:"launchers,omitempty"`
	Logo                          *Image                 `protobuf:"bytes,20,opt,name=logo,proto3" json:"logo,omitempty"`
	Name                          string                 `protobuf:"bytes,21,opt,name=name,proto3" json:"name,omitempty"`
	Parent                        *string                `protobuf:"bytes,22,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	PendingLaunches               *int32                 `protobuf:"varint,23,opt,name=pending_launches,json=pendingLaunches,proto3,oneof" json:"pending_launches,omitempty"`
	ResponseMode                  string                 `protobuf:"bytes,24,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	SocialLogo                    *Image                 `protobuf:"bytes,25,opt,name=social_logo,json=socialLogo,proto3" json:"social_logo,omitempty"`
	SocialMediaLinks              []*SocialMediaLink     `protobuf:"bytes,26,rep,name=social_media_links,json=socialMediaLinks,proto3" json:"social_media_links,omitempty"`
	Spacecraft                    string                 `protobuf:"bytes,27,opt,name=spacecraft,proto3" json:"spacecraft,omitempty"`
	SuccessfulLandings            *int32                 `protobuf:"varint,28,opt,name=successful_landings,json=successfulLandings,proto3,oneof" json:"successful_landings,omitempty"`
	SuccessfulLandingsPayload     *int32                 `protobuf:"varint,29,opt,name=successful_landings_payload,json=successfulLandingsPayload,proto3,oneof" json:"successful_landings_payload,omitempty"`
	SuccessfulLandingsSpacecraft  *int32                 `protobuf:"varint,30,opt,name=successful_landings_spacecraft,json=successfulLandingsSpacecraft,proto3,oneof" json:"successful_landings_spacecraft,omitempty"`
	SuccessfulLaunches            *int32                 `protobuf:"varint,31,opt,name=successful_launches,json=successfulLaunches,proto3,oneof" json:"successful_launches,omitempty"`
	TotalLaunchCount              *int32                 `protobuf:"varint,32,opt,name=total_launch_count,json=totalLaunchCount,proto3,oneof" json:"total_launch_count,omitempty"`
	Type                          *AgencyType            `protobuf:"bytes,33,opt,name=type,proto3" json:"type,omitempty"`
	Url                           string                 `protobuf:"bytes,34,opt,name=url,proto3" json:"url,omitempty"`
	WikiUrl                       *string                `protobuf:"bytes,35,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AgencyDetailed) Reset() {
	*x = AgencyDetailed{}
	mi := &file_payload_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyDetailed) ProtoMessage() {}

func (x *AgencyDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyDetailed.ProtoReflect.Descriptor instead.
func (*AgencyDetailed) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *AgencyDetailed) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyDetailed) GetAdministrator() string {
	if x != nil && x.Administrator != nil {
		return *x.Administrator
	}
	return ""
}

func (x *AgencyDetailed) GetAttemptedLandings() int32 {
	if x != nil && x.AttemptedLandings != nil {
		return *x.AttemptedLandings
	}
	return 0
}

func (x *AgencyDetailed) GetAttemptedLandingsPayload() int32 {
	if x != nil && x.AttemptedLandingsPayload != nil {
		return *x.AttemptedLandingsPayload
	}
	return 0
}

func (x *AgencyDetailed) GetAttemptedLandingsSpacecraft() int32 {
	if x != nil && x.AttemptedLandingsSpacecraft != nil {
		return *x.AttemptedLandingsSpacecraft
	}
	return 0
}

func (x *AgencyDetailed) GetConsecutiveSuccessfulLandings() int32 {
	if x != nil && x.ConsecutiveSuccessfulLandings != nil {
		return *x.ConsecutiveSuccessfulLandings
	}
	return 0
}

func (x *AgencyDetailed) GetConsecutiveSuccessfulLaunches() int32 {
	if x != nil && x.ConsecutiveSuccessfulLaunches != nil {
		return *x.ConsecutiveSuccessfulLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetCountry() []*Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *AgencyDetailed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AgencyDetailed) GetFailedLandings() int32 {
	if x != nil && x.FailedLandings != nil {
		return *x.FailedLandings
	}
	return 0
}

func (x *AgencyDetailed) GetFailedLandingsPayload() int32 {
	if x != nil && x.FailedLandingsPayload != nil {
		return *x.FailedLandingsPayload
	}
	return 0
}

func (x *AgencyDetailed) GetFailedLandingsSpacecraft() int32 {
	if x != nil && x.FailedLandingsSpacecraft != nil {
		return *x.FailedLandingsSpacecraft
	}
	return 0
}

func (x *AgencyDetailed) GetFailedLaunches() int32 {
	if x != nil && x.FailedLaunches != nil {
		return *x.FailedLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *AgencyDetailed) GetFoundingYear() int32 {
	if x != nil && x.FoundingYear != nil {
		return *x.FoundingYear
	}
	return 0
}

func (x *AgencyDetailed) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyDetailed) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *AgencyDetailed) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *AgencyDetailed) GetLaunchers() string {
	if x != nil {
		return x.Launchers
	}
	return ""
}

func (x *AgencyDetailed) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *AgencyDetailed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyDetailed) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *AgencyDetailed) GetPendingLaunches() int32 {
	if x != nil && x.PendingLaunches != nil {
		return *x.PendingLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyDetailed) GetSocialLogo() *Image {
	if x != nil {
		return x.SocialLogo
	}
	return nil
}

func (x *AgencyDetailed) GetSocialMediaLinks() []*SocialMediaLink {
	if x != nil {
		return x.SocialMediaLinks
	}
	return nil
}

func (x *AgencyDetailed) GetSpacecraft() string {
	if x != nil {
		return x.Spacecraft
	}
	return ""
}

func (x *AgencyDetailed) GetSuccessfulLandings() int32 {
	if x != nil && x.SuccessfulLandings != nil {
		return *x.SuccessfulLandings
	}
	return 0
}

func (x *AgencyDetailed) GetSuccessfulLandingsPayload() int32 {
	if x != nil && x.SuccessfulLandingsPayload != nil {
		return *x.SuccessfulLandingsPayload
	}
	return 0
}

func (x *AgencyDetailed) GetSuccessfulLandingsSpacecraft() int32 {
	if x != nil && x.SuccessfulLandingsSpacecraft != nil {
		return *x.SuccessfulLandingsSpacecraft
	}
	return 0
}

func (x *AgencyDetailed) GetSuccessfulLaunches() int32 {
	if x != nil && x.SuccessfulLaunches != nil {
		return *x.SuccessfulLaunches
	}
	return 0
}

func (x *AgencyDetailed) GetTotalLaunchCount() int32 {
	if x != nil && x.TotalLaunchCount != nil {
		return *x.TotalLaunchCount
	}
	return 0
}

func (x *AgencyDetailed) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyDetailed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AgencyDetailed) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type AgencyMini struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,4,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	Type          *AgencyType            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyMini) Reset() {
	*x = AgencyMini{}
	mi := &file_payload_v1_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyMini) ProtoMessage() {}

func (x *AgencyMini) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyMini.ProtoReflect.Descriptor instead.
func (*AgencyMini) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{1}
}

func (x *AgencyMini) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyMini) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyMini) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyMini) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyMini) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyMini) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgencyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyType) Reset() {
	*x = AgencyType{}
	mi := &file_payload_v1_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyType) ProtoMessage() {}

func (x *AgencyType) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyType.ProtoReflect.Descriptor instead.
func (*AgencyType) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{2}
}

func (x *AgencyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Country struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Alpha_2Code             string                 `protobuf:"bytes,1,opt,name=alpha_2_code,json=alpha2Code,proto3" json:"alpha_2_code,omitempty"`
	Alpha_3Code             string                 `protobuf:"bytes,2,opt,name=alpha_3_code,json=alpha3Code,proto3" json:"alpha_3_code,omitempty"`
	Id                      int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name                    string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NationalityName         string                 `protobuf:"bytes,5,opt,name=nationality_name,json=nationalityName,proto3" json:"nationality_name,omitempty"`
	NationalityNameComposed string                 `protobuf:"bytes,6,opt,name=nationality_name_composed,json=nationalityNameComposed,proto3" json:"nationality_name_composed,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_payload_v1_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{3}
}

func (x *Country) GetAlpha_2Code() string {
	if x != nil {
		return x.Alpha_2Code
	}
	return ""
}

func (x *Country) GetAlpha_3Code() string {
	if x != nil {
		return x.Alpha_3Code
	}
	return ""
}

func (x *Country) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetNationalityName() string {
	if x != nil {
		return x.NationalityName
	}
	return ""
}

func (x *Country) GetNationalityNameComposed() string {
	if x != nil {
		return x.NationalityNameComposed
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credit        *string                `protobuf:"bytes,1,opt,name=credit,proto3,oneof" json:"credit,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	License       *ImageLicense          `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SingleUse     bool                   `protobuf:"varint,6,opt,name=single_use,json=singleUse,proto3" json:"single_use,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Variants      []*ImageVariant        `protobuf:"bytes,8,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_payload_v1_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetCredit() string {
	if x != nil && x.Credit != nil {
		return *x.Credit
	}
	return ""
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Image) GetLicense() *ImageLicense {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetSingleUse() bool {
	if x != nil {
		return x.SingleUse
	}
	return false
}

func (x *Image) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Image) GetVariants() []*ImageVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ImageLicense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          *string                `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageLicense) Reset() {
	*x = ImageLicense{}
	mi := &file_payload_v1_payload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageLicense) ProtoMessage() {}

func (x *ImageLicense) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageLicense.ProtoReflect.Descriptor instead.
func (*ImageLicense) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{5}
}

func (x *ImageLicense) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageLicense) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *ImageLicense) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageLicense) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type          *ImageVariantType      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariant) Reset() {
	*x = ImageVariant{}
	mi := &file_payload_v1_payload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariant) ProtoMessage() {}

func (x *ImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariant.ProtoReflect.Descriptor instead.
func (*ImageVariant) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{6}
}

func (x *ImageVariant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariant) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageVariant) GetType() *ImageVariantType {
	if x != nil {
		return x.Type
	}
	return nil
}

type ImageVariantType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariantType) Reset() {
	*x = ImageVariantType{}
	mi := &file_payload_v1_payload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariantType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariantType) ProtoMessage() {}

func (x *ImageVariantType) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariantType.ProtoReflect.Descriptor instead.
func (*ImageVariantType) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{7}
}

func (x *ImageVariantType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariantType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MissionPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agency        *AgencyMini            `protobuf:"bytes,1,opt,name=agency,proto3" json:"agency,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,6,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionPatch) Reset() {
	*x = MissionPatch{}
	mi := &file_payload_v1_payload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionPatch) ProtoMessage() {}

func (x *MissionPatch) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionPatch.ProtoReflect.Descriptor instead.
func (*MissionPatch) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{8}
}

func (x *MissionPatch) GetAgency() *AgencyMini {
	if x != nil {
		return x.Agency
	}
	return nil
}

func (x *MissionPatch) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MissionPatch) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MissionPatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MissionPatch) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MissionPatch) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          *int32                 `protobuf:"varint,1,opt,name=cost,proto3,oneof" json:"cost,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Image         *Image                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	InfoLink      string                 `protobuf:"bytes,5,opt,name=info_link,json=infoLink,proto3" json:"info_link,omitempty"`
	Manufacturer  *AgencyDetailed        `protobuf:"bytes,6,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Mass          *float32               `protobuf:"fixed32,7,opt,name=mass,proto3,oneof" json:"mass,omitempty"`
	Name          string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Operator      *AgencyDetailed        `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	Program       []*ProgramNormal       `protobuf:"bytes,10,rep,name=program,proto3" json:"program,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,11,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	Type          *PayloadType           `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	WikiLink      string                 `protobuf:"bytes,13,opt,name=wiki_link,json=wikiLink,proto3" json:"wiki_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_payload_v1_payload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{9}
}

func (x *Payload) GetCost() int32 {
	if x != nil && x.Cost != nil {
		return *x.Cost
	}
	return 0
}

func (x *Payload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Payload) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payload) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Payload) GetInfoLink() string {
	if x != nil {
		return x.InfoLink
	}
	return ""
}

func (x *Payload) GetManufacturer() *AgencyDetailed {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *Payload) GetMass() float32 {
	if x != nil && x.Mass != nil {
		return *x.Mass
	}
	return 0
}

func (x *Payload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Payload) GetOperator() *AgencyDetailed {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *Payload) GetProgram() []*ProgramNormal {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *Payload) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *Payload) GetType() *PayloadType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Payload) GetWikiLink() string {
	if x != nil {
		return x.WikiLink
	}
	return ""
}

type PayloadType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadType) Reset() {
	*x = PayloadType{}
	mi := &file_payload_v1_payload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadType) ProtoMessage() {}

func (x *PayloadType) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadType.ProtoReflect.Descriptor instead.
func (*PayloadType) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{10}
}

func (x *PayloadType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PayloadType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProgramNormal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Agencies       []*AgencyMini          `protobuf:"bytes,1,rep,name=agencies,proto3" json:"agencies,omitempty"`
	Description    *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	EndDate        *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Id             int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Image          *Image                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl        *string                `protobuf:"bytes,6,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	MissionPatches []*MissionPatch        `protobuf:"bytes,7,rep,name=mission_patches,json=missionPatches,proto3" json:"mission_patches,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode   string                 `protobuf:"bytes,9,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	StartDate      *string                `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	Type           *ProgramType           `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Url            string                 `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	WikiUrl        *string                `protobuf:"bytes,13,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgramNormal) Reset() {
	*x = ProgramNormal{}
	mi := &file_payload_v1_payload_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramNormal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramNormal) ProtoMessage() {}

func (x *ProgramNormal) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramNormal.ProtoReflect.Descriptor instead.
func (*ProgramNormal) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{11}
}

func (x *ProgramNormal) GetAgencies() []*AgencyMini {
	if x != nil {
		return x.Agencies
	}
	return nil
}

func (x *ProgramNormal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProgramNormal) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *ProgramNormal) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramNormal) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ProgramNormal) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *ProgramNormal) GetMissionPatches() []*MissionPatch {
	if x != nil {
		return x.MissionPatches
	}
	return nil
}

func (x *ProgramNormal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramNormal) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *ProgramNormal) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *ProgramNormal) GetType() *ProgramType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ProgramNormal) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProgramNormal) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type ProgramType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramType) Reset() {
	*x = ProgramType{}
	mi := &file_payload_v1_payload_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramType) ProtoMessage() {}

func (x *ProgramType) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramType.ProtoReflect.Descriptor instead.
func (*ProgramType) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{12}
}

func (x *ProgramType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SocialMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Logo          *Image                 `protobuf:"bytes,2,opt,name=logo,proto3" json:"logo,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Url           *string                `protobuf:"bytes,4,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMedia) Reset() {
	*x = SocialMedia{}
	mi := &file_payload_v1_payload_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMedia) ProtoMessage() {}

func (x *SocialMedia) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMedia.ProtoReflect.Descriptor instead.
func (*SocialMedia) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{13}
}

func (x *SocialMedia) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMedia) GetLogo() *Image {
	if x != nil {
		return x.Logo
	}
	return nil
}

func (x *SocialMedia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SocialMedia) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type SocialMediaLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SocialMedia   *SocialMedia           `protobuf:"bytes,2,opt,name=social_media,json=socialMedia,proto3" json:"social_media,omitempty"`
	Url           *string                `protobuf:"bytes,3,opt,name=url,proto3,oneof" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialMediaLink) Reset() {
	*x = SocialMediaLink{}
	mi := &file_payload_v1_payload_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialMediaLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialMediaLink) ProtoMessage() {}

func (x *SocialMediaLink) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialMediaLink.ProtoReflect.Descriptor instead.
func (*SocialMediaLink) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{14}
}

func (x *SocialMediaLink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialMediaLink) GetSocialMedia() *SocialMedia {
	if x != nil {
		return x.SocialMedia
	}
	return nil
}

func (x *SocialMediaLink) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

type ListPayloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPayloadsRequest) Reset() {
	*x = ListPayloadsRequest{}
	mi := &file_payload_v1_payload_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPayloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPayloadsRequest) ProtoMessage() {}

func (x *ListPayloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPayloadsRequest.ProtoReflect.Descriptor instead.
func (*ListPayloadsRequest) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{15}
}

func (x *ListPayloadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPayloadsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListPayloadsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListPayloadsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListPayloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*Payload             `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPayloadsResponse) Reset() {
	*x = ListPayloadsResponse{}
	mi := &file_payload_v1_payload_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPayloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPayloadsResponse) ProtoMessage() {}

func (x *ListPayloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPayloadsResponse.ProtoReflect.Descriptor instead.
func (*ListPayloadsResponse) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{16}
}

func (x *ListPayloadsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListPayloadsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListPayloadsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListPayloadsResponse) GetResults() []*Payload {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayloadRequest) Reset() {
	*x = GetPayloadRequest{}
	mi := &file_payload_v1_payload_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayloadRequest) ProtoMessage() {}

func (x *GetPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayloadRequest.ProtoReflect.Descriptor instead.
func (*GetPayloadRequest) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{17}
}

func (x *GetPayloadRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPayloadRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *Payload               `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayloadResponse) Reset() {
	*x = GetPayloadResponse{}
	mi := &file_payload_v1_payload_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayloadResponse) ProtoMessage() {}

func (x *GetPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_v1_payload_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayloadResponse.ProtoReflect.Descriptor instead.
func (*GetPayloadResponse) Descriptor() ([]byte, []int) {
	return file_payload_v1_payload_proto_rawDescGZIP(), []int{18}
}

func (x *GetPayloadResponse) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_payload_v1_payload_proto protoreflect.FileDescriptor

const file_payload_v1_payload_proto_rawDesc = "" +
	"\n" +
	"\x18payload/v1/payload.proto\x12\n" +
	"payload.v1\"\xf0\x10\n" +
	"\x0eAgencyDetailed\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12)\n" +
	"\radministrator\x18\x02 \x01(\tH\x00R\radministrator\x88\x01\x01\x122\n" +
	"\x12attempted_landings\x18\x03 \x01(\x05H\x01R\x11attemptedLandings\x88\x01\x01\x12A\n" +
	"\x1aattempted_landings_payload\x18\x04 \x01(\x05H\x02R\x18attemptedLandingsPayload\x88\x01\x01\x12G\n" +
	"\x1dattempted_landings_spacecraft\x18\x05 \x01(\x05H\x03R\x1battemptedLandingsSpacecraft\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_landings\x18\x06 \x01(\x05H\x04R\x1dconsecutiveSuccessfulLandings\x88\x01\x01\x12K\n" +
	"\x1fconsecutive_successful_launches\x18\a \x01(\x05H\x05R\x1dconsecutiveSuccessfulLaunches\x88\x01\x01\x12-\n" +
	"\acountry\x18\b \x03(\v2\x13.payload.v1.CountryR\acountry\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x06R\vdescription\x88\x01\x01\x12,\n" +
	"\x0ffailed_landings\x18\n" +
	" \x01(\x05H\aR\x0efailedLandings\x88\x01\x01\x12;\n" +
	"\x17failed_landings_payload\x18\v \x01(\x05H\bR\x15failedLandingsPayload\x88\x01\x01\x12A\n" +
	"\x1afailed_landings_spacecraft\x18\f \x01(\x05H\tR\x18failedLandingsSpacecraft\x88\x01\x01\x12,\n" +
	"\x0ffailed_launches\x18\r \x01(\x05H\n" +
	"R\x0efailedLaunches\x88\x01\x01\x12\x1a\n" +
	"\bfeatured\x18\x0e \x01(\bR\bfeatured\x12(\n" +
	"\rfounding_year\x18\x0f \x01(\x05H\vR\ffoundingYear\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x10 \x01(\x05R\x02id\x12'\n" +
	"\x05image\x18\x11 \x01(\v2\x11.payload.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\x12 \x01(\tH\fR\ainfoUrl\x88\x01\x01\x12\x1c\n" +
	"\tlaunchers\x18\x13 \x01(\tR\tlaunchers\x12%\n" +
	"\x04logo\x18\x14 \x01(\v2\x11.payload.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\x15 \x01(\tR\x04name\x12\x1b\n" +
	"\x06parent\x18\x16 \x01(\tH\rR\x06parent\x88\x01\x01\x12.\n" +
	"\x10pending_launches\x18\x17 \x01(\x05H\x0eR\x0fpendingLaunches\x88\x01\x01\x12#\n" +
	"\rresponse_mode\x18\x18 \x01(\tR\fresponseMode\x122\n" +
	"\vsocial_logo\x18\x19 \x01(\v2\x11.payload.v1.ImageR\n" +
	"socialLogo\x12I\n" +
	"\x12social_media_links\x18\x1a \x03(\v2\x1b.payload.v1.SocialMediaLinkR\x10socialMediaLinks\x12\x1e\n" +
	"\n" +
	"spacecraft\x18\x1b \x01(\tR\n" +
	"spacecraft\x124\n" +
	"\x13successful_landings\x18\x1c \x01(\x05H\x0fR\x12successfulLandings\x88\x01\x01\x12C\n" +
	"\x1bsuccessful_landings_payload\x18\x1d \x01(\x05H\x10R\x19successfulLandingsPayload\x88\x01\x01\x12I\n" +
	"\x1esuccessful_landings_spacecraft\x18\x1e \x01(\x05H\x11R\x1csuccessfulLandingsSpacecraft\x88\x01\x01\x124\n" +
	"\x13successful_launches\x18\x1f \x01(\x05H\x12R\x12successfulLaunches\x88\x01\x01\x121\n" +
	"\x12total_launch_count\x18  \x01(\x05H\x13R\x10totalLaunchCount\x88\x01\x01\x12*\n" +
	"\x04type\x18! \x01(\v2\x16.payload.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\" \x01(\tR\x03url\x12\x1e\n" +
	"\bwiki_url\x18# \x01(\tH\x14R\awikiUrl\x88\x01\x01B\x10\n" +
	"\x0e_administratorB\x15\n" +
	"\x13_attempted_landingsB\x1d\n" +
	"\x1b_attempted_landings_payloadB \n" +
	"\x1e_attempted_landings_spacecraftB\"\n" +
	" _consecutive_successful_landingsB\"\n" +
	" _consecutive_successful_launchesB\x0e\n" +
	"\f_descriptionB\x12\n" +
	"\x10_failed_landingsB\x1a\n" +
	"\x18_failed_landings_payloadB\x1d\n" +
	"\x1b_failed_landings_spacecraftB\x12\n" +
	"\x10_failed_launchesB\x10\n" +
	"\x0e_founding_yearB\v\n" +
	"\t_info_urlB\t\n" +
	"\a_parentB\x13\n" +
	"\x11_pending_launchesB\x16\n" +
	"\x14_successful_landingsB\x1e\n" +
	"\x1c_successful_landings_payloadB!\n" +
	"\x1f_successful_landings_spacecraftB\x16\n" +
	"\x14_successful_launchesB\x15\n" +
	"\x13_total_launch_countB\v\n" +
	"\t_wiki_url\"\xab\x01\n" +
	"\n" +
	"AgencyMini\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\x04 \x01(\tR\fresponseMode\x12*\n" +
	"\x04type\x18\x05 \x01(\v2\x16.payload.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"0\n" +
	"\n" +
	"AgencyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd8\x01\n" +
	"\aCountry\x12 \n" +
	"\falpha_2_code\x18\x01 \x01(\tR\n" +
	"alpha2Code\x12 \n" +
	"\falpha_3_code\x18\x02 \x01(\tR\n" +
	"alpha3Code\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x10nationality_name\x18\x05 \x01(\tR\x0fnationalityName\x12:\n" +
	"\x19nationality_name_composed\x18\x06 \x01(\tR\x17nationalityNameComposed\"\x9e\x02\n" +
	"\x05Image\x12\x1b\n" +
	"\x06credit\x18\x01 \x01(\tH\x00R\x06credit\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x122\n" +
	"\alicense\x18\x04 \x01(\v2\x18.payload.v1.ImageLicenseR\alicense\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"single_use\x18\x06 \x01(\bR\tsingleUse\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x124\n" +
	"\bvariants\x18\b \x03(\v2\x18.payload.v1.ImageVariantR\bvariantsB\t\n" +
	"\a_credit\"p\n" +
	"\fImageLicense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04link\x18\x02 \x01(\tH\x00R\x04link\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB\a\n" +
	"\x05_link\"m\n" +
	"\fImageVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x120\n" +
	"\x04type\x18\x03 \x01(\v2\x1c.payload.v1.ImageVariantTypeR\x04type\"6\n" +
	"\x10ImageVariantType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc0\x01\n" +
	"\fMissionPatch\x12.\n" +
	"\x06agency\x18\x01 \x01(\v2\x16.payload.v1.AgencyMiniR\x06agency\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12#\n" +
	"\rresponse_mode\x18\x06 \x01(\tR\fresponseMode\"\xf5\x03\n" +
	"\aPayload\x12\x17\n" +
	"\x04cost\x18\x01 \x01(\x05H\x00R\x04cost\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12'\n" +
	"\x05image\x18\x04 \x01(\v2\x11.payload.v1.ImageR\x05image\x12\x1b\n" +
	"\tinfo_link\x18\x05 \x01(\tR\binfoLink\x12>\n" +
	"\fmanufacturer\x18\x06 \x01(\v2\x1a.payload.v1.AgencyDetailedR\fmanufacturer\x12\x17\n" +
	"\x04mass\x18\a \x01(\x02H\x01R\x04mass\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x126\n" +
	"\boperator\x18\t \x01(\v2\x1a.payload.v1.AgencyDetailedR\boperator\x123\n" +
	"\aprogram\x18\n" +
	" \x03(\v2\x19.payload.v1.ProgramNormalR\aprogram\x12#\n" +
	"\rresponse_mode\x18\v \x01(\tR\fresponseMode\x12+\n" +
	"\x04type\x18\f \x01(\v2\x17.payload.v1.PayloadTypeR\x04type\x12\x1b\n" +
	"\twiki_link\x18\r \x01(\tR\bwikiLinkB\a\n" +
	"\x05_costB\a\n" +
	"\x05_mass\"1\n" +
	"\vPayloadType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa8\x04\n" +
	"\rProgramNormal\x122\n" +
	"\bagencies\x18\x01 \x03(\v2\x16.payload.v1.AgencyMiniR\bagencies\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\tH\x01R\aendDate\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\x12'\n" +
	"\x05image\x18\x05 \x01(\v2\x11.payload.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\x06 \x01(\tH\x02R\ainfoUrl\x88\x01\x01\x12A\n" +
	"\x0fmission_patches\x18\a \x03(\v2\x18.payload.v1.MissionPatchR\x0emissionPatches\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\t \x01(\tR\fresponseMode\x12\"\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\tH\x03R\tstartDate\x88\x01\x01\x12+\n" +
	"\x04type\x18\v \x01(\v2\x17.payload.v1.ProgramTypeR\x04type\x12\x10\n" +
	"\x03url\x18\f \x01(\tR\x03url\x12\x1e\n" +
	"\bwiki_url\x18\r \x01(\tH\x04R\awikiUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_end_dateB\v\n" +
	"\t_info_urlB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_wiki_url\"1\n" +
	"\vProgramType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"w\n" +
	"\vSocialMedia\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x04logo\x18\x02 \x01(\v2\x11.payload.v1.ImageR\x04logo\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x03url\x18\x04 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"|\n" +
	"\x0fSocialMediaLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12:\n" +
	"\fsocial_media\x18\x02 \x01(\v2\x17.payload.v1.SocialMediaR\vsocialMedia\x12\x15\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x88\x01\x01B\x06\n" +
	"\x04_url\"o\n" +
	"\x13ListPayloadsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x8b\x01\n" +
	"\x14ListPayloadsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12-\n" +
	"\aresults\x18\x04 \x03(\v2\x13.payload.v1.PayloadR\aresults\"7\n" +
	"\x11GetPayloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"C\n" +
	"\x12GetPayloadResponse\x12-\n" +
	"\apayload\x18\x01 \x01(\v2\x13.payload.v1.PayloadR\apayload2\xb0\x01\n" +
	"\x0ePayloadService\x12Q\n" +
	"\fListPayloads\x12\x1f.payload.v1.ListPayloadsRequest\x1a .payload.v1.ListPayloadsResponse\x12K\n" +
	"\n" +
	"GetPayload\x12\x1d.payload.v1.GetPayloadRequest\x1a\x1e.payload.v1.GetPayloadResponseB8Z6github.com/pobochiigo/bhole/proto/payload/v1;payloadv1b\x06proto3"

var (
	file_payload_v1_payload_proto_rawDescOnce sync.Once
	file_payload_v1_payload_proto_rawDescData []byte
)

func file_payload_v1_payload_proto_rawDescGZIP() []byte {
	file_payload_v1_payload_proto_rawDescOnce.Do(func() {
		file_payload_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_v1_payload_proto_rawDesc), len(file_payload_v1_payload_proto_rawDesc)))
	})
	return file_payload_v1_payload_proto_rawDescData
}

var file_payload_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_payload_v1_payload_proto_goTypes = []any{
	(*AgencyDetailed)(nil),       // 0: payload.v1.AgencyDetailed
	(*AgencyMini)(nil),           // 1: payload.v1.AgencyMini
	(*AgencyType)(nil),           // 2: payload.v1.AgencyType
	(*Country)(nil),              // 3: payload.v1.Country
	(*Image)(nil),                // 4: payload.v1.Image
	(*ImageLicense)(nil),         // 5: payload.v1.ImageLicense
	(*ImageVariant)(nil),         // 6: payload.v1.ImageVariant
	(*ImageVariantType)(nil),     // 7: payload.v1.ImageVariantType
	(*MissionPatch)(nil),         // 8: payload.v1.MissionPatch
	(*Payload)(nil),              // 9: payload.v1.Payload
	(*PayloadType)(nil),          // 10: payload.v1.PayloadType
	(*ProgramNormal)(nil),        // 11: payload.v1.ProgramNormal
	(*ProgramType)(nil),          // 12: payload.v1.ProgramType
	(*SocialMedia)(nil),          // 13: payload.v1.SocialMedia
	(*SocialMediaLink)(nil),      // 14: payload.v1.SocialMediaLink
	(*ListPayloadsRequest)(nil),  // 15: payload.v1.ListPayloadsRequest
	(*ListPayloadsResponse)(nil), // 16: payload.v1.ListPayloadsResponse
	(*GetPayloadRequest)(nil),    // 17: payload.v1.GetPayloadRequest
	(*GetPayloadResponse)(nil),   // 18: payload.v1.GetPayloadResponse
}
var file_payload_v1_payload_proto_depIdxs = []int32{
	3,  // 0: payload.v1.AgencyDetailed.country:type_name -> payload.v1.Country
	4,  // 1: payload.v1.AgencyDetailed.image:type_name -> payload.v1.Image
	4,  // 2: payload.v1.AgencyDetailed.logo:type_name -> payload.v1.Image
	4,  // 3: payload.v1.AgencyDetailed.social_logo:type_name -> payload.v1.Image
	14, // 4: payload.v1.AgencyDetailed.social_media_links:type_name -> payload.v1.SocialMediaLink
	2,  // 5: payload.v1.AgencyDetailed.type:type_name -> payload.v1.AgencyType
	2,  // 6: payload.v1.AgencyMini.type:type_name -> payload.v1.AgencyType
	5,  // 7: payload.v1.Image.license:type_name -> payload.v1.ImageLicense
	6,  // 8: payload.v1.Image.variants:type_name -> payload.v1.ImageVariant
	7,  // 9: payload.v1.ImageVariant.type:type_name -> payload.v1.ImageVariantType
	1,  // 10: payload.v1.MissionPatch.agency:type_name -> payload.v1.AgencyMini
	4,  // 11: payload.v1.Payload.image:type_name -> payload.v1.Image
	0,  // 12: payload.v1.Payload.manufacturer:type_name -> payload.v1.AgencyDetailed
	0,  // 13: payload.v1.Payload.operator:type_name -> payload.v1.AgencyDetailed
	11, // 14: payload.v1.Payload.program:type_name -> payload.v1.ProgramNormal
	10, // 15: payload.v1.Payload.type:type_name -> payload.v1.PayloadType
	1,  // 16: payload.v1.ProgramNormal.agencies:type_name -> payload.v1.AgencyMini
	4,  // 17: payload.v1.ProgramNormal.image:type_name -> payload.v1.Image
	8,  // 18: payload.v1.ProgramNormal.mission_patches:type_name -> payload.v1.MissionPatch
	12, // 19: payload.v1.ProgramNormal.type:type_name -> payload.v1.ProgramType
	4,  // 20: payload.v1.SocialMedia.logo:type_name -> payload.v1.Image
	13, // 21: payload.v1.SocialMediaLink.social_media:type_name -> payload.v1.SocialMedia
	9,  // 22: payload.v1.ListPayloadsResponse.results:type_name -> payload.v1.Payload
	9,  // 23: payload.v1.GetPayloadResponse.payload:type_name -> payload.v1.Payload
	15, // 24: payload.v1.PayloadService.ListPayloads:input_type -> payload.v1.ListPayloadsRequest
	17, // 25: payload.v1.PayloadService.GetPayload:input_type -> payload.v1.GetPayloadRequest
	16, // 26: payload.v1.PayloadService.ListPayloads:output_type -> payload.v1.ListPayloadsResponse
	18, // 27: payload.v1.PayloadService.GetPayload:output_type -> payload.v1.GetPayloadResponse
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_payload_v1_payload_proto_init() }
func file_payload_v1_payload_proto_init() {
	if File_payload_v1_payload_proto != nil {
		return
	}
	file_payload_v1_payload_proto_msgTypes[0].OneofWrappers = []any{}
	file_payload_v1_payload_proto_msgTypes[4].OneofWrappers = []any{}
	file_payload_v1_payload_proto_msgTypes[5].OneofWrappers = []any{}
	file_payload_v1_payload_proto_msgTypes[9].OneofWrappers = []any{}
	file_payload_v1_payload_proto_msgTypes[11].OneofWrappers = []any{}
	file_payload_v1_payload_proto_msgTypes[13].OneofWrappers = []any{}
	file_payload_v1_payload_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_v1_payload_proto_rawDesc), len(file_payload_v1_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payload_v1_payload_proto_goTypes,
		DependencyIndexes: file_payload_v1_payload_proto_depIdxs,
		MessageInfos:      file_payload_v1_payload_proto_msgTypes,
	}.Build()
	File_payload_v1_payload_proto = out.File
	file_payload_v1_payload_proto_goTypes = nil
	file_payload_v1_payload_proto_depIdxs = nil
}
