import os
import shutil
import subprocess

# Mapping of the 18 primary LL2 API resources
RESOURCES = {
    "agency": {"plural_method": "ListAgencies", "singular": "Agency"},
    "astronaut": {"plural_method": "ListAstronauts", "singular": "Astronaut"},
    "celestial_body": {"plural_method": "ListCelestialBodies", "singular": "CelestialBody"},
    "docking_event": {"plural_method": "ListDockingEvents", "singular": "DockingEvent"},
    "event": {"plural_method": "ListEvents", "singular": "Event"},
    "expedition": {"plural_method": "ListExpeditions", "singular": "Expedition"},
    "landing": {"plural_method": "ListLandings", "singular": "Landing"},
    "launcher": {"plural_method": "ListLaunchers", "singular": "Launcher"},
    "launcher_configuration": {"plural_method": "ListLauncherConfigurations", "singular": "LauncherConfiguration"},
    "launch": {"plural_method": "ListLaunches", "singular": "Launch"},
    "location": {"plural_method": "ListLocations", "singular": "Location"},
    "pad": {"plural_method": "ListPads", "singular": "Pad"},
    "payload": {"plural_method": "ListPayloads", "singular": "Payload"},
    "program": {"plural_method": "ListPrograms", "singular": "Program"},
    "space_station": {"plural_method": "ListSpaceStations", "singular": "SpaceStation"},
    "spacecraft": {"plural_method": "ListSpacecrafts", "singular": "Spacecraft"},
    "spacewalk": {"plural_method": "ListSpacewalks", "singular": "Spacewalk"},
    "update": {"plural_method": "ListUpdates", "singular": "Update"}
}


def camel_case(s):
    return "".join(x.capitalize() for x in s.split("_"))


def run_gofmt(paths):
    """Format generated Go files so the tree is gofmt-clean without a manual pass."""
    if shutil.which("gofmt") is None:
        print("warning: gofmt not found in PATH; generated Go files were not formatted")
        return
    subprocess.run(["gofmt", "-w", *paths], check=True)


def main():
    print("Generating cmd/server/main.go...")
    os.makedirs("cmd/server", exist_ok=True)

    std_imports = [
        '"context"',
        '"errors"',
        '"log"',
        '"net/http"',
        '"os"',
        '"os/signal"',
        '"syscall"',
        '"time"',
    ]
    project_imports = ['"github.com/pobochiigo/bhole/client/transport"']
    for feature in sorted(RESOURCES.keys()):
        feature_camel = camel_case(feature)
        project_imports.append(f'{feature}client "github.com/pobochiigo/bhole/client/{feature}"')
        project_imports.append(f'{feature} "github.com/pobochiigo/bhole/{feature}"')
        project_imports.append(f'{feature}v1connect "github.com/pobochiigo/bhole/proto/{feature}/v1/{feature}v1connect"')

    nl = "\n\t"
    main_content = f"""// Code generated by scripts/generate_server_cmd.py. DO NOT EDIT.

// Command server is a ConnectRPC gateway in front of the LaunchLibrary v2 REST
// API. Every service handler is backed by the REST-mapping client, so browser
// and gRPC-style callers get real LL2 data without a separate backend.
//
// Configuration (environment variables):
//
//	LL2_BASE_URL  upstream REST base URL (default https://lldev.thespacedevs.com)
//	BHOLE_ADDR    listen address (default :8080)
package main

import (
	{nl.join(std_imports)}

	{nl.join(project_imports)}
)

const (
	defaultBaseURL  = "https://lldev.thespacedevs.com"
	defaultAddr     = ":8080"
	upstreamTimeout = 30 * time.Second
	shutdownTimeout = 10 * time.Second
)

// corsMiddleware allows browser-based Connect-Web clients on any origin.
func corsMiddleware(next http.Handler) http.Handler {{
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {{
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, Authorization, Connect-Protocol-Version, Connect-Timeout-Ms")

		if r.Method == http.MethodOptions {{
			w.WriteHeader(http.StatusNoContent)
			return
		}}

		next.ServeHTTP(w, r)
	}})
}}

func envOr(key, fallback string) string {{
	if v := os.Getenv(key); v != "" {{
		return v
	}}
	return fallback
}}

// newMux registers every ConnectRPC service, each backed by the REST client.
func newMux(restClient *transport.RESTClient, baseURL string) *http.ServeMux {{
	mux := http.NewServeMux()
"""

    for feature, config in sorted(RESOURCES.items()):
        feature_camel = camel_case(feature)
        main_content += (
            f"\tmux.Handle({feature}v1connect.New{feature_camel}ServiceHandler("
            f"{feature}.New{feature_camel}Handler({feature}client.New{feature_camel}Client(restClient, baseURL))))\n"
        )

    main_content += """	return mux
}

func main() {
	baseURL := envOr("LL2_BASE_URL", defaultBaseURL)
	addr := envOr("BHOLE_ADDR", defaultAddr)

	restClient := transport.NewRESTClient(baseURL, &http.Client{Timeout: upstreamTimeout})

	srv := &http.Server{
		Addr:              addr,
		Handler:           corsMiddleware(newMux(restClient, baseURL)),
		ReadHeaderTimeout: 10 * time.Second,
	}
	// Serve HTTP/1.1 and cleartext HTTP/2 (h2c) so both Connect-Web and gRPC clients work.
	srv.Protocols = new(http.Protocols)
	srv.Protocols.SetHTTP1(true)
	srv.Protocols.SetUnencryptedHTTP2(true)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	errCh := make(chan error, 1)
	go func() {
		errCh <- srv.ListenAndServe()
	}()
	log.Printf("bhole gateway listening on %s, proxying to %s", addr, baseURL)

	select {
	case err := <-errCh:
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server failed: %v", err)
		}
	case <-ctx.Done():
		stop()
		log.Println("shutting down...")
		shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
		defer cancel()
		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("graceful shutdown failed: %v", err)
		}
	}
}
"""

    with open("cmd/server/main.go", "w") as f:
        f.write(main_content)

    run_gofmt(["cmd/server"])
    print("cmd/server/main.go generated successfully!")


if __name__ == "__main__":
    main()
