// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: program/v1/program.proto

package programv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgencyMini struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abbrev        string                 `protobuf:"bytes,1,opt,name=abbrev,proto3" json:"abbrev,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,4,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	Type          *AgencyType            `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyMini) Reset() {
	*x = AgencyMini{}
	mi := &file_program_v1_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyMini) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyMini) ProtoMessage() {}

func (x *AgencyMini) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyMini.ProtoReflect.Descriptor instead.
func (*AgencyMini) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{0}
}

func (x *AgencyMini) GetAbbrev() string {
	if x != nil {
		return x.Abbrev
	}
	return ""
}

func (x *AgencyMini) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyMini) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgencyMini) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *AgencyMini) GetType() *AgencyType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *AgencyMini) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AgencyType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgencyType) Reset() {
	*x = AgencyType{}
	mi := &file_program_v1_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgencyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgencyType) ProtoMessage() {}

func (x *AgencyType) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgencyType.ProtoReflect.Descriptor instead.
func (*AgencyType) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{1}
}

func (x *AgencyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgencyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credit        *string                `protobuf:"bytes,1,opt,name=credit,proto3,oneof" json:"credit,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	License       *ImageLicense          `protobuf:"bytes,4,opt,name=license,proto3" json:"license,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SingleUse     bool                   `protobuf:"varint,6,opt,name=single_use,json=singleUse,proto3" json:"single_use,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Variants      []*ImageVariant        `protobuf:"bytes,8,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_program_v1_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{2}
}

func (x *Image) GetCredit() string {
	if x != nil && x.Credit != nil {
		return *x.Credit
	}
	return ""
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Image) GetLicense() *ImageLicense {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetSingleUse() bool {
	if x != nil {
		return x.SingleUse
	}
	return false
}

func (x *Image) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Image) GetVariants() []*ImageVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type ImageLicense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          *string                `protobuf:"bytes,2,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageLicense) Reset() {
	*x = ImageLicense{}
	mi := &file_program_v1_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageLicense) ProtoMessage() {}

func (x *ImageLicense) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageLicense.ProtoReflect.Descriptor instead.
func (*ImageLicense) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{3}
}

func (x *ImageLicense) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageLicense) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *ImageLicense) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageLicense) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type          *ImageVariantType      `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariant) Reset() {
	*x = ImageVariant{}
	mi := &file_program_v1_program_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariant) ProtoMessage() {}

func (x *ImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariant.ProtoReflect.Descriptor instead.
func (*ImageVariant) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{4}
}

func (x *ImageVariant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariant) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageVariant) GetType() *ImageVariantType {
	if x != nil {
		return x.Type
	}
	return nil
}

type ImageVariantType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariantType) Reset() {
	*x = ImageVariantType{}
	mi := &file_program_v1_program_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariantType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariantType) ProtoMessage() {}

func (x *ImageVariantType) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariantType.ProtoReflect.Descriptor instead.
func (*ImageVariantType) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{5}
}

func (x *ImageVariantType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageVariantType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MissionPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agency        *AgencyMini            `protobuf:"bytes,1,opt,name=agency,proto3" json:"agency,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ResponseMode  string                 `protobuf:"bytes,6,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionPatch) Reset() {
	*x = MissionPatch{}
	mi := &file_program_v1_program_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionPatch) ProtoMessage() {}

func (x *MissionPatch) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionPatch.ProtoReflect.Descriptor instead.
func (*MissionPatch) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{6}
}

func (x *MissionPatch) GetAgency() *AgencyMini {
	if x != nil {
		return x.Agency
	}
	return nil
}

func (x *MissionPatch) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MissionPatch) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MissionPatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MissionPatch) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MissionPatch) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

type Program struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Agencies       []*AgencyMini          `protobuf:"bytes,1,rep,name=agencies,proto3" json:"agencies,omitempty"`
	Description    *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	EndDate        *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Id             int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	Image          *Image                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	InfoUrl        *string                `protobuf:"bytes,6,opt,name=info_url,json=infoUrl,proto3,oneof" json:"info_url,omitempty"`
	MissionPatches []*MissionPatch        `protobuf:"bytes,7,rep,name=mission_patches,json=missionPatches,proto3" json:"mission_patches,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	ResponseMode   string                 `protobuf:"bytes,9,opt,name=response_mode,json=responseMode,proto3" json:"response_mode,omitempty"`
	StartDate      *string                `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	Type           *ProgramType           `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Url            string                 `protobuf:"bytes,12,opt,name=url,proto3" json:"url,omitempty"`
	WikiUrl        *string                `protobuf:"bytes,13,opt,name=wiki_url,json=wikiUrl,proto3,oneof" json:"wiki_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_program_v1_program_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{7}
}

func (x *Program) GetAgencies() []*AgencyMini {
	if x != nil {
		return x.Agencies
	}
	return nil
}

func (x *Program) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Program) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *Program) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Program) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Program) GetInfoUrl() string {
	if x != nil && x.InfoUrl != nil {
		return *x.InfoUrl
	}
	return ""
}

func (x *Program) GetMissionPatches() []*MissionPatch {
	if x != nil {
		return x.MissionPatches
	}
	return nil
}

func (x *Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Program) GetResponseMode() string {
	if x != nil {
		return x.ResponseMode
	}
	return ""
}

func (x *Program) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *Program) GetType() *ProgramType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Program) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Program) GetWikiUrl() string {
	if x != nil && x.WikiUrl != nil {
		return *x.WikiUrl
	}
	return ""
}

type ProgramType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramType) Reset() {
	*x = ProgramType{}
	mi := &file_program_v1_program_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramType) ProtoMessage() {}

func (x *ProgramType) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramType.ProtoReflect.Descriptor instead.
func (*ProgramType) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{8}
}

func (x *ProgramType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProgramsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgramsRequest) Reset() {
	*x = ListProgramsRequest{}
	mi := &file_program_v1_program_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgramsRequest) ProtoMessage() {}

func (x *ListProgramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgramsRequest.ProtoReflect.Descriptor instead.
func (*ListProgramsRequest) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{9}
}

func (x *ListProgramsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProgramsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProgramsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListProgramsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListProgramsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Previous      string                 `protobuf:"bytes,3,opt,name=previous,proto3" json:"previous,omitempty"`
	Results       []*Program             `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgramsResponse) Reset() {
	*x = ListProgramsResponse{}
	mi := &file_program_v1_program_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgramsResponse) ProtoMessage() {}

func (x *ListProgramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgramsResponse.ProtoReflect.Descriptor instead.
func (*ListProgramsResponse) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{10}
}

func (x *ListProgramsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListProgramsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *ListProgramsResponse) GetPrevious() string {
	if x != nil {
		return x.Previous
	}
	return ""
}

func (x *ListProgramsResponse) GetResults() []*Program {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetProgramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramRequest) Reset() {
	*x = GetProgramRequest{}
	mi := &file_program_v1_program_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramRequest) ProtoMessage() {}

func (x *GetProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramRequest.ProtoReflect.Descriptor instead.
func (*GetProgramRequest) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{11}
}

func (x *GetProgramRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProgramRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetProgramResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       *Program               `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramResponse) Reset() {
	*x = GetProgramResponse{}
	mi := &file_program_v1_program_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramResponse) ProtoMessage() {}

func (x *GetProgramResponse) ProtoReflect() protoreflect.Message {
	mi := &file_program_v1_program_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramResponse.ProtoReflect.Descriptor instead.
func (*GetProgramResponse) Descriptor() ([]byte, []int) {
	return file_program_v1_program_proto_rawDescGZIP(), []int{12}
}

func (x *GetProgramResponse) GetProgram() *Program {
	if x != nil {
		return x.Program
	}
	return nil
}

var File_program_v1_program_proto protoreflect.FileDescriptor

const file_program_v1_program_proto_rawDesc = "" +
	"\n" +
	"\x18program/v1/program.proto\x12\n" +
	"program.v1\"\xab\x01\n" +
	"\n" +
	"AgencyMini\x12\x16\n" +
	"\x06abbrev\x18\x01 \x01(\tR\x06abbrev\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\x04 \x01(\tR\fresponseMode\x12*\n" +
	"\x04type\x18\x05 \x01(\v2\x16.program.v1.AgencyTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\"0\n" +
	"\n" +
	"AgencyType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9e\x02\n" +
	"\x05Image\x12\x1b\n" +
	"\x06credit\x18\x01 \x01(\tH\x00R\x06credit\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x122\n" +
	"\alicense\x18\x04 \x01(\v2\x18.program.v1.ImageLicenseR\alicense\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"single_use\x18\x06 \x01(\bR\tsingleUse\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x124\n" +
	"\bvariants\x18\b \x03(\v2\x18.program.v1.ImageVariantR\bvariantsB\t\n" +
	"\a_credit\"p\n" +
	"\fImageLicense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04link\x18\x02 \x01(\tH\x00R\x04link\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriorityB\a\n" +
	"\x05_link\"m\n" +
	"\fImageVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x120\n" +
	"\x04type\x18\x03 \x01(\v2\x1c.program.v1.ImageVariantTypeR\x04type\"6\n" +
	"\x10ImageVariantType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc0\x01\n" +
	"\fMissionPatch\x12.\n" +
	"\x06agency\x18\x01 \x01(\v2\x16.program.v1.AgencyMiniR\x06agency\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12#\n" +
	"\rresponse_mode\x18\x06 \x01(\tR\fresponseMode\"\xa2\x04\n" +
	"\aProgram\x122\n" +
	"\bagencies\x18\x01 \x03(\v2\x16.program.v1.AgencyMiniR\bagencies\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\tH\x01R\aendDate\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02id\x12'\n" +
	"\x05image\x18\x05 \x01(\v2\x11.program.v1.ImageR\x05image\x12\x1e\n" +
	"\binfo_url\x18\x06 \x01(\tH\x02R\ainfoUrl\x88\x01\x01\x12A\n" +
	"\x0fmission_patches\x18\a \x03(\v2\x18.program.v1.MissionPatchR\x0emissionPatches\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12#\n" +
	"\rresponse_mode\x18\t \x01(\tR\fresponseMode\x12\"\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\tH\x03R\tstartDate\x88\x01\x01\x12+\n" +
	"\x04type\x18\v \x01(\v2\x17.program.v1.ProgramTypeR\x04type\x12\x10\n" +
	"\x03url\x18\f \x01(\tR\x03url\x12\x1e\n" +
	"\bwiki_url\x18\r \x01(\tH\x04R\awikiUrl\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_end_dateB\v\n" +
	"\t_info_urlB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_wiki_url\"1\n" +
	"\vProgramType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"o\n" +
	"\x13ListProgramsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\x8b\x01\n" +
	"\x14ListProgramsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x1a\n" +
	"\bprevious\x18\x03 \x01(\tR\bprevious\x12-\n" +
	"\aresults\x18\x04 \x03(\v2\x13.program.v1.ProgramR\aresults\"7\n" +
	"\x11GetProgramRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"C\n" +
	"\x12GetProgramResponse\x12-\n" +
	"\aprogram\x18\x01 \x01(\v2\x13.program.v1.ProgramR\aprogram2\xb0\x01\n" +
	"\x0eProgramService\x12Q\n" +
	"\fListPrograms\x12\x1f.program.v1.ListProgramsRequest\x1a .program.v1.ListProgramsResponse\x12K\n" +
	"\n" +
	"GetProgram\x12\x1d.program.v1.GetProgramRequest\x1a\x1e.program.v1.GetProgramResponseB8Z6com.gitlab/pobochiigo/bhole/proto/program/v1;programv1b\x06proto3"

var (
	file_program_v1_program_proto_rawDescOnce sync.Once
	file_program_v1_program_proto_rawDescData []byte
)

func file_program_v1_program_proto_rawDescGZIP() []byte {
	file_program_v1_program_proto_rawDescOnce.Do(func() {
		file_program_v1_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_program_v1_program_proto_rawDesc), len(file_program_v1_program_proto_rawDesc)))
	})
	return file_program_v1_program_proto_rawDescData
}

var file_program_v1_program_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_program_v1_program_proto_goTypes = []any{
	(*AgencyMini)(nil),           // 0: program.v1.AgencyMini
	(*AgencyType)(nil),           // 1: program.v1.AgencyType
	(*Image)(nil),                // 2: program.v1.Image
	(*ImageLicense)(nil),         // 3: program.v1.ImageLicense
	(*ImageVariant)(nil),         // 4: program.v1.ImageVariant
	(*ImageVariantType)(nil),     // 5: program.v1.ImageVariantType
	(*MissionPatch)(nil),         // 6: program.v1.MissionPatch
	(*Program)(nil),              // 7: program.v1.Program
	(*ProgramType)(nil),          // 8: program.v1.ProgramType
	(*ListProgramsRequest)(nil),  // 9: program.v1.ListProgramsRequest
	(*ListProgramsResponse)(nil), // 10: program.v1.ListProgramsResponse
	(*GetProgramRequest)(nil),    // 11: program.v1.GetProgramRequest
	(*GetProgramResponse)(nil),   // 12: program.v1.GetProgramResponse
}
var file_program_v1_program_proto_depIdxs = []int32{
	1,  // 0: program.v1.AgencyMini.type:type_name -> program.v1.AgencyType
	3,  // 1: program.v1.Image.license:type_name -> program.v1.ImageLicense
	4,  // 2: program.v1.Image.variants:type_name -> program.v1.ImageVariant
	5,  // 3: program.v1.ImageVariant.type:type_name -> program.v1.ImageVariantType
	0,  // 4: program.v1.MissionPatch.agency:type_name -> program.v1.AgencyMini
	0,  // 5: program.v1.Program.agencies:type_name -> program.v1.AgencyMini
	2,  // 6: program.v1.Program.image:type_name -> program.v1.Image
	6,  // 7: program.v1.Program.mission_patches:type_name -> program.v1.MissionPatch
	8,  // 8: program.v1.Program.type:type_name -> program.v1.ProgramType
	7,  // 9: program.v1.ListProgramsResponse.results:type_name -> program.v1.Program
	7,  // 10: program.v1.GetProgramResponse.program:type_name -> program.v1.Program
	9,  // 11: program.v1.ProgramService.ListPrograms:input_type -> program.v1.ListProgramsRequest
	11, // 12: program.v1.ProgramService.GetProgram:input_type -> program.v1.GetProgramRequest
	10, // 13: program.v1.ProgramService.ListPrograms:output_type -> program.v1.ListProgramsResponse
	12, // 14: program.v1.ProgramService.GetProgram:output_type -> program.v1.GetProgramResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_program_v1_program_proto_init() }
func file_program_v1_program_proto_init() {
	if File_program_v1_program_proto != nil {
		return
	}
	file_program_v1_program_proto_msgTypes[2].OneofWrappers = []any{}
	file_program_v1_program_proto_msgTypes[3].OneofWrappers = []any{}
	file_program_v1_program_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_program_v1_program_proto_rawDesc), len(file_program_v1_program_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_program_v1_program_proto_goTypes,
		DependencyIndexes: file_program_v1_program_proto_depIdxs,
		MessageInfos:      file_program_v1_program_proto_msgTypes,
	}.Build()
	File_program_v1_program_proto = out.File
	file_program_v1_program_proto_goTypes = nil
	file_program_v1_program_proto_depIdxs = nil
}
