// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: launcher/v1/launcher.proto

package launcherv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pobochiigo/bhole/proto/launcher/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LauncherServiceName is the fully-qualified name of the LauncherService service.
	LauncherServiceName = "launcher.v1.LauncherService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LauncherServiceListLaunchersProcedure is the fully-qualified name of the LauncherService's
	// ListLaunchers RPC.
	LauncherServiceListLaunchersProcedure = "/launcher.v1.LauncherService/ListLaunchers"
	// LauncherServiceGetLauncherProcedure is the fully-qualified name of the LauncherService's
	// GetLauncher RPC.
	LauncherServiceGetLauncherProcedure = "/launcher.v1.LauncherService/GetLauncher"
)

// LauncherServiceClient is a client for the launcher.v1.LauncherService service.
type LauncherServiceClient interface {
	ListLaunchers(context.Context, *connect.Request[v1.ListLaunchersRequest]) (*connect.Response[v1.ListLaunchersResponse], error)
	GetLauncher(context.Context, *connect.Request[v1.GetLauncherRequest]) (*connect.Response[v1.GetLauncherResponse], error)
}

// NewLauncherServiceClient constructs a client for the launcher.v1.LauncherService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLauncherServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LauncherServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	launcherServiceMethods := v1.File_launcher_v1_launcher_proto.Services().ByName("LauncherService").Methods()
	return &launcherServiceClient{
		listLaunchers: connect.NewClient[v1.ListLaunchersRequest, v1.ListLaunchersResponse](
			httpClient,
			baseURL+LauncherServiceListLaunchersProcedure,
			connect.WithSchema(launcherServiceMethods.ByName("ListLaunchers")),
			connect.WithClientOptions(opts...),
		),
		getLauncher: connect.NewClient[v1.GetLauncherRequest, v1.GetLauncherResponse](
			httpClient,
			baseURL+LauncherServiceGetLauncherProcedure,
			connect.WithSchema(launcherServiceMethods.ByName("GetLauncher")),
			connect.WithClientOptions(opts...),
		),
	}
}

// launcherServiceClient implements LauncherServiceClient.
type launcherServiceClient struct {
	listLaunchers *connect.Client[v1.ListLaunchersRequest, v1.ListLaunchersResponse]
	getLauncher   *connect.Client[v1.GetLauncherRequest, v1.GetLauncherResponse]
}

// ListLaunchers calls launcher.v1.LauncherService.ListLaunchers.
func (c *launcherServiceClient) ListLaunchers(ctx context.Context, req *connect.Request[v1.ListLaunchersRequest]) (*connect.Response[v1.ListLaunchersResponse], error) {
	return c.listLaunchers.CallUnary(ctx, req)
}

// GetLauncher calls launcher.v1.LauncherService.GetLauncher.
func (c *launcherServiceClient) GetLauncher(ctx context.Context, req *connect.Request[v1.GetLauncherRequest]) (*connect.Response[v1.GetLauncherResponse], error) {
	return c.getLauncher.CallUnary(ctx, req)
}

// LauncherServiceHandler is an implementation of the launcher.v1.LauncherService service.
type LauncherServiceHandler interface {
	ListLaunchers(context.Context, *connect.Request[v1.ListLaunchersRequest]) (*connect.Response[v1.ListLaunchersResponse], error)
	GetLauncher(context.Context, *connect.Request[v1.GetLauncherRequest]) (*connect.Response[v1.GetLauncherResponse], error)
}

// NewLauncherServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLauncherServiceHandler(svc LauncherServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	launcherServiceMethods := v1.File_launcher_v1_launcher_proto.Services().ByName("LauncherService").Methods()
	launcherServiceListLaunchersHandler := connect.NewUnaryHandler(
		LauncherServiceListLaunchersProcedure,
		svc.ListLaunchers,
		connect.WithSchema(launcherServiceMethods.ByName("ListLaunchers")),
		connect.WithHandlerOptions(opts...),
	)
	launcherServiceGetLauncherHandler := connect.NewUnaryHandler(
		LauncherServiceGetLauncherProcedure,
		svc.GetLauncher,
		connect.WithSchema(launcherServiceMethods.ByName("GetLauncher")),
		connect.WithHandlerOptions(opts...),
	)
	return "/launcher.v1.LauncherService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LauncherServiceListLaunchersProcedure:
			launcherServiceListLaunchersHandler.ServeHTTP(w, r)
		case LauncherServiceGetLauncherProcedure:
			launcherServiceGetLauncherHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLauncherServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLauncherServiceHandler struct{}

func (UnimplementedLauncherServiceHandler) ListLaunchers(context.Context, *connect.Request[v1.ListLaunchersRequest]) (*connect.Response[v1.ListLaunchersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("launcher.v1.LauncherService.ListLaunchers is not implemented"))
}

func (UnimplementedLauncherServiceHandler) GetLauncher(context.Context, *connect.Request[v1.GetLauncherRequest]) (*connect.Response[v1.GetLauncherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("launcher.v1.LauncherService.GetLauncher is not implemented"))
}
