// Code generated by scripts/generate_server_cmd.py. DO NOT EDIT.

// Command server is a ConnectRPC gateway in front of the LaunchLibrary v2 REST
// API. Every service handler is backed by the REST-mapping client, so browser
// and gRPC-style callers get real LL2 data without a separate backend.
//
// Configuration (environment variables):
//
//	LL2_BASE_URL  upstream REST base URL (default https://lldev.thespacedevs.com)
//	BHOLE_ADDR    listen address (default :8080)
package main

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	agency "github.com/pobochiigo/bhole/agency"
	astronaut "github.com/pobochiigo/bhole/astronaut"
	celestial_body "github.com/pobochiigo/bhole/celestial_body"
	agencyclient "github.com/pobochiigo/bhole/client/agency"
	astronautclient "github.com/pobochiigo/bhole/client/astronaut"
	celestial_bodyclient "github.com/pobochiigo/bhole/client/celestial_body"
	docking_eventclient "github.com/pobochiigo/bhole/client/docking_event"
	eventclient "github.com/pobochiigo/bhole/client/event"
	expeditionclient "github.com/pobochiigo/bhole/client/expedition"
	landingclient "github.com/pobochiigo/bhole/client/landing"
	launchclient "github.com/pobochiigo/bhole/client/launch"
	launcherclient "github.com/pobochiigo/bhole/client/launcher"
	launcher_configurationclient "github.com/pobochiigo/bhole/client/launcher_configuration"
	locationclient "github.com/pobochiigo/bhole/client/location"
	padclient "github.com/pobochiigo/bhole/client/pad"
	payloadclient "github.com/pobochiigo/bhole/client/payload"
	programclient "github.com/pobochiigo/bhole/client/program"
	space_stationclient "github.com/pobochiigo/bhole/client/space_station"
	spacecraftclient "github.com/pobochiigo/bhole/client/spacecraft"
	spacewalkclient "github.com/pobochiigo/bhole/client/spacewalk"
	"github.com/pobochiigo/bhole/client/transport"
	updateclient "github.com/pobochiigo/bhole/client/update"
	docking_event "github.com/pobochiigo/bhole/docking_event"
	event "github.com/pobochiigo/bhole/event"
	expedition "github.com/pobochiigo/bhole/expedition"
	landing "github.com/pobochiigo/bhole/landing"
	launch "github.com/pobochiigo/bhole/launch"
	launcher "github.com/pobochiigo/bhole/launcher"
	launcher_configuration "github.com/pobochiigo/bhole/launcher_configuration"
	location "github.com/pobochiigo/bhole/location"
	pad "github.com/pobochiigo/bhole/pad"
	payload "github.com/pobochiigo/bhole/payload"
	program "github.com/pobochiigo/bhole/program"
	agencyv1connect "github.com/pobochiigo/bhole/proto/agency/v1/agencyv1connect"
	astronautv1connect "github.com/pobochiigo/bhole/proto/astronaut/v1/astronautv1connect"
	celestial_bodyv1connect "github.com/pobochiigo/bhole/proto/celestial_body/v1/celestial_bodyv1connect"
	docking_eventv1connect "github.com/pobochiigo/bhole/proto/docking_event/v1/docking_eventv1connect"
	eventv1connect "github.com/pobochiigo/bhole/proto/event/v1/eventv1connect"
	expeditionv1connect "github.com/pobochiigo/bhole/proto/expedition/v1/expeditionv1connect"
	landingv1connect "github.com/pobochiigo/bhole/proto/landing/v1/landingv1connect"
	launchv1connect "github.com/pobochiigo/bhole/proto/launch/v1/launchv1connect"
	launcherv1connect "github.com/pobochiigo/bhole/proto/launcher/v1/launcherv1connect"
	launcher_configurationv1connect "github.com/pobochiigo/bhole/proto/launcher_configuration/v1/launcher_configurationv1connect"
	locationv1connect "github.com/pobochiigo/bhole/proto/location/v1/locationv1connect"
	padv1connect "github.com/pobochiigo/bhole/proto/pad/v1/padv1connect"
	payloadv1connect "github.com/pobochiigo/bhole/proto/payload/v1/payloadv1connect"
	programv1connect "github.com/pobochiigo/bhole/proto/program/v1/programv1connect"
	space_stationv1connect "github.com/pobochiigo/bhole/proto/space_station/v1/space_stationv1connect"
	spacecraftv1connect "github.com/pobochiigo/bhole/proto/spacecraft/v1/spacecraftv1connect"
	spacewalkv1connect "github.com/pobochiigo/bhole/proto/spacewalk/v1/spacewalkv1connect"
	updatev1connect "github.com/pobochiigo/bhole/proto/update/v1/updatev1connect"
	space_station "github.com/pobochiigo/bhole/space_station"
	spacecraft "github.com/pobochiigo/bhole/spacecraft"
	spacewalk "github.com/pobochiigo/bhole/spacewalk"
	update "github.com/pobochiigo/bhole/update"
)

const (
	defaultBaseURL  = "https://lldev.thespacedevs.com"
	defaultAddr     = ":8080"
	upstreamTimeout = 30 * time.Second
	shutdownTimeout = 10 * time.Second
)

// corsMiddleware allows browser-based Connect-Web clients on any origin.
func corsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, Authorization, Connect-Protocol-Version, Connect-Timeout-Ms")

		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}

		next.ServeHTTP(w, r)
	})
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// newMux registers every ConnectRPC service, each backed by the REST client.
func newMux(restClient *transport.RESTClient, baseURL string) *http.ServeMux {
	mux := http.NewServeMux()
	mux.Handle(agencyv1connect.NewAgencyServiceHandler(agency.NewAgencyHandler(agencyclient.NewAgencyClient(restClient, baseURL))))
	mux.Handle(astronautv1connect.NewAstronautServiceHandler(astronaut.NewAstronautHandler(astronautclient.NewAstronautClient(restClient, baseURL))))
	mux.Handle(celestial_bodyv1connect.NewCelestialBodyServiceHandler(celestial_body.NewCelestialBodyHandler(celestial_bodyclient.NewCelestialBodyClient(restClient, baseURL))))
	mux.Handle(docking_eventv1connect.NewDockingEventServiceHandler(docking_event.NewDockingEventHandler(docking_eventclient.NewDockingEventClient(restClient, baseURL))))
	mux.Handle(eventv1connect.NewEventServiceHandler(event.NewEventHandler(eventclient.NewEventClient(restClient, baseURL))))
	mux.Handle(expeditionv1connect.NewExpeditionServiceHandler(expedition.NewExpeditionHandler(expeditionclient.NewExpeditionClient(restClient, baseURL))))
	mux.Handle(landingv1connect.NewLandingServiceHandler(landing.NewLandingHandler(landingclient.NewLandingClient(restClient, baseURL))))
	mux.Handle(launchv1connect.NewLaunchServiceHandler(launch.NewLaunchHandler(launchclient.NewLaunchClient(restClient, baseURL))))
	mux.Handle(launcherv1connect.NewLauncherServiceHandler(launcher.NewLauncherHandler(launcherclient.NewLauncherClient(restClient, baseURL))))
	mux.Handle(launcher_configurationv1connect.NewLauncherConfigurationServiceHandler(launcher_configuration.NewLauncherConfigurationHandler(launcher_configurationclient.NewLauncherConfigurationClient(restClient, baseURL))))
	mux.Handle(locationv1connect.NewLocationServiceHandler(location.NewLocationHandler(locationclient.NewLocationClient(restClient, baseURL))))
	mux.Handle(padv1connect.NewPadServiceHandler(pad.NewPadHandler(padclient.NewPadClient(restClient, baseURL))))
	mux.Handle(payloadv1connect.NewPayloadServiceHandler(payload.NewPayloadHandler(payloadclient.NewPayloadClient(restClient, baseURL))))
	mux.Handle(programv1connect.NewProgramServiceHandler(program.NewProgramHandler(programclient.NewProgramClient(restClient, baseURL))))
	mux.Handle(space_stationv1connect.NewSpaceStationServiceHandler(space_station.NewSpaceStationHandler(space_stationclient.NewSpaceStationClient(restClient, baseURL))))
	mux.Handle(spacecraftv1connect.NewSpacecraftServiceHandler(spacecraft.NewSpacecraftHandler(spacecraftclient.NewSpacecraftClient(restClient, baseURL))))
	mux.Handle(spacewalkv1connect.NewSpacewalkServiceHandler(spacewalk.NewSpacewalkHandler(spacewalkclient.NewSpacewalkClient(restClient, baseURL))))
	mux.Handle(updatev1connect.NewUpdateServiceHandler(update.NewUpdateHandler(updateclient.NewUpdateClient(restClient, baseURL))))
	return mux
}

func main() {
	baseURL := envOr("LL2_BASE_URL", defaultBaseURL)
	addr := envOr("BHOLE_ADDR", defaultAddr)

	restClient := transport.NewRESTClient(baseURL, &http.Client{Timeout: upstreamTimeout})

	srv := &http.Server{
		Addr:              addr,
		Handler:           corsMiddleware(newMux(restClient, baseURL)),
		ReadHeaderTimeout: 10 * time.Second,
	}
	// Serve HTTP/1.1 and cleartext HTTP/2 (h2c) so both Connect-Web and gRPC clients work.
	srv.Protocols = new(http.Protocols)
	srv.Protocols.SetHTTP1(true)
	srv.Protocols.SetUnencryptedHTTP2(true)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	errCh := make(chan error, 1)
	go func() {
		errCh <- srv.ListenAndServe()
	}()
	log.Printf("bhole gateway listening on %s, proxying to %s", addr, baseURL)

	select {
	case err := <-errCh:
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server failed: %v", err)
		}
	case <-ctx.Done():
		stop()
		log.Println("shutting down...")
		shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
		defer cancel()
		if err := srv.Shutdown(shutdownCtx); err != nil {
			log.Printf("graceful shutdown failed: %v", err)
		}
	}
}
