// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: launcher_configuration/v1/launcher_configuration.proto

package launcher_configurationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pobochiigo/bhole/proto/launcher_configuration/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LauncherConfigurationServiceName is the fully-qualified name of the LauncherConfigurationService
	// service.
	LauncherConfigurationServiceName = "launcher_configuration.v1.LauncherConfigurationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LauncherConfigurationServiceListLauncherConfigurationsProcedure is the fully-qualified name of
	// the LauncherConfigurationService's ListLauncherConfigurations RPC.
	LauncherConfigurationServiceListLauncherConfigurationsProcedure = "/launcher_configuration.v1.LauncherConfigurationService/ListLauncherConfigurations"
	// LauncherConfigurationServiceGetLauncherConfigurationProcedure is the fully-qualified name of the
	// LauncherConfigurationService's GetLauncherConfiguration RPC.
	LauncherConfigurationServiceGetLauncherConfigurationProcedure = "/launcher_configuration.v1.LauncherConfigurationService/GetLauncherConfiguration"
)

// LauncherConfigurationServiceClient is a client for the
// launcher_configuration.v1.LauncherConfigurationService service.
type LauncherConfigurationServiceClient interface {
	ListLauncherConfigurations(context.Context, *connect.Request[v1.ListLauncherConfigurationsRequest]) (*connect.Response[v1.ListLauncherConfigurationsResponse], error)
	GetLauncherConfiguration(context.Context, *connect.Request[v1.GetLauncherConfigurationRequest]) (*connect.Response[v1.GetLauncherConfigurationResponse], error)
}

// NewLauncherConfigurationServiceClient constructs a client for the
// launcher_configuration.v1.LauncherConfigurationService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLauncherConfigurationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LauncherConfigurationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	launcherConfigurationServiceMethods := v1.File_launcher_configuration_v1_launcher_configuration_proto.Services().ByName("LauncherConfigurationService").Methods()
	return &launcherConfigurationServiceClient{
		listLauncherConfigurations: connect.NewClient[v1.ListLauncherConfigurationsRequest, v1.ListLauncherConfigurationsResponse](
			httpClient,
			baseURL+LauncherConfigurationServiceListLauncherConfigurationsProcedure,
			connect.WithSchema(launcherConfigurationServiceMethods.ByName("ListLauncherConfigurations")),
			connect.WithClientOptions(opts...),
		),
		getLauncherConfiguration: connect.NewClient[v1.GetLauncherConfigurationRequest, v1.GetLauncherConfigurationResponse](
			httpClient,
			baseURL+LauncherConfigurationServiceGetLauncherConfigurationProcedure,
			connect.WithSchema(launcherConfigurationServiceMethods.ByName("GetLauncherConfiguration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// launcherConfigurationServiceClient implements LauncherConfigurationServiceClient.
type launcherConfigurationServiceClient struct {
	listLauncherConfigurations *connect.Client[v1.ListLauncherConfigurationsRequest, v1.ListLauncherConfigurationsResponse]
	getLauncherConfiguration   *connect.Client[v1.GetLauncherConfigurationRequest, v1.GetLauncherConfigurationResponse]
}

// ListLauncherConfigurations calls
// launcher_configuration.v1.LauncherConfigurationService.ListLauncherConfigurations.
func (c *launcherConfigurationServiceClient) ListLauncherConfigurations(ctx context.Context, req *connect.Request[v1.ListLauncherConfigurationsRequest]) (*connect.Response[v1.ListLauncherConfigurationsResponse], error) {
	return c.listLauncherConfigurations.CallUnary(ctx, req)
}

// GetLauncherConfiguration calls
// launcher_configuration.v1.LauncherConfigurationService.GetLauncherConfiguration.
func (c *launcherConfigurationServiceClient) GetLauncherConfiguration(ctx context.Context, req *connect.Request[v1.GetLauncherConfigurationRequest]) (*connect.Response[v1.GetLauncherConfigurationResponse], error) {
	return c.getLauncherConfiguration.CallUnary(ctx, req)
}

// LauncherConfigurationServiceHandler is an implementation of the
// launcher_configuration.v1.LauncherConfigurationService service.
type LauncherConfigurationServiceHandler interface {
	ListLauncherConfigurations(context.Context, *connect.Request[v1.ListLauncherConfigurationsRequest]) (*connect.Response[v1.ListLauncherConfigurationsResponse], error)
	GetLauncherConfiguration(context.Context, *connect.Request[v1.GetLauncherConfigurationRequest]) (*connect.Response[v1.GetLauncherConfigurationResponse], error)
}

// NewLauncherConfigurationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLauncherConfigurationServiceHandler(svc LauncherConfigurationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	launcherConfigurationServiceMethods := v1.File_launcher_configuration_v1_launcher_configuration_proto.Services().ByName("LauncherConfigurationService").Methods()
	launcherConfigurationServiceListLauncherConfigurationsHandler := connect.NewUnaryHandler(
		LauncherConfigurationServiceListLauncherConfigurationsProcedure,
		svc.ListLauncherConfigurations,
		connect.WithSchema(launcherConfigurationServiceMethods.ByName("ListLauncherConfigurations")),
		connect.WithHandlerOptions(opts...),
	)
	launcherConfigurationServiceGetLauncherConfigurationHandler := connect.NewUnaryHandler(
		LauncherConfigurationServiceGetLauncherConfigurationProcedure,
		svc.GetLauncherConfiguration,
		connect.WithSchema(launcherConfigurationServiceMethods.ByName("GetLauncherConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/launcher_configuration.v1.LauncherConfigurationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LauncherConfigurationServiceListLauncherConfigurationsProcedure:
			launcherConfigurationServiceListLauncherConfigurationsHandler.ServeHTTP(w, r)
		case LauncherConfigurationServiceGetLauncherConfigurationProcedure:
			launcherConfigurationServiceGetLauncherConfigurationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLauncherConfigurationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLauncherConfigurationServiceHandler struct{}

func (UnimplementedLauncherConfigurationServiceHandler) ListLauncherConfigurations(context.Context, *connect.Request[v1.ListLauncherConfigurationsRequest]) (*connect.Response[v1.ListLauncherConfigurationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("launcher_configuration.v1.LauncherConfigurationService.ListLauncherConfigurations is not implemented"))
}

func (UnimplementedLauncherConfigurationServiceHandler) GetLauncherConfiguration(context.Context, *connect.Request[v1.GetLauncherConfigurationRequest]) (*connect.Response[v1.GetLauncherConfigurationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("launcher_configuration.v1.LauncherConfigurationService.GetLauncherConfiguration is not implemented"))
}
